// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="hls_sobel,hls_ip_2015_4,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=8.734000,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=27,HLS_SYN_DSP=0,HLS_SYN_FF=2197,HLS_SYN_LUT=3693}" *)

module hls_sobel (
        INPUT_STREAM_TDATA,
        INPUT_STREAM_TKEEP,
        INPUT_STREAM_TSTRB,
        INPUT_STREAM_TUSER,
        INPUT_STREAM_TLAST,
        INPUT_STREAM_TID,
        INPUT_STREAM_TDEST,
        OUTPUT_STREAM_TDATA,
        OUTPUT_STREAM_TKEEP,
        OUTPUT_STREAM_TSTRB,
        OUTPUT_STREAM_TUSER,
        OUTPUT_STREAM_TLAST,
        OUTPUT_STREAM_TID,
        OUTPUT_STREAM_TDEST,
        rows,
        cols,
        ap_clk,
        ap_rst_n,
        INPUT_STREAM_TVALID,
        INPUT_STREAM_TREADY,
        ap_start,
        OUTPUT_STREAM_TVALID,
        OUTPUT_STREAM_TREADY,
        ap_done,
        ap_idle,
        ap_ready
);

parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv4_0 = 4'b0000;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv32_B = 32'b1011;
parameter    ap_const_logic_1 = 1'b1;
parameter    ap_true = 1'b1;
parameter    ap_const_logic_0 = 1'b0;

input  [31:0] INPUT_STREAM_TDATA;
input  [3:0] INPUT_STREAM_TKEEP;
input  [3:0] INPUT_STREAM_TSTRB;
input  [0:0] INPUT_STREAM_TUSER;
input  [0:0] INPUT_STREAM_TLAST;
input  [0:0] INPUT_STREAM_TID;
input  [0:0] INPUT_STREAM_TDEST;
output  [31:0] OUTPUT_STREAM_TDATA;
output  [3:0] OUTPUT_STREAM_TKEEP;
output  [3:0] OUTPUT_STREAM_TSTRB;
output  [0:0] OUTPUT_STREAM_TUSER;
output  [0:0] OUTPUT_STREAM_TLAST;
output  [0:0] OUTPUT_STREAM_TID;
output  [0:0] OUTPUT_STREAM_TDEST;
input  [31:0] rows;
input  [31:0] cols;
input   ap_clk;
input   ap_rst_n;
input   INPUT_STREAM_TVALID;
output   INPUT_STREAM_TREADY;
input   ap_start;
output   OUTPUT_STREAM_TVALID;
input   OUTPUT_STREAM_TREADY;
output   ap_done;
output   ap_idle;
output   ap_ready;

reg ap_idle;
reg    ap_rst_n_inv;
wire    hls_sobel_AXIvideo2Mat_U0_ap_start;
wire    hls_sobel_AXIvideo2Mat_U0_ap_done;
wire    hls_sobel_AXIvideo2Mat_U0_ap_continue;
wire    hls_sobel_AXIvideo2Mat_U0_ap_idle;
wire    hls_sobel_AXIvideo2Mat_U0_ap_ready;
wire   [31:0] hls_sobel_AXIvideo2Mat_U0_INPUT_STREAM_TDATA;
wire    hls_sobel_AXIvideo2Mat_U0_INPUT_STREAM_TVALID;
wire    hls_sobel_AXIvideo2Mat_U0_INPUT_STREAM_TREADY;
wire   [3:0] hls_sobel_AXIvideo2Mat_U0_INPUT_STREAM_TKEEP;
wire   [3:0] hls_sobel_AXIvideo2Mat_U0_INPUT_STREAM_TSTRB;
wire   [0:0] hls_sobel_AXIvideo2Mat_U0_INPUT_STREAM_TUSER;
wire   [0:0] hls_sobel_AXIvideo2Mat_U0_INPUT_STREAM_TLAST;
wire   [0:0] hls_sobel_AXIvideo2Mat_U0_INPUT_STREAM_TID;
wire   [0:0] hls_sobel_AXIvideo2Mat_U0_INPUT_STREAM_TDEST;
wire   [10:0] hls_sobel_AXIvideo2Mat_U0_rows;
wire   [10:0] hls_sobel_AXIvideo2Mat_U0_cols;
wire   [7:0] hls_sobel_AXIvideo2Mat_U0_img_data_stream_0_V_din;
wire    hls_sobel_AXIvideo2Mat_U0_img_data_stream_0_V_full_n;
wire    hls_sobel_AXIvideo2Mat_U0_img_data_stream_0_V_write;
wire   [7:0] hls_sobel_AXIvideo2Mat_U0_img_data_stream_1_V_din;
wire    hls_sobel_AXIvideo2Mat_U0_img_data_stream_1_V_full_n;
wire    hls_sobel_AXIvideo2Mat_U0_img_data_stream_1_V_write;
wire   [7:0] hls_sobel_AXIvideo2Mat_U0_img_data_stream_2_V_din;
wire    hls_sobel_AXIvideo2Mat_U0_img_data_stream_2_V_full_n;
wire    hls_sobel_AXIvideo2Mat_U0_img_data_stream_2_V_write;
wire    hls_sobel_Sobel_U0_ap_start;
wire    hls_sobel_Sobel_U0_ap_done;
wire    hls_sobel_Sobel_U0_ap_continue;
wire    hls_sobel_Sobel_U0_ap_idle;
wire    hls_sobel_Sobel_U0_ap_ready;
wire   [10:0] hls_sobel_Sobel_U0_rows;
wire   [10:0] hls_sobel_Sobel_U0_cols;
wire   [7:0] hls_sobel_Sobel_U0_p_src_data_stream_0_V_dout;
wire    hls_sobel_Sobel_U0_p_src_data_stream_0_V_empty_n;
wire    hls_sobel_Sobel_U0_p_src_data_stream_0_V_read;
wire   [7:0] hls_sobel_Sobel_U0_p_src_data_stream_1_V_dout;
wire    hls_sobel_Sobel_U0_p_src_data_stream_1_V_empty_n;
wire    hls_sobel_Sobel_U0_p_src_data_stream_1_V_read;
wire   [7:0] hls_sobel_Sobel_U0_p_src_data_stream_2_V_dout;
wire    hls_sobel_Sobel_U0_p_src_data_stream_2_V_empty_n;
wire    hls_sobel_Sobel_U0_p_src_data_stream_2_V_read;
wire   [7:0] hls_sobel_Sobel_U0_p_dst_data_stream_0_V_din;
wire    hls_sobel_Sobel_U0_p_dst_data_stream_0_V_full_n;
wire    hls_sobel_Sobel_U0_p_dst_data_stream_0_V_write;
wire   [7:0] hls_sobel_Sobel_U0_p_dst_data_stream_1_V_din;
wire    hls_sobel_Sobel_U0_p_dst_data_stream_1_V_full_n;
wire    hls_sobel_Sobel_U0_p_dst_data_stream_1_V_write;
wire   [7:0] hls_sobel_Sobel_U0_p_dst_data_stream_2_V_din;
wire    hls_sobel_Sobel_U0_p_dst_data_stream_2_V_full_n;
wire    hls_sobel_Sobel_U0_p_dst_data_stream_2_V_write;
wire    hls_sobel_SubS_U0_ap_start;
wire    hls_sobel_SubS_U0_ap_done;
wire    hls_sobel_SubS_U0_ap_continue;
wire    hls_sobel_SubS_U0_ap_idle;
wire    hls_sobel_SubS_U0_ap_ready;
wire   [10:0] hls_sobel_SubS_U0_rows;
wire   [10:0] hls_sobel_SubS_U0_cols;
wire   [7:0] hls_sobel_SubS_U0_src_data_stream_0_V_dout;
wire    hls_sobel_SubS_U0_src_data_stream_0_V_empty_n;
wire    hls_sobel_SubS_U0_src_data_stream_0_V_read;
wire   [7:0] hls_sobel_SubS_U0_src_data_stream_1_V_dout;
wire    hls_sobel_SubS_U0_src_data_stream_1_V_empty_n;
wire    hls_sobel_SubS_U0_src_data_stream_1_V_read;
wire   [7:0] hls_sobel_SubS_U0_src_data_stream_2_V_dout;
wire    hls_sobel_SubS_U0_src_data_stream_2_V_empty_n;
wire    hls_sobel_SubS_U0_src_data_stream_2_V_read;
wire   [7:0] hls_sobel_SubS_U0_dst_data_stream_0_V_din;
wire    hls_sobel_SubS_U0_dst_data_stream_0_V_full_n;
wire    hls_sobel_SubS_U0_dst_data_stream_0_V_write;
wire   [7:0] hls_sobel_SubS_U0_dst_data_stream_1_V_din;
wire    hls_sobel_SubS_U0_dst_data_stream_1_V_full_n;
wire    hls_sobel_SubS_U0_dst_data_stream_1_V_write;
wire   [7:0] hls_sobel_SubS_U0_dst_data_stream_2_V_din;
wire    hls_sobel_SubS_U0_dst_data_stream_2_V_full_n;
wire    hls_sobel_SubS_U0_dst_data_stream_2_V_write;
wire    hls_sobel_Scale_1080_1920_32_32_int_U0_ap_start;
wire    hls_sobel_Scale_1080_1920_32_32_int_U0_ap_done;
wire    hls_sobel_Scale_1080_1920_32_32_int_U0_ap_continue;
wire    hls_sobel_Scale_1080_1920_32_32_int_U0_ap_idle;
wire    hls_sobel_Scale_1080_1920_32_32_int_U0_ap_ready;
wire   [10:0] hls_sobel_Scale_1080_1920_32_32_int_U0_rows;
wire   [10:0] hls_sobel_Scale_1080_1920_32_32_int_U0_cols;
wire   [7:0] hls_sobel_Scale_1080_1920_32_32_int_U0_src_data_stream_0_V_dout;
wire    hls_sobel_Scale_1080_1920_32_32_int_U0_src_data_stream_0_V_empty_n;
wire    hls_sobel_Scale_1080_1920_32_32_int_U0_src_data_stream_0_V_read;
wire   [7:0] hls_sobel_Scale_1080_1920_32_32_int_U0_src_data_stream_1_V_dout;
wire    hls_sobel_Scale_1080_1920_32_32_int_U0_src_data_stream_1_V_empty_n;
wire    hls_sobel_Scale_1080_1920_32_32_int_U0_src_data_stream_1_V_read;
wire   [7:0] hls_sobel_Scale_1080_1920_32_32_int_U0_src_data_stream_2_V_dout;
wire    hls_sobel_Scale_1080_1920_32_32_int_U0_src_data_stream_2_V_empty_n;
wire    hls_sobel_Scale_1080_1920_32_32_int_U0_src_data_stream_2_V_read;
wire   [7:0] hls_sobel_Scale_1080_1920_32_32_int_U0_dst_data_stream_0_V_din;
wire    hls_sobel_Scale_1080_1920_32_32_int_U0_dst_data_stream_0_V_full_n;
wire    hls_sobel_Scale_1080_1920_32_32_int_U0_dst_data_stream_0_V_write;
wire   [7:0] hls_sobel_Scale_1080_1920_32_32_int_U0_dst_data_stream_1_V_din;
wire    hls_sobel_Scale_1080_1920_32_32_int_U0_dst_data_stream_1_V_full_n;
wire    hls_sobel_Scale_1080_1920_32_32_int_U0_dst_data_stream_1_V_write;
wire   [7:0] hls_sobel_Scale_1080_1920_32_32_int_U0_dst_data_stream_2_V_din;
wire    hls_sobel_Scale_1080_1920_32_32_int_U0_dst_data_stream_2_V_full_n;
wire    hls_sobel_Scale_1080_1920_32_32_int_U0_dst_data_stream_2_V_write;
wire    hls_sobel_Erode_32_32_1080_1920_U0_ap_start;
wire    hls_sobel_Erode_32_32_1080_1920_U0_ap_done;
wire    hls_sobel_Erode_32_32_1080_1920_U0_ap_continue;
wire    hls_sobel_Erode_32_32_1080_1920_U0_ap_idle;
wire    hls_sobel_Erode_32_32_1080_1920_U0_ap_ready;
wire   [10:0] hls_sobel_Erode_32_32_1080_1920_U0_rows;
wire   [10:0] hls_sobel_Erode_32_32_1080_1920_U0_cols;
wire   [7:0] hls_sobel_Erode_32_32_1080_1920_U0_p_src_data_stream_0_V_dout;
wire    hls_sobel_Erode_32_32_1080_1920_U0_p_src_data_stream_0_V_empty_n;
wire    hls_sobel_Erode_32_32_1080_1920_U0_p_src_data_stream_0_V_read;
wire   [7:0] hls_sobel_Erode_32_32_1080_1920_U0_p_src_data_stream_1_V_dout;
wire    hls_sobel_Erode_32_32_1080_1920_U0_p_src_data_stream_1_V_empty_n;
wire    hls_sobel_Erode_32_32_1080_1920_U0_p_src_data_stream_1_V_read;
wire   [7:0] hls_sobel_Erode_32_32_1080_1920_U0_p_src_data_stream_2_V_dout;
wire    hls_sobel_Erode_32_32_1080_1920_U0_p_src_data_stream_2_V_empty_n;
wire    hls_sobel_Erode_32_32_1080_1920_U0_p_src_data_stream_2_V_read;
wire   [7:0] hls_sobel_Erode_32_32_1080_1920_U0_p_dst_data_stream_0_V_din;
wire    hls_sobel_Erode_32_32_1080_1920_U0_p_dst_data_stream_0_V_full_n;
wire    hls_sobel_Erode_32_32_1080_1920_U0_p_dst_data_stream_0_V_write;
wire   [7:0] hls_sobel_Erode_32_32_1080_1920_U0_p_dst_data_stream_1_V_din;
wire    hls_sobel_Erode_32_32_1080_1920_U0_p_dst_data_stream_1_V_full_n;
wire    hls_sobel_Erode_32_32_1080_1920_U0_p_dst_data_stream_1_V_write;
wire   [7:0] hls_sobel_Erode_32_32_1080_1920_U0_p_dst_data_stream_2_V_din;
wire    hls_sobel_Erode_32_32_1080_1920_U0_p_dst_data_stream_2_V_full_n;
wire    hls_sobel_Erode_32_32_1080_1920_U0_p_dst_data_stream_2_V_write;
wire    hls_sobel_Dilate_32_32_1080_1920_U0_ap_start;
wire    hls_sobel_Dilate_32_32_1080_1920_U0_ap_done;
wire    hls_sobel_Dilate_32_32_1080_1920_U0_ap_continue;
wire    hls_sobel_Dilate_32_32_1080_1920_U0_ap_idle;
wire    hls_sobel_Dilate_32_32_1080_1920_U0_ap_ready;
wire   [10:0] hls_sobel_Dilate_32_32_1080_1920_U0_rows;
wire   [10:0] hls_sobel_Dilate_32_32_1080_1920_U0_cols;
wire   [7:0] hls_sobel_Dilate_32_32_1080_1920_U0_p_src_data_stream_0_V_dout;
wire    hls_sobel_Dilate_32_32_1080_1920_U0_p_src_data_stream_0_V_empty_n;
wire    hls_sobel_Dilate_32_32_1080_1920_U0_p_src_data_stream_0_V_read;
wire   [7:0] hls_sobel_Dilate_32_32_1080_1920_U0_p_src_data_stream_1_V_dout;
wire    hls_sobel_Dilate_32_32_1080_1920_U0_p_src_data_stream_1_V_empty_n;
wire    hls_sobel_Dilate_32_32_1080_1920_U0_p_src_data_stream_1_V_read;
wire   [7:0] hls_sobel_Dilate_32_32_1080_1920_U0_p_src_data_stream_2_V_dout;
wire    hls_sobel_Dilate_32_32_1080_1920_U0_p_src_data_stream_2_V_empty_n;
wire    hls_sobel_Dilate_32_32_1080_1920_U0_p_src_data_stream_2_V_read;
wire   [7:0] hls_sobel_Dilate_32_32_1080_1920_U0_p_dst_data_stream_0_V_din;
wire    hls_sobel_Dilate_32_32_1080_1920_U0_p_dst_data_stream_0_V_full_n;
wire    hls_sobel_Dilate_32_32_1080_1920_U0_p_dst_data_stream_0_V_write;
wire   [7:0] hls_sobel_Dilate_32_32_1080_1920_U0_p_dst_data_stream_1_V_din;
wire    hls_sobel_Dilate_32_32_1080_1920_U0_p_dst_data_stream_1_V_full_n;
wire    hls_sobel_Dilate_32_32_1080_1920_U0_p_dst_data_stream_1_V_write;
wire   [7:0] hls_sobel_Dilate_32_32_1080_1920_U0_p_dst_data_stream_2_V_din;
wire    hls_sobel_Dilate_32_32_1080_1920_U0_p_dst_data_stream_2_V_full_n;
wire    hls_sobel_Dilate_32_32_1080_1920_U0_p_dst_data_stream_2_V_write;
wire    hls_sobel_Mat2AXIvideo_U0_ap_start;
wire    hls_sobel_Mat2AXIvideo_U0_ap_done;
wire    hls_sobel_Mat2AXIvideo_U0_ap_continue;
wire    hls_sobel_Mat2AXIvideo_U0_ap_idle;
wire    hls_sobel_Mat2AXIvideo_U0_ap_ready;
wire   [10:0] hls_sobel_Mat2AXIvideo_U0_rows;
wire   [10:0] hls_sobel_Mat2AXIvideo_U0_cols;
wire   [7:0] hls_sobel_Mat2AXIvideo_U0_img_data_stream_0_V_dout;
wire    hls_sobel_Mat2AXIvideo_U0_img_data_stream_0_V_empty_n;
wire    hls_sobel_Mat2AXIvideo_U0_img_data_stream_0_V_read;
wire   [7:0] hls_sobel_Mat2AXIvideo_U0_img_data_stream_1_V_dout;
wire    hls_sobel_Mat2AXIvideo_U0_img_data_stream_1_V_empty_n;
wire    hls_sobel_Mat2AXIvideo_U0_img_data_stream_1_V_read;
wire   [7:0] hls_sobel_Mat2AXIvideo_U0_img_data_stream_2_V_dout;
wire    hls_sobel_Mat2AXIvideo_U0_img_data_stream_2_V_empty_n;
wire    hls_sobel_Mat2AXIvideo_U0_img_data_stream_2_V_read;
wire   [31:0] hls_sobel_Mat2AXIvideo_U0_OUTPUT_STREAM_TDATA;
wire    hls_sobel_Mat2AXIvideo_U0_OUTPUT_STREAM_TVALID;
wire    hls_sobel_Mat2AXIvideo_U0_OUTPUT_STREAM_TREADY;
wire   [3:0] hls_sobel_Mat2AXIvideo_U0_OUTPUT_STREAM_TKEEP;
wire   [3:0] hls_sobel_Mat2AXIvideo_U0_OUTPUT_STREAM_TSTRB;
wire   [0:0] hls_sobel_Mat2AXIvideo_U0_OUTPUT_STREAM_TUSER;
wire   [0:0] hls_sobel_Mat2AXIvideo_U0_OUTPUT_STREAM_TLAST;
wire   [0:0] hls_sobel_Mat2AXIvideo_U0_OUTPUT_STREAM_TID;
wire   [0:0] hls_sobel_Mat2AXIvideo_U0_OUTPUT_STREAM_TDEST;
wire    ap_sig_hs_continue;
wire    img_0_data_stream_0_V_U_ap_dummy_ce;
wire   [7:0] img_0_data_stream_0_V_din;
wire    img_0_data_stream_0_V_full_n;
wire    img_0_data_stream_0_V_write;
wire   [7:0] img_0_data_stream_0_V_dout;
wire    img_0_data_stream_0_V_empty_n;
wire    img_0_data_stream_0_V_read;
wire    img_0_data_stream_1_V_U_ap_dummy_ce;
wire   [7:0] img_0_data_stream_1_V_din;
wire    img_0_data_stream_1_V_full_n;
wire    img_0_data_stream_1_V_write;
wire   [7:0] img_0_data_stream_1_V_dout;
wire    img_0_data_stream_1_V_empty_n;
wire    img_0_data_stream_1_V_read;
wire    img_0_data_stream_2_V_U_ap_dummy_ce;
wire   [7:0] img_0_data_stream_2_V_din;
wire    img_0_data_stream_2_V_full_n;
wire    img_0_data_stream_2_V_write;
wire   [7:0] img_0_data_stream_2_V_dout;
wire    img_0_data_stream_2_V_empty_n;
wire    img_0_data_stream_2_V_read;
wire    img_1_data_stream_0_V_U_ap_dummy_ce;
wire   [7:0] img_1_data_stream_0_V_din;
wire    img_1_data_stream_0_V_full_n;
wire    img_1_data_stream_0_V_write;
wire   [7:0] img_1_data_stream_0_V_dout;
wire    img_1_data_stream_0_V_empty_n;
wire    img_1_data_stream_0_V_read;
wire    img_1_data_stream_1_V_U_ap_dummy_ce;
wire   [7:0] img_1_data_stream_1_V_din;
wire    img_1_data_stream_1_V_full_n;
wire    img_1_data_stream_1_V_write;
wire   [7:0] img_1_data_stream_1_V_dout;
wire    img_1_data_stream_1_V_empty_n;
wire    img_1_data_stream_1_V_read;
wire    img_1_data_stream_2_V_U_ap_dummy_ce;
wire   [7:0] img_1_data_stream_2_V_din;
wire    img_1_data_stream_2_V_full_n;
wire    img_1_data_stream_2_V_write;
wire   [7:0] img_1_data_stream_2_V_dout;
wire    img_1_data_stream_2_V_empty_n;
wire    img_1_data_stream_2_V_read;
wire    img_2_data_stream_0_V_U_ap_dummy_ce;
wire   [7:0] img_2_data_stream_0_V_din;
wire    img_2_data_stream_0_V_full_n;
wire    img_2_data_stream_0_V_write;
wire   [7:0] img_2_data_stream_0_V_dout;
wire    img_2_data_stream_0_V_empty_n;
wire    img_2_data_stream_0_V_read;
wire    img_2_data_stream_1_V_U_ap_dummy_ce;
wire   [7:0] img_2_data_stream_1_V_din;
wire    img_2_data_stream_1_V_full_n;
wire    img_2_data_stream_1_V_write;
wire   [7:0] img_2_data_stream_1_V_dout;
wire    img_2_data_stream_1_V_empty_n;
wire    img_2_data_stream_1_V_read;
wire    img_2_data_stream_2_V_U_ap_dummy_ce;
wire   [7:0] img_2_data_stream_2_V_din;
wire    img_2_data_stream_2_V_full_n;
wire    img_2_data_stream_2_V_write;
wire   [7:0] img_2_data_stream_2_V_dout;
wire    img_2_data_stream_2_V_empty_n;
wire    img_2_data_stream_2_V_read;
wire    img_3_data_stream_0_V_U_ap_dummy_ce;
wire   [7:0] img_3_data_stream_0_V_din;
wire    img_3_data_stream_0_V_full_n;
wire    img_3_data_stream_0_V_write;
wire   [7:0] img_3_data_stream_0_V_dout;
wire    img_3_data_stream_0_V_empty_n;
wire    img_3_data_stream_0_V_read;
wire    img_3_data_stream_1_V_U_ap_dummy_ce;
wire   [7:0] img_3_data_stream_1_V_din;
wire    img_3_data_stream_1_V_full_n;
wire    img_3_data_stream_1_V_write;
wire   [7:0] img_3_data_stream_1_V_dout;
wire    img_3_data_stream_1_V_empty_n;
wire    img_3_data_stream_1_V_read;
wire    img_3_data_stream_2_V_U_ap_dummy_ce;
wire   [7:0] img_3_data_stream_2_V_din;
wire    img_3_data_stream_2_V_full_n;
wire    img_3_data_stream_2_V_write;
wire   [7:0] img_3_data_stream_2_V_dout;
wire    img_3_data_stream_2_V_empty_n;
wire    img_3_data_stream_2_V_read;
wire    img_4_data_stream_0_V_U_ap_dummy_ce;
wire   [7:0] img_4_data_stream_0_V_din;
wire    img_4_data_stream_0_V_full_n;
wire    img_4_data_stream_0_V_write;
wire   [7:0] img_4_data_stream_0_V_dout;
wire    img_4_data_stream_0_V_empty_n;
wire    img_4_data_stream_0_V_read;
wire    img_4_data_stream_1_V_U_ap_dummy_ce;
wire   [7:0] img_4_data_stream_1_V_din;
wire    img_4_data_stream_1_V_full_n;
wire    img_4_data_stream_1_V_write;
wire   [7:0] img_4_data_stream_1_V_dout;
wire    img_4_data_stream_1_V_empty_n;
wire    img_4_data_stream_1_V_read;
wire    img_4_data_stream_2_V_U_ap_dummy_ce;
wire   [7:0] img_4_data_stream_2_V_din;
wire    img_4_data_stream_2_V_full_n;
wire    img_4_data_stream_2_V_write;
wire   [7:0] img_4_data_stream_2_V_dout;
wire    img_4_data_stream_2_V_empty_n;
wire    img_4_data_stream_2_V_read;
wire    img_5_data_stream_0_V_U_ap_dummy_ce;
wire   [7:0] img_5_data_stream_0_V_din;
wire    img_5_data_stream_0_V_full_n;
wire    img_5_data_stream_0_V_write;
wire   [7:0] img_5_data_stream_0_V_dout;
wire    img_5_data_stream_0_V_empty_n;
wire    img_5_data_stream_0_V_read;
wire    img_5_data_stream_1_V_U_ap_dummy_ce;
wire   [7:0] img_5_data_stream_1_V_din;
wire    img_5_data_stream_1_V_full_n;
wire    img_5_data_stream_1_V_write;
wire   [7:0] img_5_data_stream_1_V_dout;
wire    img_5_data_stream_1_V_empty_n;
wire    img_5_data_stream_1_V_read;
wire    img_5_data_stream_2_V_U_ap_dummy_ce;
wire   [7:0] img_5_data_stream_2_V_din;
wire    img_5_data_stream_2_V_full_n;
wire    img_5_data_stream_2_V_write;
wire   [7:0] img_5_data_stream_2_V_dout;
wire    img_5_data_stream_2_V_empty_n;
wire    img_5_data_stream_2_V_read;
reg    ap_reg_procdone_hls_sobel_AXIvideo2Mat_U0 = 1'b0;
reg    ap_sig_hs_done;
reg    ap_reg_procdone_hls_sobel_Sobel_U0 = 1'b0;
reg    ap_reg_procdone_hls_sobel_SubS_U0 = 1'b0;
reg    ap_reg_procdone_hls_sobel_Scale_1080_1920_32_32_int_U0 = 1'b0;
reg    ap_reg_procdone_hls_sobel_Erode_32_32_1080_1920_U0 = 1'b0;
reg    ap_reg_procdone_hls_sobel_Dilate_32_32_1080_1920_U0 = 1'b0;
reg    ap_reg_procdone_hls_sobel_Mat2AXIvideo_U0 = 1'b0;
reg    ap_CS;
wire    ap_sig_top_allready;


hls_sobel_AXIvideo2Mat hls_sobel_AXIvideo2Mat_U0(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst_n_inv ),
    .ap_start( hls_sobel_AXIvideo2Mat_U0_ap_start ),
    .ap_done( hls_sobel_AXIvideo2Mat_U0_ap_done ),
    .ap_continue( hls_sobel_AXIvideo2Mat_U0_ap_continue ),
    .ap_idle( hls_sobel_AXIvideo2Mat_U0_ap_idle ),
    .ap_ready( hls_sobel_AXIvideo2Mat_U0_ap_ready ),
    .INPUT_STREAM_TDATA( hls_sobel_AXIvideo2Mat_U0_INPUT_STREAM_TDATA ),
    .INPUT_STREAM_TVALID( hls_sobel_AXIvideo2Mat_U0_INPUT_STREAM_TVALID ),
    .INPUT_STREAM_TREADY( hls_sobel_AXIvideo2Mat_U0_INPUT_STREAM_TREADY ),
    .INPUT_STREAM_TKEEP( hls_sobel_AXIvideo2Mat_U0_INPUT_STREAM_TKEEP ),
    .INPUT_STREAM_TSTRB( hls_sobel_AXIvideo2Mat_U0_INPUT_STREAM_TSTRB ),
    .INPUT_STREAM_TUSER( hls_sobel_AXIvideo2Mat_U0_INPUT_STREAM_TUSER ),
    .INPUT_STREAM_TLAST( hls_sobel_AXIvideo2Mat_U0_INPUT_STREAM_TLAST ),
    .INPUT_STREAM_TID( hls_sobel_AXIvideo2Mat_U0_INPUT_STREAM_TID ),
    .INPUT_STREAM_TDEST( hls_sobel_AXIvideo2Mat_U0_INPUT_STREAM_TDEST ),
    .rows( hls_sobel_AXIvideo2Mat_U0_rows ),
    .cols( hls_sobel_AXIvideo2Mat_U0_cols ),
    .img_data_stream_0_V_din( hls_sobel_AXIvideo2Mat_U0_img_data_stream_0_V_din ),
    .img_data_stream_0_V_full_n( hls_sobel_AXIvideo2Mat_U0_img_data_stream_0_V_full_n ),
    .img_data_stream_0_V_write( hls_sobel_AXIvideo2Mat_U0_img_data_stream_0_V_write ),
    .img_data_stream_1_V_din( hls_sobel_AXIvideo2Mat_U0_img_data_stream_1_V_din ),
    .img_data_stream_1_V_full_n( hls_sobel_AXIvideo2Mat_U0_img_data_stream_1_V_full_n ),
    .img_data_stream_1_V_write( hls_sobel_AXIvideo2Mat_U0_img_data_stream_1_V_write ),
    .img_data_stream_2_V_din( hls_sobel_AXIvideo2Mat_U0_img_data_stream_2_V_din ),
    .img_data_stream_2_V_full_n( hls_sobel_AXIvideo2Mat_U0_img_data_stream_2_V_full_n ),
    .img_data_stream_2_V_write( hls_sobel_AXIvideo2Mat_U0_img_data_stream_2_V_write )
);

hls_sobel_Sobel hls_sobel_Sobel_U0(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst_n_inv ),
    .ap_start( hls_sobel_Sobel_U0_ap_start ),
    .ap_done( hls_sobel_Sobel_U0_ap_done ),
    .ap_continue( hls_sobel_Sobel_U0_ap_continue ),
    .ap_idle( hls_sobel_Sobel_U0_ap_idle ),
    .ap_ready( hls_sobel_Sobel_U0_ap_ready ),
    .rows( hls_sobel_Sobel_U0_rows ),
    .cols( hls_sobel_Sobel_U0_cols ),
    .p_src_data_stream_0_V_dout( hls_sobel_Sobel_U0_p_src_data_stream_0_V_dout ),
    .p_src_data_stream_0_V_empty_n( hls_sobel_Sobel_U0_p_src_data_stream_0_V_empty_n ),
    .p_src_data_stream_0_V_read( hls_sobel_Sobel_U0_p_src_data_stream_0_V_read ),
    .p_src_data_stream_1_V_dout( hls_sobel_Sobel_U0_p_src_data_stream_1_V_dout ),
    .p_src_data_stream_1_V_empty_n( hls_sobel_Sobel_U0_p_src_data_stream_1_V_empty_n ),
    .p_src_data_stream_1_V_read( hls_sobel_Sobel_U0_p_src_data_stream_1_V_read ),
    .p_src_data_stream_2_V_dout( hls_sobel_Sobel_U0_p_src_data_stream_2_V_dout ),
    .p_src_data_stream_2_V_empty_n( hls_sobel_Sobel_U0_p_src_data_stream_2_V_empty_n ),
    .p_src_data_stream_2_V_read( hls_sobel_Sobel_U0_p_src_data_stream_2_V_read ),
    .p_dst_data_stream_0_V_din( hls_sobel_Sobel_U0_p_dst_data_stream_0_V_din ),
    .p_dst_data_stream_0_V_full_n( hls_sobel_Sobel_U0_p_dst_data_stream_0_V_full_n ),
    .p_dst_data_stream_0_V_write( hls_sobel_Sobel_U0_p_dst_data_stream_0_V_write ),
    .p_dst_data_stream_1_V_din( hls_sobel_Sobel_U0_p_dst_data_stream_1_V_din ),
    .p_dst_data_stream_1_V_full_n( hls_sobel_Sobel_U0_p_dst_data_stream_1_V_full_n ),
    .p_dst_data_stream_1_V_write( hls_sobel_Sobel_U0_p_dst_data_stream_1_V_write ),
    .p_dst_data_stream_2_V_din( hls_sobel_Sobel_U0_p_dst_data_stream_2_V_din ),
    .p_dst_data_stream_2_V_full_n( hls_sobel_Sobel_U0_p_dst_data_stream_2_V_full_n ),
    .p_dst_data_stream_2_V_write( hls_sobel_Sobel_U0_p_dst_data_stream_2_V_write )
);

hls_sobel_SubS hls_sobel_SubS_U0(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst_n_inv ),
    .ap_start( hls_sobel_SubS_U0_ap_start ),
    .ap_done( hls_sobel_SubS_U0_ap_done ),
    .ap_continue( hls_sobel_SubS_U0_ap_continue ),
    .ap_idle( hls_sobel_SubS_U0_ap_idle ),
    .ap_ready( hls_sobel_SubS_U0_ap_ready ),
    .rows( hls_sobel_SubS_U0_rows ),
    .cols( hls_sobel_SubS_U0_cols ),
    .src_data_stream_0_V_dout( hls_sobel_SubS_U0_src_data_stream_0_V_dout ),
    .src_data_stream_0_V_empty_n( hls_sobel_SubS_U0_src_data_stream_0_V_empty_n ),
    .src_data_stream_0_V_read( hls_sobel_SubS_U0_src_data_stream_0_V_read ),
    .src_data_stream_1_V_dout( hls_sobel_SubS_U0_src_data_stream_1_V_dout ),
    .src_data_stream_1_V_empty_n( hls_sobel_SubS_U0_src_data_stream_1_V_empty_n ),
    .src_data_stream_1_V_read( hls_sobel_SubS_U0_src_data_stream_1_V_read ),
    .src_data_stream_2_V_dout( hls_sobel_SubS_U0_src_data_stream_2_V_dout ),
    .src_data_stream_2_V_empty_n( hls_sobel_SubS_U0_src_data_stream_2_V_empty_n ),
    .src_data_stream_2_V_read( hls_sobel_SubS_U0_src_data_stream_2_V_read ),
    .dst_data_stream_0_V_din( hls_sobel_SubS_U0_dst_data_stream_0_V_din ),
    .dst_data_stream_0_V_full_n( hls_sobel_SubS_U0_dst_data_stream_0_V_full_n ),
    .dst_data_stream_0_V_write( hls_sobel_SubS_U0_dst_data_stream_0_V_write ),
    .dst_data_stream_1_V_din( hls_sobel_SubS_U0_dst_data_stream_1_V_din ),
    .dst_data_stream_1_V_full_n( hls_sobel_SubS_U0_dst_data_stream_1_V_full_n ),
    .dst_data_stream_1_V_write( hls_sobel_SubS_U0_dst_data_stream_1_V_write ),
    .dst_data_stream_2_V_din( hls_sobel_SubS_U0_dst_data_stream_2_V_din ),
    .dst_data_stream_2_V_full_n( hls_sobel_SubS_U0_dst_data_stream_2_V_full_n ),
    .dst_data_stream_2_V_write( hls_sobel_SubS_U0_dst_data_stream_2_V_write )
);

hls_sobel_Scale_1080_1920_32_32_int_s hls_sobel_Scale_1080_1920_32_32_int_U0(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst_n_inv ),
    .ap_start( hls_sobel_Scale_1080_1920_32_32_int_U0_ap_start ),
    .ap_done( hls_sobel_Scale_1080_1920_32_32_int_U0_ap_done ),
    .ap_continue( hls_sobel_Scale_1080_1920_32_32_int_U0_ap_continue ),
    .ap_idle( hls_sobel_Scale_1080_1920_32_32_int_U0_ap_idle ),
    .ap_ready( hls_sobel_Scale_1080_1920_32_32_int_U0_ap_ready ),
    .rows( hls_sobel_Scale_1080_1920_32_32_int_U0_rows ),
    .cols( hls_sobel_Scale_1080_1920_32_32_int_U0_cols ),
    .src_data_stream_0_V_dout( hls_sobel_Scale_1080_1920_32_32_int_U0_src_data_stream_0_V_dout ),
    .src_data_stream_0_V_empty_n( hls_sobel_Scale_1080_1920_32_32_int_U0_src_data_stream_0_V_empty_n ),
    .src_data_stream_0_V_read( hls_sobel_Scale_1080_1920_32_32_int_U0_src_data_stream_0_V_read ),
    .src_data_stream_1_V_dout( hls_sobel_Scale_1080_1920_32_32_int_U0_src_data_stream_1_V_dout ),
    .src_data_stream_1_V_empty_n( hls_sobel_Scale_1080_1920_32_32_int_U0_src_data_stream_1_V_empty_n ),
    .src_data_stream_1_V_read( hls_sobel_Scale_1080_1920_32_32_int_U0_src_data_stream_1_V_read ),
    .src_data_stream_2_V_dout( hls_sobel_Scale_1080_1920_32_32_int_U0_src_data_stream_2_V_dout ),
    .src_data_stream_2_V_empty_n( hls_sobel_Scale_1080_1920_32_32_int_U0_src_data_stream_2_V_empty_n ),
    .src_data_stream_2_V_read( hls_sobel_Scale_1080_1920_32_32_int_U0_src_data_stream_2_V_read ),
    .dst_data_stream_0_V_din( hls_sobel_Scale_1080_1920_32_32_int_U0_dst_data_stream_0_V_din ),
    .dst_data_stream_0_V_full_n( hls_sobel_Scale_1080_1920_32_32_int_U0_dst_data_stream_0_V_full_n ),
    .dst_data_stream_0_V_write( hls_sobel_Scale_1080_1920_32_32_int_U0_dst_data_stream_0_V_write ),
    .dst_data_stream_1_V_din( hls_sobel_Scale_1080_1920_32_32_int_U0_dst_data_stream_1_V_din ),
    .dst_data_stream_1_V_full_n( hls_sobel_Scale_1080_1920_32_32_int_U0_dst_data_stream_1_V_full_n ),
    .dst_data_stream_1_V_write( hls_sobel_Scale_1080_1920_32_32_int_U0_dst_data_stream_1_V_write ),
    .dst_data_stream_2_V_din( hls_sobel_Scale_1080_1920_32_32_int_U0_dst_data_stream_2_V_din ),
    .dst_data_stream_2_V_full_n( hls_sobel_Scale_1080_1920_32_32_int_U0_dst_data_stream_2_V_full_n ),
    .dst_data_stream_2_V_write( hls_sobel_Scale_1080_1920_32_32_int_U0_dst_data_stream_2_V_write )
);

hls_sobel_Erode_32_32_1080_1920_s hls_sobel_Erode_32_32_1080_1920_U0(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst_n_inv ),
    .ap_start( hls_sobel_Erode_32_32_1080_1920_U0_ap_start ),
    .ap_done( hls_sobel_Erode_32_32_1080_1920_U0_ap_done ),
    .ap_continue( hls_sobel_Erode_32_32_1080_1920_U0_ap_continue ),
    .ap_idle( hls_sobel_Erode_32_32_1080_1920_U0_ap_idle ),
    .ap_ready( hls_sobel_Erode_32_32_1080_1920_U0_ap_ready ),
    .rows( hls_sobel_Erode_32_32_1080_1920_U0_rows ),
    .cols( hls_sobel_Erode_32_32_1080_1920_U0_cols ),
    .p_src_data_stream_0_V_dout( hls_sobel_Erode_32_32_1080_1920_U0_p_src_data_stream_0_V_dout ),
    .p_src_data_stream_0_V_empty_n( hls_sobel_Erode_32_32_1080_1920_U0_p_src_data_stream_0_V_empty_n ),
    .p_src_data_stream_0_V_read( hls_sobel_Erode_32_32_1080_1920_U0_p_src_data_stream_0_V_read ),
    .p_src_data_stream_1_V_dout( hls_sobel_Erode_32_32_1080_1920_U0_p_src_data_stream_1_V_dout ),
    .p_src_data_stream_1_V_empty_n( hls_sobel_Erode_32_32_1080_1920_U0_p_src_data_stream_1_V_empty_n ),
    .p_src_data_stream_1_V_read( hls_sobel_Erode_32_32_1080_1920_U0_p_src_data_stream_1_V_read ),
    .p_src_data_stream_2_V_dout( hls_sobel_Erode_32_32_1080_1920_U0_p_src_data_stream_2_V_dout ),
    .p_src_data_stream_2_V_empty_n( hls_sobel_Erode_32_32_1080_1920_U0_p_src_data_stream_2_V_empty_n ),
    .p_src_data_stream_2_V_read( hls_sobel_Erode_32_32_1080_1920_U0_p_src_data_stream_2_V_read ),
    .p_dst_data_stream_0_V_din( hls_sobel_Erode_32_32_1080_1920_U0_p_dst_data_stream_0_V_din ),
    .p_dst_data_stream_0_V_full_n( hls_sobel_Erode_32_32_1080_1920_U0_p_dst_data_stream_0_V_full_n ),
    .p_dst_data_stream_0_V_write( hls_sobel_Erode_32_32_1080_1920_U0_p_dst_data_stream_0_V_write ),
    .p_dst_data_stream_1_V_din( hls_sobel_Erode_32_32_1080_1920_U0_p_dst_data_stream_1_V_din ),
    .p_dst_data_stream_1_V_full_n( hls_sobel_Erode_32_32_1080_1920_U0_p_dst_data_stream_1_V_full_n ),
    .p_dst_data_stream_1_V_write( hls_sobel_Erode_32_32_1080_1920_U0_p_dst_data_stream_1_V_write ),
    .p_dst_data_stream_2_V_din( hls_sobel_Erode_32_32_1080_1920_U0_p_dst_data_stream_2_V_din ),
    .p_dst_data_stream_2_V_full_n( hls_sobel_Erode_32_32_1080_1920_U0_p_dst_data_stream_2_V_full_n ),
    .p_dst_data_stream_2_V_write( hls_sobel_Erode_32_32_1080_1920_U0_p_dst_data_stream_2_V_write )
);

hls_sobel_Dilate_32_32_1080_1920_s hls_sobel_Dilate_32_32_1080_1920_U0(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst_n_inv ),
    .ap_start( hls_sobel_Dilate_32_32_1080_1920_U0_ap_start ),
    .ap_done( hls_sobel_Dilate_32_32_1080_1920_U0_ap_done ),
    .ap_continue( hls_sobel_Dilate_32_32_1080_1920_U0_ap_continue ),
    .ap_idle( hls_sobel_Dilate_32_32_1080_1920_U0_ap_idle ),
    .ap_ready( hls_sobel_Dilate_32_32_1080_1920_U0_ap_ready ),
    .rows( hls_sobel_Dilate_32_32_1080_1920_U0_rows ),
    .cols( hls_sobel_Dilate_32_32_1080_1920_U0_cols ),
    .p_src_data_stream_0_V_dout( hls_sobel_Dilate_32_32_1080_1920_U0_p_src_data_stream_0_V_dout ),
    .p_src_data_stream_0_V_empty_n( hls_sobel_Dilate_32_32_1080_1920_U0_p_src_data_stream_0_V_empty_n ),
    .p_src_data_stream_0_V_read( hls_sobel_Dilate_32_32_1080_1920_U0_p_src_data_stream_0_V_read ),
    .p_src_data_stream_1_V_dout( hls_sobel_Dilate_32_32_1080_1920_U0_p_src_data_stream_1_V_dout ),
    .p_src_data_stream_1_V_empty_n( hls_sobel_Dilate_32_32_1080_1920_U0_p_src_data_stream_1_V_empty_n ),
    .p_src_data_stream_1_V_read( hls_sobel_Dilate_32_32_1080_1920_U0_p_src_data_stream_1_V_read ),
    .p_src_data_stream_2_V_dout( hls_sobel_Dilate_32_32_1080_1920_U0_p_src_data_stream_2_V_dout ),
    .p_src_data_stream_2_V_empty_n( hls_sobel_Dilate_32_32_1080_1920_U0_p_src_data_stream_2_V_empty_n ),
    .p_src_data_stream_2_V_read( hls_sobel_Dilate_32_32_1080_1920_U0_p_src_data_stream_2_V_read ),
    .p_dst_data_stream_0_V_din( hls_sobel_Dilate_32_32_1080_1920_U0_p_dst_data_stream_0_V_din ),
    .p_dst_data_stream_0_V_full_n( hls_sobel_Dilate_32_32_1080_1920_U0_p_dst_data_stream_0_V_full_n ),
    .p_dst_data_stream_0_V_write( hls_sobel_Dilate_32_32_1080_1920_U0_p_dst_data_stream_0_V_write ),
    .p_dst_data_stream_1_V_din( hls_sobel_Dilate_32_32_1080_1920_U0_p_dst_data_stream_1_V_din ),
    .p_dst_data_stream_1_V_full_n( hls_sobel_Dilate_32_32_1080_1920_U0_p_dst_data_stream_1_V_full_n ),
    .p_dst_data_stream_1_V_write( hls_sobel_Dilate_32_32_1080_1920_U0_p_dst_data_stream_1_V_write ),
    .p_dst_data_stream_2_V_din( hls_sobel_Dilate_32_32_1080_1920_U0_p_dst_data_stream_2_V_din ),
    .p_dst_data_stream_2_V_full_n( hls_sobel_Dilate_32_32_1080_1920_U0_p_dst_data_stream_2_V_full_n ),
    .p_dst_data_stream_2_V_write( hls_sobel_Dilate_32_32_1080_1920_U0_p_dst_data_stream_2_V_write )
);

hls_sobel_Mat2AXIvideo hls_sobel_Mat2AXIvideo_U0(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst_n_inv ),
    .ap_start( hls_sobel_Mat2AXIvideo_U0_ap_start ),
    .ap_done( hls_sobel_Mat2AXIvideo_U0_ap_done ),
    .ap_continue( hls_sobel_Mat2AXIvideo_U0_ap_continue ),
    .ap_idle( hls_sobel_Mat2AXIvideo_U0_ap_idle ),
    .ap_ready( hls_sobel_Mat2AXIvideo_U0_ap_ready ),
    .rows( hls_sobel_Mat2AXIvideo_U0_rows ),
    .cols( hls_sobel_Mat2AXIvideo_U0_cols ),
    .img_data_stream_0_V_dout( hls_sobel_Mat2AXIvideo_U0_img_data_stream_0_V_dout ),
    .img_data_stream_0_V_empty_n( hls_sobel_Mat2AXIvideo_U0_img_data_stream_0_V_empty_n ),
    .img_data_stream_0_V_read( hls_sobel_Mat2AXIvideo_U0_img_data_stream_0_V_read ),
    .img_data_stream_1_V_dout( hls_sobel_Mat2AXIvideo_U0_img_data_stream_1_V_dout ),
    .img_data_stream_1_V_empty_n( hls_sobel_Mat2AXIvideo_U0_img_data_stream_1_V_empty_n ),
    .img_data_stream_1_V_read( hls_sobel_Mat2AXIvideo_U0_img_data_stream_1_V_read ),
    .img_data_stream_2_V_dout( hls_sobel_Mat2AXIvideo_U0_img_data_stream_2_V_dout ),
    .img_data_stream_2_V_empty_n( hls_sobel_Mat2AXIvideo_U0_img_data_stream_2_V_empty_n ),
    .img_data_stream_2_V_read( hls_sobel_Mat2AXIvideo_U0_img_data_stream_2_V_read ),
    .OUTPUT_STREAM_TDATA( hls_sobel_Mat2AXIvideo_U0_OUTPUT_STREAM_TDATA ),
    .OUTPUT_STREAM_TVALID( hls_sobel_Mat2AXIvideo_U0_OUTPUT_STREAM_TVALID ),
    .OUTPUT_STREAM_TREADY( hls_sobel_Mat2AXIvideo_U0_OUTPUT_STREAM_TREADY ),
    .OUTPUT_STREAM_TKEEP( hls_sobel_Mat2AXIvideo_U0_OUTPUT_STREAM_TKEEP ),
    .OUTPUT_STREAM_TSTRB( hls_sobel_Mat2AXIvideo_U0_OUTPUT_STREAM_TSTRB ),
    .OUTPUT_STREAM_TUSER( hls_sobel_Mat2AXIvideo_U0_OUTPUT_STREAM_TUSER ),
    .OUTPUT_STREAM_TLAST( hls_sobel_Mat2AXIvideo_U0_OUTPUT_STREAM_TLAST ),
    .OUTPUT_STREAM_TID( hls_sobel_Mat2AXIvideo_U0_OUTPUT_STREAM_TID ),
    .OUTPUT_STREAM_TDEST( hls_sobel_Mat2AXIvideo_U0_OUTPUT_STREAM_TDEST )
);

FIFO_hls_sobel_img_0_data_stream_0_V img_0_data_stream_0_V_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( img_0_data_stream_0_V_U_ap_dummy_ce ),
    .if_write_ce( img_0_data_stream_0_V_U_ap_dummy_ce ),
    .if_din( img_0_data_stream_0_V_din ),
    .if_full_n( img_0_data_stream_0_V_full_n ),
    .if_write( img_0_data_stream_0_V_write ),
    .if_dout( img_0_data_stream_0_V_dout ),
    .if_empty_n( img_0_data_stream_0_V_empty_n ),
    .if_read( img_0_data_stream_0_V_read )
);

FIFO_hls_sobel_img_0_data_stream_1_V img_0_data_stream_1_V_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( img_0_data_stream_1_V_U_ap_dummy_ce ),
    .if_write_ce( img_0_data_stream_1_V_U_ap_dummy_ce ),
    .if_din( img_0_data_stream_1_V_din ),
    .if_full_n( img_0_data_stream_1_V_full_n ),
    .if_write( img_0_data_stream_1_V_write ),
    .if_dout( img_0_data_stream_1_V_dout ),
    .if_empty_n( img_0_data_stream_1_V_empty_n ),
    .if_read( img_0_data_stream_1_V_read )
);

FIFO_hls_sobel_img_0_data_stream_2_V img_0_data_stream_2_V_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( img_0_data_stream_2_V_U_ap_dummy_ce ),
    .if_write_ce( img_0_data_stream_2_V_U_ap_dummy_ce ),
    .if_din( img_0_data_stream_2_V_din ),
    .if_full_n( img_0_data_stream_2_V_full_n ),
    .if_write( img_0_data_stream_2_V_write ),
    .if_dout( img_0_data_stream_2_V_dout ),
    .if_empty_n( img_0_data_stream_2_V_empty_n ),
    .if_read( img_0_data_stream_2_V_read )
);

FIFO_hls_sobel_img_1_data_stream_0_V img_1_data_stream_0_V_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( img_1_data_stream_0_V_U_ap_dummy_ce ),
    .if_write_ce( img_1_data_stream_0_V_U_ap_dummy_ce ),
    .if_din( img_1_data_stream_0_V_din ),
    .if_full_n( img_1_data_stream_0_V_full_n ),
    .if_write( img_1_data_stream_0_V_write ),
    .if_dout( img_1_data_stream_0_V_dout ),
    .if_empty_n( img_1_data_stream_0_V_empty_n ),
    .if_read( img_1_data_stream_0_V_read )
);

FIFO_hls_sobel_img_1_data_stream_1_V img_1_data_stream_1_V_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( img_1_data_stream_1_V_U_ap_dummy_ce ),
    .if_write_ce( img_1_data_stream_1_V_U_ap_dummy_ce ),
    .if_din( img_1_data_stream_1_V_din ),
    .if_full_n( img_1_data_stream_1_V_full_n ),
    .if_write( img_1_data_stream_1_V_write ),
    .if_dout( img_1_data_stream_1_V_dout ),
    .if_empty_n( img_1_data_stream_1_V_empty_n ),
    .if_read( img_1_data_stream_1_V_read )
);

FIFO_hls_sobel_img_1_data_stream_2_V img_1_data_stream_2_V_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( img_1_data_stream_2_V_U_ap_dummy_ce ),
    .if_write_ce( img_1_data_stream_2_V_U_ap_dummy_ce ),
    .if_din( img_1_data_stream_2_V_din ),
    .if_full_n( img_1_data_stream_2_V_full_n ),
    .if_write( img_1_data_stream_2_V_write ),
    .if_dout( img_1_data_stream_2_V_dout ),
    .if_empty_n( img_1_data_stream_2_V_empty_n ),
    .if_read( img_1_data_stream_2_V_read )
);

FIFO_hls_sobel_img_2_data_stream_0_V img_2_data_stream_0_V_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( img_2_data_stream_0_V_U_ap_dummy_ce ),
    .if_write_ce( img_2_data_stream_0_V_U_ap_dummy_ce ),
    .if_din( img_2_data_stream_0_V_din ),
    .if_full_n( img_2_data_stream_0_V_full_n ),
    .if_write( img_2_data_stream_0_V_write ),
    .if_dout( img_2_data_stream_0_V_dout ),
    .if_empty_n( img_2_data_stream_0_V_empty_n ),
    .if_read( img_2_data_stream_0_V_read )
);

FIFO_hls_sobel_img_2_data_stream_1_V img_2_data_stream_1_V_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( img_2_data_stream_1_V_U_ap_dummy_ce ),
    .if_write_ce( img_2_data_stream_1_V_U_ap_dummy_ce ),
    .if_din( img_2_data_stream_1_V_din ),
    .if_full_n( img_2_data_stream_1_V_full_n ),
    .if_write( img_2_data_stream_1_V_write ),
    .if_dout( img_2_data_stream_1_V_dout ),
    .if_empty_n( img_2_data_stream_1_V_empty_n ),
    .if_read( img_2_data_stream_1_V_read )
);

FIFO_hls_sobel_img_2_data_stream_2_V img_2_data_stream_2_V_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( img_2_data_stream_2_V_U_ap_dummy_ce ),
    .if_write_ce( img_2_data_stream_2_V_U_ap_dummy_ce ),
    .if_din( img_2_data_stream_2_V_din ),
    .if_full_n( img_2_data_stream_2_V_full_n ),
    .if_write( img_2_data_stream_2_V_write ),
    .if_dout( img_2_data_stream_2_V_dout ),
    .if_empty_n( img_2_data_stream_2_V_empty_n ),
    .if_read( img_2_data_stream_2_V_read )
);

FIFO_hls_sobel_img_3_data_stream_0_V img_3_data_stream_0_V_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( img_3_data_stream_0_V_U_ap_dummy_ce ),
    .if_write_ce( img_3_data_stream_0_V_U_ap_dummy_ce ),
    .if_din( img_3_data_stream_0_V_din ),
    .if_full_n( img_3_data_stream_0_V_full_n ),
    .if_write( img_3_data_stream_0_V_write ),
    .if_dout( img_3_data_stream_0_V_dout ),
    .if_empty_n( img_3_data_stream_0_V_empty_n ),
    .if_read( img_3_data_stream_0_V_read )
);

FIFO_hls_sobel_img_3_data_stream_1_V img_3_data_stream_1_V_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( img_3_data_stream_1_V_U_ap_dummy_ce ),
    .if_write_ce( img_3_data_stream_1_V_U_ap_dummy_ce ),
    .if_din( img_3_data_stream_1_V_din ),
    .if_full_n( img_3_data_stream_1_V_full_n ),
    .if_write( img_3_data_stream_1_V_write ),
    .if_dout( img_3_data_stream_1_V_dout ),
    .if_empty_n( img_3_data_stream_1_V_empty_n ),
    .if_read( img_3_data_stream_1_V_read )
);

FIFO_hls_sobel_img_3_data_stream_2_V img_3_data_stream_2_V_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( img_3_data_stream_2_V_U_ap_dummy_ce ),
    .if_write_ce( img_3_data_stream_2_V_U_ap_dummy_ce ),
    .if_din( img_3_data_stream_2_V_din ),
    .if_full_n( img_3_data_stream_2_V_full_n ),
    .if_write( img_3_data_stream_2_V_write ),
    .if_dout( img_3_data_stream_2_V_dout ),
    .if_empty_n( img_3_data_stream_2_V_empty_n ),
    .if_read( img_3_data_stream_2_V_read )
);

FIFO_hls_sobel_img_4_data_stream_0_V img_4_data_stream_0_V_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( img_4_data_stream_0_V_U_ap_dummy_ce ),
    .if_write_ce( img_4_data_stream_0_V_U_ap_dummy_ce ),
    .if_din( img_4_data_stream_0_V_din ),
    .if_full_n( img_4_data_stream_0_V_full_n ),
    .if_write( img_4_data_stream_0_V_write ),
    .if_dout( img_4_data_stream_0_V_dout ),
    .if_empty_n( img_4_data_stream_0_V_empty_n ),
    .if_read( img_4_data_stream_0_V_read )
);

FIFO_hls_sobel_img_4_data_stream_1_V img_4_data_stream_1_V_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( img_4_data_stream_1_V_U_ap_dummy_ce ),
    .if_write_ce( img_4_data_stream_1_V_U_ap_dummy_ce ),
    .if_din( img_4_data_stream_1_V_din ),
    .if_full_n( img_4_data_stream_1_V_full_n ),
    .if_write( img_4_data_stream_1_V_write ),
    .if_dout( img_4_data_stream_1_V_dout ),
    .if_empty_n( img_4_data_stream_1_V_empty_n ),
    .if_read( img_4_data_stream_1_V_read )
);

FIFO_hls_sobel_img_4_data_stream_2_V img_4_data_stream_2_V_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( img_4_data_stream_2_V_U_ap_dummy_ce ),
    .if_write_ce( img_4_data_stream_2_V_U_ap_dummy_ce ),
    .if_din( img_4_data_stream_2_V_din ),
    .if_full_n( img_4_data_stream_2_V_full_n ),
    .if_write( img_4_data_stream_2_V_write ),
    .if_dout( img_4_data_stream_2_V_dout ),
    .if_empty_n( img_4_data_stream_2_V_empty_n ),
    .if_read( img_4_data_stream_2_V_read )
);

FIFO_hls_sobel_img_5_data_stream_0_V img_5_data_stream_0_V_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( img_5_data_stream_0_V_U_ap_dummy_ce ),
    .if_write_ce( img_5_data_stream_0_V_U_ap_dummy_ce ),
    .if_din( img_5_data_stream_0_V_din ),
    .if_full_n( img_5_data_stream_0_V_full_n ),
    .if_write( img_5_data_stream_0_V_write ),
    .if_dout( img_5_data_stream_0_V_dout ),
    .if_empty_n( img_5_data_stream_0_V_empty_n ),
    .if_read( img_5_data_stream_0_V_read )
);

FIFO_hls_sobel_img_5_data_stream_1_V img_5_data_stream_1_V_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( img_5_data_stream_1_V_U_ap_dummy_ce ),
    .if_write_ce( img_5_data_stream_1_V_U_ap_dummy_ce ),
    .if_din( img_5_data_stream_1_V_din ),
    .if_full_n( img_5_data_stream_1_V_full_n ),
    .if_write( img_5_data_stream_1_V_write ),
    .if_dout( img_5_data_stream_1_V_dout ),
    .if_empty_n( img_5_data_stream_1_V_empty_n ),
    .if_read( img_5_data_stream_1_V_read )
);

FIFO_hls_sobel_img_5_data_stream_2_V img_5_data_stream_2_V_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( img_5_data_stream_2_V_U_ap_dummy_ce ),
    .if_write_ce( img_5_data_stream_2_V_U_ap_dummy_ce ),
    .if_din( img_5_data_stream_2_V_din ),
    .if_full_n( img_5_data_stream_2_V_full_n ),
    .if_write( img_5_data_stream_2_V_write ),
    .if_dout( img_5_data_stream_2_V_dout ),
    .if_empty_n( img_5_data_stream_2_V_empty_n ),
    .if_read( img_5_data_stream_2_V_read )
);



always @ (posedge ap_clk) begin : ap_ret_ap_reg_procdone_hls_sobel_AXIvideo2Mat_U0
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_procdone_hls_sobel_AXIvideo2Mat_U0 <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_hs_done)) begin
            ap_reg_procdone_hls_sobel_AXIvideo2Mat_U0 <= ap_const_logic_0;
        end else if ((hls_sobel_AXIvideo2Mat_U0_ap_done == ap_const_logic_1)) begin
            ap_reg_procdone_hls_sobel_AXIvideo2Mat_U0 <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_procdone_hls_sobel_Dilate_32_32_1080_1920_U0
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_procdone_hls_sobel_Dilate_32_32_1080_1920_U0 <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_hs_done)) begin
            ap_reg_procdone_hls_sobel_Dilate_32_32_1080_1920_U0 <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == hls_sobel_Dilate_32_32_1080_1920_U0_ap_done)) begin
            ap_reg_procdone_hls_sobel_Dilate_32_32_1080_1920_U0 <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_procdone_hls_sobel_Erode_32_32_1080_1920_U0
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_procdone_hls_sobel_Erode_32_32_1080_1920_U0 <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_hs_done)) begin
            ap_reg_procdone_hls_sobel_Erode_32_32_1080_1920_U0 <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == hls_sobel_Erode_32_32_1080_1920_U0_ap_done)) begin
            ap_reg_procdone_hls_sobel_Erode_32_32_1080_1920_U0 <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_procdone_hls_sobel_Mat2AXIvideo_U0
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_procdone_hls_sobel_Mat2AXIvideo_U0 <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_hs_done)) begin
            ap_reg_procdone_hls_sobel_Mat2AXIvideo_U0 <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == hls_sobel_Mat2AXIvideo_U0_ap_done)) begin
            ap_reg_procdone_hls_sobel_Mat2AXIvideo_U0 <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_procdone_hls_sobel_Scale_1080_1920_32_32_int_U0
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_procdone_hls_sobel_Scale_1080_1920_32_32_int_U0 <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_hs_done)) begin
            ap_reg_procdone_hls_sobel_Scale_1080_1920_32_32_int_U0 <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == hls_sobel_Scale_1080_1920_32_32_int_U0_ap_done)) begin
            ap_reg_procdone_hls_sobel_Scale_1080_1920_32_32_int_U0 <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_procdone_hls_sobel_Sobel_U0
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_procdone_hls_sobel_Sobel_U0 <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_hs_done)) begin
            ap_reg_procdone_hls_sobel_Sobel_U0 <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == hls_sobel_Sobel_U0_ap_done)) begin
            ap_reg_procdone_hls_sobel_Sobel_U0 <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_procdone_hls_sobel_SubS_U0
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_procdone_hls_sobel_SubS_U0 <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_hs_done)) begin
            ap_reg_procdone_hls_sobel_SubS_U0 <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == hls_sobel_SubS_U0_ap_done)) begin
            ap_reg_procdone_hls_sobel_SubS_U0 <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin
    ap_CS <= ap_const_logic_0;
end

always @ (hls_sobel_AXIvideo2Mat_U0_ap_idle or hls_sobel_Sobel_U0_ap_idle or hls_sobel_SubS_U0_ap_idle or hls_sobel_Scale_1080_1920_32_32_int_U0_ap_idle or hls_sobel_Erode_32_32_1080_1920_U0_ap_idle or hls_sobel_Dilate_32_32_1080_1920_U0_ap_idle or hls_sobel_Mat2AXIvideo_U0_ap_idle) begin
    if (((hls_sobel_AXIvideo2Mat_U0_ap_idle == ap_const_logic_1) & (ap_const_logic_1 == hls_sobel_Sobel_U0_ap_idle) & (ap_const_logic_1 == hls_sobel_SubS_U0_ap_idle) & (ap_const_logic_1 == hls_sobel_Scale_1080_1920_32_32_int_U0_ap_idle) & (ap_const_logic_1 == hls_sobel_Erode_32_32_1080_1920_U0_ap_idle) & (ap_const_logic_1 == hls_sobel_Dilate_32_32_1080_1920_U0_ap_idle) & (ap_const_logic_1 == hls_sobel_Mat2AXIvideo_U0_ap_idle))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

always @ (hls_sobel_Mat2AXIvideo_U0_ap_done) begin
    if ((ap_const_logic_1 == hls_sobel_Mat2AXIvideo_U0_ap_done)) begin
        ap_sig_hs_done = ap_const_logic_1;
    end else begin
        ap_sig_hs_done = ap_const_logic_0;
    end
end

assign INPUT_STREAM_TREADY = hls_sobel_AXIvideo2Mat_U0_INPUT_STREAM_TREADY;

assign OUTPUT_STREAM_TDATA = hls_sobel_Mat2AXIvideo_U0_OUTPUT_STREAM_TDATA;

assign OUTPUT_STREAM_TDEST = hls_sobel_Mat2AXIvideo_U0_OUTPUT_STREAM_TDEST;

assign OUTPUT_STREAM_TID = hls_sobel_Mat2AXIvideo_U0_OUTPUT_STREAM_TID;

assign OUTPUT_STREAM_TKEEP = hls_sobel_Mat2AXIvideo_U0_OUTPUT_STREAM_TKEEP;

assign OUTPUT_STREAM_TLAST = hls_sobel_Mat2AXIvideo_U0_OUTPUT_STREAM_TLAST;

assign OUTPUT_STREAM_TSTRB = hls_sobel_Mat2AXIvideo_U0_OUTPUT_STREAM_TSTRB;

assign OUTPUT_STREAM_TUSER = hls_sobel_Mat2AXIvideo_U0_OUTPUT_STREAM_TUSER;

assign OUTPUT_STREAM_TVALID = hls_sobel_Mat2AXIvideo_U0_OUTPUT_STREAM_TVALID;

assign ap_done = ap_sig_hs_done;

assign ap_ready = ap_sig_top_allready;


always @ (ap_rst_n) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sig_hs_continue = ap_const_logic_1;

assign ap_sig_top_allready = hls_sobel_AXIvideo2Mat_U0_ap_ready;

assign hls_sobel_AXIvideo2Mat_U0_INPUT_STREAM_TDATA = INPUT_STREAM_TDATA;

assign hls_sobel_AXIvideo2Mat_U0_INPUT_STREAM_TDEST = INPUT_STREAM_TDEST;

assign hls_sobel_AXIvideo2Mat_U0_INPUT_STREAM_TID = INPUT_STREAM_TID;

assign hls_sobel_AXIvideo2Mat_U0_INPUT_STREAM_TKEEP = INPUT_STREAM_TKEEP;

assign hls_sobel_AXIvideo2Mat_U0_INPUT_STREAM_TLAST = INPUT_STREAM_TLAST;

assign hls_sobel_AXIvideo2Mat_U0_INPUT_STREAM_TSTRB = INPUT_STREAM_TSTRB;

assign hls_sobel_AXIvideo2Mat_U0_INPUT_STREAM_TUSER = INPUT_STREAM_TUSER;

assign hls_sobel_AXIvideo2Mat_U0_INPUT_STREAM_TVALID = INPUT_STREAM_TVALID;

assign hls_sobel_AXIvideo2Mat_U0_ap_continue = ap_const_logic_1;

assign hls_sobel_AXIvideo2Mat_U0_ap_start = ap_start;

assign hls_sobel_AXIvideo2Mat_U0_cols = {{cols[(ap_const_lv32_B - 32'd1) : ap_const_lv32_0]}};

assign hls_sobel_AXIvideo2Mat_U0_img_data_stream_0_V_full_n = img_0_data_stream_0_V_full_n;

assign hls_sobel_AXIvideo2Mat_U0_img_data_stream_1_V_full_n = img_0_data_stream_1_V_full_n;

assign hls_sobel_AXIvideo2Mat_U0_img_data_stream_2_V_full_n = img_0_data_stream_2_V_full_n;

assign hls_sobel_AXIvideo2Mat_U0_rows = {{rows[(ap_const_lv32_B - 32'd1) : ap_const_lv32_0]}};

assign hls_sobel_Dilate_32_32_1080_1920_U0_ap_continue = ap_const_logic_1;

assign hls_sobel_Dilate_32_32_1080_1920_U0_ap_start = ap_start;

assign hls_sobel_Dilate_32_32_1080_1920_U0_cols = {{cols[(ap_const_lv32_B - 32'd1) : ap_const_lv32_0]}};

assign hls_sobel_Dilate_32_32_1080_1920_U0_p_dst_data_stream_0_V_full_n = img_5_data_stream_0_V_full_n;

assign hls_sobel_Dilate_32_32_1080_1920_U0_p_dst_data_stream_1_V_full_n = img_5_data_stream_1_V_full_n;

assign hls_sobel_Dilate_32_32_1080_1920_U0_p_dst_data_stream_2_V_full_n = img_5_data_stream_2_V_full_n;

assign hls_sobel_Dilate_32_32_1080_1920_U0_p_src_data_stream_0_V_dout = img_4_data_stream_0_V_dout;

assign hls_sobel_Dilate_32_32_1080_1920_U0_p_src_data_stream_0_V_empty_n = img_4_data_stream_0_V_empty_n;

assign hls_sobel_Dilate_32_32_1080_1920_U0_p_src_data_stream_1_V_dout = img_4_data_stream_1_V_dout;

assign hls_sobel_Dilate_32_32_1080_1920_U0_p_src_data_stream_1_V_empty_n = img_4_data_stream_1_V_empty_n;

assign hls_sobel_Dilate_32_32_1080_1920_U0_p_src_data_stream_2_V_dout = img_4_data_stream_2_V_dout;

assign hls_sobel_Dilate_32_32_1080_1920_U0_p_src_data_stream_2_V_empty_n = img_4_data_stream_2_V_empty_n;

assign hls_sobel_Dilate_32_32_1080_1920_U0_rows = {{rows[(ap_const_lv32_B - 32'd1) : ap_const_lv32_0]}};

assign hls_sobel_Erode_32_32_1080_1920_U0_ap_continue = ap_const_logic_1;

assign hls_sobel_Erode_32_32_1080_1920_U0_ap_start = ap_start;

assign hls_sobel_Erode_32_32_1080_1920_U0_cols = {{cols[(ap_const_lv32_B - 32'd1) : ap_const_lv32_0]}};

assign hls_sobel_Erode_32_32_1080_1920_U0_p_dst_data_stream_0_V_full_n = img_4_data_stream_0_V_full_n;

assign hls_sobel_Erode_32_32_1080_1920_U0_p_dst_data_stream_1_V_full_n = img_4_data_stream_1_V_full_n;

assign hls_sobel_Erode_32_32_1080_1920_U0_p_dst_data_stream_2_V_full_n = img_4_data_stream_2_V_full_n;

assign hls_sobel_Erode_32_32_1080_1920_U0_p_src_data_stream_0_V_dout = img_3_data_stream_0_V_dout;

assign hls_sobel_Erode_32_32_1080_1920_U0_p_src_data_stream_0_V_empty_n = img_3_data_stream_0_V_empty_n;

assign hls_sobel_Erode_32_32_1080_1920_U0_p_src_data_stream_1_V_dout = img_3_data_stream_1_V_dout;

assign hls_sobel_Erode_32_32_1080_1920_U0_p_src_data_stream_1_V_empty_n = img_3_data_stream_1_V_empty_n;

assign hls_sobel_Erode_32_32_1080_1920_U0_p_src_data_stream_2_V_dout = img_3_data_stream_2_V_dout;

assign hls_sobel_Erode_32_32_1080_1920_U0_p_src_data_stream_2_V_empty_n = img_3_data_stream_2_V_empty_n;

assign hls_sobel_Erode_32_32_1080_1920_U0_rows = {{rows[(ap_const_lv32_B - 32'd1) : ap_const_lv32_0]}};

assign hls_sobel_Mat2AXIvideo_U0_OUTPUT_STREAM_TREADY = OUTPUT_STREAM_TREADY;

assign hls_sobel_Mat2AXIvideo_U0_ap_continue = ap_sig_hs_continue;

assign hls_sobel_Mat2AXIvideo_U0_ap_start = ap_start;

assign hls_sobel_Mat2AXIvideo_U0_cols = {{cols[(ap_const_lv32_B - 32'd1) : ap_const_lv32_0]}};

assign hls_sobel_Mat2AXIvideo_U0_img_data_stream_0_V_dout = img_5_data_stream_0_V_dout;

assign hls_sobel_Mat2AXIvideo_U0_img_data_stream_0_V_empty_n = img_5_data_stream_0_V_empty_n;

assign hls_sobel_Mat2AXIvideo_U0_img_data_stream_1_V_dout = img_5_data_stream_1_V_dout;

assign hls_sobel_Mat2AXIvideo_U0_img_data_stream_1_V_empty_n = img_5_data_stream_1_V_empty_n;

assign hls_sobel_Mat2AXIvideo_U0_img_data_stream_2_V_dout = img_5_data_stream_2_V_dout;

assign hls_sobel_Mat2AXIvideo_U0_img_data_stream_2_V_empty_n = img_5_data_stream_2_V_empty_n;

assign hls_sobel_Mat2AXIvideo_U0_rows = {{rows[(ap_const_lv32_B - 32'd1) : ap_const_lv32_0]}};

assign hls_sobel_Scale_1080_1920_32_32_int_U0_ap_continue = ap_const_logic_1;

assign hls_sobel_Scale_1080_1920_32_32_int_U0_ap_start = ap_start;

assign hls_sobel_Scale_1080_1920_32_32_int_U0_cols = {{cols[(ap_const_lv32_B - 32'd1) : ap_const_lv32_0]}};

assign hls_sobel_Scale_1080_1920_32_32_int_U0_dst_data_stream_0_V_full_n = img_3_data_stream_0_V_full_n;

assign hls_sobel_Scale_1080_1920_32_32_int_U0_dst_data_stream_1_V_full_n = img_3_data_stream_1_V_full_n;

assign hls_sobel_Scale_1080_1920_32_32_int_U0_dst_data_stream_2_V_full_n = img_3_data_stream_2_V_full_n;

assign hls_sobel_Scale_1080_1920_32_32_int_U0_rows = {{rows[(ap_const_lv32_B - 32'd1) : ap_const_lv32_0]}};

assign hls_sobel_Scale_1080_1920_32_32_int_U0_src_data_stream_0_V_dout = img_2_data_stream_0_V_dout;

assign hls_sobel_Scale_1080_1920_32_32_int_U0_src_data_stream_0_V_empty_n = img_2_data_stream_0_V_empty_n;

assign hls_sobel_Scale_1080_1920_32_32_int_U0_src_data_stream_1_V_dout = img_2_data_stream_1_V_dout;

assign hls_sobel_Scale_1080_1920_32_32_int_U0_src_data_stream_1_V_empty_n = img_2_data_stream_1_V_empty_n;

assign hls_sobel_Scale_1080_1920_32_32_int_U0_src_data_stream_2_V_dout = img_2_data_stream_2_V_dout;

assign hls_sobel_Scale_1080_1920_32_32_int_U0_src_data_stream_2_V_empty_n = img_2_data_stream_2_V_empty_n;

assign hls_sobel_Sobel_U0_ap_continue = ap_const_logic_1;

assign hls_sobel_Sobel_U0_ap_start = ap_start;

assign hls_sobel_Sobel_U0_cols = {{cols[(ap_const_lv32_B - 32'd1) : ap_const_lv32_0]}};

assign hls_sobel_Sobel_U0_p_dst_data_stream_0_V_full_n = img_1_data_stream_0_V_full_n;

assign hls_sobel_Sobel_U0_p_dst_data_stream_1_V_full_n = img_1_data_stream_1_V_full_n;

assign hls_sobel_Sobel_U0_p_dst_data_stream_2_V_full_n = img_1_data_stream_2_V_full_n;

assign hls_sobel_Sobel_U0_p_src_data_stream_0_V_dout = img_0_data_stream_0_V_dout;

assign hls_sobel_Sobel_U0_p_src_data_stream_0_V_empty_n = img_0_data_stream_0_V_empty_n;

assign hls_sobel_Sobel_U0_p_src_data_stream_1_V_dout = img_0_data_stream_1_V_dout;

assign hls_sobel_Sobel_U0_p_src_data_stream_1_V_empty_n = img_0_data_stream_1_V_empty_n;

assign hls_sobel_Sobel_U0_p_src_data_stream_2_V_dout = img_0_data_stream_2_V_dout;

assign hls_sobel_Sobel_U0_p_src_data_stream_2_V_empty_n = img_0_data_stream_2_V_empty_n;

assign hls_sobel_Sobel_U0_rows = {{rows[(ap_const_lv32_B - 32'd1) : ap_const_lv32_0]}};

assign hls_sobel_SubS_U0_ap_continue = ap_const_logic_1;

assign hls_sobel_SubS_U0_ap_start = ap_start;

assign hls_sobel_SubS_U0_cols = {{cols[(ap_const_lv32_B - 32'd1) : ap_const_lv32_0]}};

assign hls_sobel_SubS_U0_dst_data_stream_0_V_full_n = img_2_data_stream_0_V_full_n;

assign hls_sobel_SubS_U0_dst_data_stream_1_V_full_n = img_2_data_stream_1_V_full_n;

assign hls_sobel_SubS_U0_dst_data_stream_2_V_full_n = img_2_data_stream_2_V_full_n;

assign hls_sobel_SubS_U0_rows = {{rows[(ap_const_lv32_B - 32'd1) : ap_const_lv32_0]}};

assign hls_sobel_SubS_U0_src_data_stream_0_V_dout = img_1_data_stream_0_V_dout;

assign hls_sobel_SubS_U0_src_data_stream_0_V_empty_n = img_1_data_stream_0_V_empty_n;

assign hls_sobel_SubS_U0_src_data_stream_1_V_dout = img_1_data_stream_1_V_dout;

assign hls_sobel_SubS_U0_src_data_stream_1_V_empty_n = img_1_data_stream_1_V_empty_n;

assign hls_sobel_SubS_U0_src_data_stream_2_V_dout = img_1_data_stream_2_V_dout;

assign hls_sobel_SubS_U0_src_data_stream_2_V_empty_n = img_1_data_stream_2_V_empty_n;

assign img_0_data_stream_0_V_U_ap_dummy_ce = ap_const_logic_1;

assign img_0_data_stream_0_V_din = hls_sobel_AXIvideo2Mat_U0_img_data_stream_0_V_din;

assign img_0_data_stream_0_V_read = hls_sobel_Sobel_U0_p_src_data_stream_0_V_read;

assign img_0_data_stream_0_V_write = hls_sobel_AXIvideo2Mat_U0_img_data_stream_0_V_write;

assign img_0_data_stream_1_V_U_ap_dummy_ce = ap_const_logic_1;

assign img_0_data_stream_1_V_din = hls_sobel_AXIvideo2Mat_U0_img_data_stream_1_V_din;

assign img_0_data_stream_1_V_read = hls_sobel_Sobel_U0_p_src_data_stream_1_V_read;

assign img_0_data_stream_1_V_write = hls_sobel_AXIvideo2Mat_U0_img_data_stream_1_V_write;

assign img_0_data_stream_2_V_U_ap_dummy_ce = ap_const_logic_1;

assign img_0_data_stream_2_V_din = hls_sobel_AXIvideo2Mat_U0_img_data_stream_2_V_din;

assign img_0_data_stream_2_V_read = hls_sobel_Sobel_U0_p_src_data_stream_2_V_read;

assign img_0_data_stream_2_V_write = hls_sobel_AXIvideo2Mat_U0_img_data_stream_2_V_write;

assign img_1_data_stream_0_V_U_ap_dummy_ce = ap_const_logic_1;

assign img_1_data_stream_0_V_din = hls_sobel_Sobel_U0_p_dst_data_stream_0_V_din;

assign img_1_data_stream_0_V_read = hls_sobel_SubS_U0_src_data_stream_0_V_read;

assign img_1_data_stream_0_V_write = hls_sobel_Sobel_U0_p_dst_data_stream_0_V_write;

assign img_1_data_stream_1_V_U_ap_dummy_ce = ap_const_logic_1;

assign img_1_data_stream_1_V_din = hls_sobel_Sobel_U0_p_dst_data_stream_1_V_din;

assign img_1_data_stream_1_V_read = hls_sobel_SubS_U0_src_data_stream_1_V_read;

assign img_1_data_stream_1_V_write = hls_sobel_Sobel_U0_p_dst_data_stream_1_V_write;

assign img_1_data_stream_2_V_U_ap_dummy_ce = ap_const_logic_1;

assign img_1_data_stream_2_V_din = hls_sobel_Sobel_U0_p_dst_data_stream_2_V_din;

assign img_1_data_stream_2_V_read = hls_sobel_SubS_U0_src_data_stream_2_V_read;

assign img_1_data_stream_2_V_write = hls_sobel_Sobel_U0_p_dst_data_stream_2_V_write;

assign img_2_data_stream_0_V_U_ap_dummy_ce = ap_const_logic_1;

assign img_2_data_stream_0_V_din = hls_sobel_SubS_U0_dst_data_stream_0_V_din;

assign img_2_data_stream_0_V_read = hls_sobel_Scale_1080_1920_32_32_int_U0_src_data_stream_0_V_read;

assign img_2_data_stream_0_V_write = hls_sobel_SubS_U0_dst_data_stream_0_V_write;

assign img_2_data_stream_1_V_U_ap_dummy_ce = ap_const_logic_1;

assign img_2_data_stream_1_V_din = hls_sobel_SubS_U0_dst_data_stream_1_V_din;

assign img_2_data_stream_1_V_read = hls_sobel_Scale_1080_1920_32_32_int_U0_src_data_stream_1_V_read;

assign img_2_data_stream_1_V_write = hls_sobel_SubS_U0_dst_data_stream_1_V_write;

assign img_2_data_stream_2_V_U_ap_dummy_ce = ap_const_logic_1;

assign img_2_data_stream_2_V_din = hls_sobel_SubS_U0_dst_data_stream_2_V_din;

assign img_2_data_stream_2_V_read = hls_sobel_Scale_1080_1920_32_32_int_U0_src_data_stream_2_V_read;

assign img_2_data_stream_2_V_write = hls_sobel_SubS_U0_dst_data_stream_2_V_write;

assign img_3_data_stream_0_V_U_ap_dummy_ce = ap_const_logic_1;

assign img_3_data_stream_0_V_din = hls_sobel_Scale_1080_1920_32_32_int_U0_dst_data_stream_0_V_din;

assign img_3_data_stream_0_V_read = hls_sobel_Erode_32_32_1080_1920_U0_p_src_data_stream_0_V_read;

assign img_3_data_stream_0_V_write = hls_sobel_Scale_1080_1920_32_32_int_U0_dst_data_stream_0_V_write;

assign img_3_data_stream_1_V_U_ap_dummy_ce = ap_const_logic_1;

assign img_3_data_stream_1_V_din = hls_sobel_Scale_1080_1920_32_32_int_U0_dst_data_stream_1_V_din;

assign img_3_data_stream_1_V_read = hls_sobel_Erode_32_32_1080_1920_U0_p_src_data_stream_1_V_read;

assign img_3_data_stream_1_V_write = hls_sobel_Scale_1080_1920_32_32_int_U0_dst_data_stream_1_V_write;

assign img_3_data_stream_2_V_U_ap_dummy_ce = ap_const_logic_1;

assign img_3_data_stream_2_V_din = hls_sobel_Scale_1080_1920_32_32_int_U0_dst_data_stream_2_V_din;

assign img_3_data_stream_2_V_read = hls_sobel_Erode_32_32_1080_1920_U0_p_src_data_stream_2_V_read;

assign img_3_data_stream_2_V_write = hls_sobel_Scale_1080_1920_32_32_int_U0_dst_data_stream_2_V_write;

assign img_4_data_stream_0_V_U_ap_dummy_ce = ap_const_logic_1;

assign img_4_data_stream_0_V_din = hls_sobel_Erode_32_32_1080_1920_U0_p_dst_data_stream_0_V_din;

assign img_4_data_stream_0_V_read = hls_sobel_Dilate_32_32_1080_1920_U0_p_src_data_stream_0_V_read;

assign img_4_data_stream_0_V_write = hls_sobel_Erode_32_32_1080_1920_U0_p_dst_data_stream_0_V_write;

assign img_4_data_stream_1_V_U_ap_dummy_ce = ap_const_logic_1;

assign img_4_data_stream_1_V_din = hls_sobel_Erode_32_32_1080_1920_U0_p_dst_data_stream_1_V_din;

assign img_4_data_stream_1_V_read = hls_sobel_Dilate_32_32_1080_1920_U0_p_src_data_stream_1_V_read;

assign img_4_data_stream_1_V_write = hls_sobel_Erode_32_32_1080_1920_U0_p_dst_data_stream_1_V_write;

assign img_4_data_stream_2_V_U_ap_dummy_ce = ap_const_logic_1;

assign img_4_data_stream_2_V_din = hls_sobel_Erode_32_32_1080_1920_U0_p_dst_data_stream_2_V_din;

assign img_4_data_stream_2_V_read = hls_sobel_Dilate_32_32_1080_1920_U0_p_src_data_stream_2_V_read;

assign img_4_data_stream_2_V_write = hls_sobel_Erode_32_32_1080_1920_U0_p_dst_data_stream_2_V_write;

assign img_5_data_stream_0_V_U_ap_dummy_ce = ap_const_logic_1;

assign img_5_data_stream_0_V_din = hls_sobel_Dilate_32_32_1080_1920_U0_p_dst_data_stream_0_V_din;

assign img_5_data_stream_0_V_read = hls_sobel_Mat2AXIvideo_U0_img_data_stream_0_V_read;

assign img_5_data_stream_0_V_write = hls_sobel_Dilate_32_32_1080_1920_U0_p_dst_data_stream_0_V_write;

assign img_5_data_stream_1_V_U_ap_dummy_ce = ap_const_logic_1;

assign img_5_data_stream_1_V_din = hls_sobel_Dilate_32_32_1080_1920_U0_p_dst_data_stream_1_V_din;

assign img_5_data_stream_1_V_read = hls_sobel_Mat2AXIvideo_U0_img_data_stream_1_V_read;

assign img_5_data_stream_1_V_write = hls_sobel_Dilate_32_32_1080_1920_U0_p_dst_data_stream_1_V_write;

assign img_5_data_stream_2_V_U_ap_dummy_ce = ap_const_logic_1;

assign img_5_data_stream_2_V_din = hls_sobel_Dilate_32_32_1080_1920_U0_p_dst_data_stream_2_V_din;

assign img_5_data_stream_2_V_read = hls_sobel_Mat2AXIvideo_U0_img_data_stream_2_V_read;

assign img_5_data_stream_2_V_write = hls_sobel_Dilate_32_32_1080_1920_U0_p_dst_data_stream_2_V_write;


endmodule //hls_sobel

