// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module hls_sobel_Erode_32_32_1080_1920_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        rows,
        cols,
        p_src_data_stream_0_V_dout,
        p_src_data_stream_0_V_empty_n,
        p_src_data_stream_0_V_read,
        p_src_data_stream_1_V_dout,
        p_src_data_stream_1_V_empty_n,
        p_src_data_stream_1_V_read,
        p_src_data_stream_2_V_dout,
        p_src_data_stream_2_V_empty_n,
        p_src_data_stream_2_V_read,
        p_dst_data_stream_0_V_din,
        p_dst_data_stream_0_V_full_n,
        p_dst_data_stream_0_V_write,
        p_dst_data_stream_1_V_din,
        p_dst_data_stream_1_V_full_n,
        p_dst_data_stream_1_V_write,
        p_dst_data_stream_2_V_din,
        p_dst_data_stream_2_V_full_n,
        p_dst_data_stream_2_V_write
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 5'b1;
parameter    ap_ST_st2_fsm_1 = 5'b10;
parameter    ap_ST_st3_fsm_2 = 5'b100;
parameter    ap_ST_pp0_stg0_fsm_3 = 5'b1000;
parameter    ap_ST_st11_fsm_4 = 5'b10000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv2_0 = 2'b00;
parameter    ap_const_lv11_0 = 11'b00000000000;
parameter    ap_const_lv32_4 = 32'b100;
parameter    ap_const_lv2_1 = 2'b1;
parameter    ap_const_lv2_2 = 2'b10;
parameter    ap_const_lv11_2 = 11'b10;
parameter    ap_const_lv11_7FF = 11'b11111111111;
parameter    ap_const_lv2_3 = 2'b11;
parameter    ap_const_lv11_1 = 11'b1;
parameter    ap_const_lv32_A = 32'b1010;
parameter    ap_const_lv10_0 = 10'b0000000000;
parameter    ap_const_lv12_FFF = 12'b111111111111;
parameter    ap_const_lv12_FFE = 12'b111111111110;
parameter    ap_const_lv12_FFD = 12'b111111111101;
parameter    ap_const_lv32_B = 32'b1011;
parameter    ap_const_lv8_0 = 8'b00000000;
parameter    ap_true = 1'b1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [10:0] rows;
input  [10:0] cols;
input  [7:0] p_src_data_stream_0_V_dout;
input   p_src_data_stream_0_V_empty_n;
output   p_src_data_stream_0_V_read;
input  [7:0] p_src_data_stream_1_V_dout;
input   p_src_data_stream_1_V_empty_n;
output   p_src_data_stream_1_V_read;
input  [7:0] p_src_data_stream_2_V_dout;
input   p_src_data_stream_2_V_empty_n;
output   p_src_data_stream_2_V_read;
output  [7:0] p_dst_data_stream_0_V_din;
input   p_dst_data_stream_0_V_full_n;
output   p_dst_data_stream_0_V_write;
output  [7:0] p_dst_data_stream_1_V_din;
input   p_dst_data_stream_1_V_full_n;
output   p_dst_data_stream_1_V_write;
output  [7:0] p_dst_data_stream_2_V_din;
input   p_dst_data_stream_2_V_full_n;
output   p_dst_data_stream_2_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg p_src_data_stream_0_V_read;
reg p_src_data_stream_1_V_read;
reg p_src_data_stream_2_V_read;
reg p_dst_data_stream_0_V_write;
reg p_dst_data_stream_1_V_write;
reg p_dst_data_stream_2_V_write;
reg    ap_done_reg = 1'b0;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm = 5'b1;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_bdd_24;
reg   [10:0] p_027_0_i_i_i_reg_468;
reg    ap_sig_bdd_64;
wire   [11:0] rows_assign_cast_i_cast_fu_479_p1;
wire   [11:0] cols_assign_cast_i_cast_fu_483_p1;
wire   [1:0] tmp_24_i_fu_487_p2;
reg    ap_sig_cseq_ST_st2_fsm_1;
reg    ap_sig_bdd_80;
wire   [10:0] heightloop_fu_499_p2;
wire   [0:0] tmp_25_i_fu_493_p2;
wire   [10:0] widthloop_fu_504_p2;
wire   [10:0] tmp_32_i_fu_509_p2;
wire   [1:0] tmp_fu_514_p1;
wire   [1:0] p_assign_cast_i_fu_521_p2;
wire   [0:0] exitcond1_fu_531_p2;
reg    ap_sig_cseq_ST_st3_fsm_2;
reg    ap_sig_bdd_104;
wire   [10:0] i_V_fu_536_p2;
reg   [10:0] i_V_reg_1887;
wire   [0:0] tmp_35_i_fu_542_p2;
reg   [0:0] tmp_35_i_reg_1892;
wire   [0:0] tmp_203_not_0_i_fu_547_p2;
reg   [0:0] tmp_203_not_0_i_reg_1896;
wire   [0:0] icmp_fu_563_p2;
reg   [0:0] icmp_reg_1901;
wire   [0:0] tmp_239_0_i_fu_569_p2;
reg   [0:0] tmp_239_0_i_reg_1906;
wire   [0:0] tmp_239_0_2_i_fu_575_p2;
reg   [0:0] tmp_239_0_2_i_reg_1910;
wire   [0:0] tmp_261_0_i_fu_581_p2;
reg   [0:0] tmp_261_0_i_reg_1914;
wire   [1:0] row_assign_14_0_i_fu_608_p2;
reg   [1:0] row_assign_14_0_i_reg_1927;
wire   [1:0] row_assign_14_0_1_t_i_fu_635_p2;
reg   [1:0] row_assign_14_0_1_t_i_reg_1934;
wire   [1:0] row_assign_14_0_2_t_i_fu_662_p2;
reg   [1:0] row_assign_14_0_2_t_i_reg_1941;
wire   [0:0] exitcond_fu_671_p2;
reg   [0:0] exitcond_reg_1948;
reg    ap_sig_cseq_ST_pp0_stg0_fsm_3;
reg    ap_sig_bdd_135;
reg    ap_reg_ppiten_pp0_it0 = 1'b0;
reg    ap_reg_ppiten_pp0_it1 = 1'b0;
reg   [0:0] or_cond_i424_i_i_i_reg_1957;
reg   [0:0] ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1;
reg    ap_sig_bdd_166;
reg    ap_reg_ppiten_pp0_it2 = 1'b0;
reg    ap_reg_ppiten_pp0_it3 = 1'b0;
reg    ap_reg_ppiten_pp0_it4 = 1'b0;
reg    ap_reg_ppiten_pp0_it5 = 1'b0;
reg   [0:0] or_cond_i_i_i_reg_1992;
reg   [0:0] ap_reg_ppstg_or_cond_i_i_i_reg_1992_pp0_it5;
reg    ap_sig_bdd_188;
reg    ap_reg_ppiten_pp0_it6 = 1'b0;
reg   [0:0] ap_reg_ppstg_exitcond_reg_1948_pp0_it1;
reg   [0:0] ap_reg_ppstg_exitcond_reg_1948_pp0_it2;
reg   [0:0] ap_reg_ppstg_exitcond_reg_1948_pp0_it3;
reg   [0:0] ap_reg_ppstg_exitcond_reg_1948_pp0_it4;
wire   [10:0] j_V_fu_676_p2;
wire   [0:0] or_cond_i424_i_i_i_fu_727_p2;
wire   [10:0] x_i_fu_748_p3;
reg   [10:0] x_i_reg_1961;
wire   [1:0] col_assign_5_i_fu_760_p2;
reg   [1:0] col_assign_5_i_reg_1966;
reg   [1:0] ap_reg_ppstg_col_assign_5_i_reg_1966_pp0_it1;
wire   [0:0] brmerge_0_i_fu_765_p2;
reg   [0:0] brmerge_0_i_reg_1979;
reg   [0:0] ap_reg_ppstg_brmerge_0_i_reg_1979_pp0_it1;
wire   [0:0] or_cond_i_i_i_fu_770_p2;
reg   [0:0] ap_reg_ppstg_or_cond_i_i_i_reg_1992_pp0_it1;
reg   [0:0] ap_reg_ppstg_or_cond_i_i_i_reg_1992_pp0_it2;
reg   [0:0] ap_reg_ppstg_or_cond_i_i_i_reg_1992_pp0_it3;
reg   [0:0] ap_reg_ppstg_or_cond_i_i_i_reg_1992_pp0_it4;
reg   [10:0] k_buf_0_val_3_addr_reg_1996;
reg   [10:0] k_buf_0_val_4_addr_reg_2002;
reg   [10:0] k_buf_0_val_5_addr_reg_2008;
reg   [10:0] k_buf_1_val_3_addr_reg_2014;
reg   [10:0] k_buf_1_val_4_addr_reg_2020;
reg   [10:0] k_buf_1_val_5_addr_reg_2026;
reg   [10:0] k_buf_2_val_3_addr_reg_2032;
reg   [10:0] k_buf_2_val_4_addr_reg_2038;
reg   [10:0] k_buf_2_val_5_addr_reg_2044;
wire   [7:0] src_kernel_win_0_val_0_0_fu_876_p3;
reg   [7:0] src_kernel_win_0_val_0_0_reg_2050;
reg   [7:0] ap_reg_ppstg_src_kernel_win_0_val_0_0_reg_2050_pp0_it3;
reg   [7:0] ap_reg_ppstg_src_kernel_win_0_val_0_0_reg_2050_pp0_it4;
reg   [7:0] ap_reg_ppstg_src_kernel_win_0_val_0_0_reg_2050_pp0_it5;
wire   [7:0] src_kernel_win_0_val_1_0_fu_894_p3;
reg   [7:0] src_kernel_win_0_val_1_0_reg_2057;
reg   [7:0] ap_reg_ppstg_src_kernel_win_0_val_1_0_reg_2057_pp0_it3;
reg   [7:0] ap_reg_ppstg_src_kernel_win_0_val_1_0_reg_2057_pp0_it4;
wire   [7:0] src_kernel_win_0_val_2_0_fu_912_p3;
reg   [7:0] src_kernel_win_0_val_2_0_reg_2064;
wire   [7:0] src_kernel_win_1_val_0_0_fu_1008_p3;
reg   [7:0] src_kernel_win_1_val_0_0_reg_2071;
reg   [7:0] ap_reg_ppstg_src_kernel_win_1_val_0_0_reg_2071_pp0_it3;
reg   [7:0] ap_reg_ppstg_src_kernel_win_1_val_0_0_reg_2071_pp0_it4;
reg   [7:0] ap_reg_ppstg_src_kernel_win_1_val_0_0_reg_2071_pp0_it5;
wire   [7:0] src_kernel_win_1_val_1_0_fu_1026_p3;
reg   [7:0] src_kernel_win_1_val_1_0_reg_2078;
reg   [7:0] ap_reg_ppstg_src_kernel_win_1_val_1_0_reg_2078_pp0_it3;
reg   [7:0] ap_reg_ppstg_src_kernel_win_1_val_1_0_reg_2078_pp0_it4;
wire   [7:0] src_kernel_win_1_val_2_0_fu_1044_p3;
reg   [7:0] src_kernel_win_1_val_2_0_reg_2085;
wire   [7:0] src_kernel_win_2_val_0_0_fu_1140_p3;
reg   [7:0] src_kernel_win_2_val_0_0_reg_2092;
reg   [7:0] ap_reg_ppstg_src_kernel_win_2_val_0_0_reg_2092_pp0_it3;
reg   [7:0] ap_reg_ppstg_src_kernel_win_2_val_0_0_reg_2092_pp0_it4;
reg   [7:0] ap_reg_ppstg_src_kernel_win_2_val_0_0_reg_2092_pp0_it5;
wire   [7:0] src_kernel_win_2_val_1_0_fu_1158_p3;
reg   [7:0] src_kernel_win_2_val_1_0_reg_2099;
reg   [7:0] ap_reg_ppstg_src_kernel_win_2_val_1_0_reg_2099_pp0_it3;
reg   [7:0] ap_reg_ppstg_src_kernel_win_2_val_1_0_reg_2099_pp0_it4;
wire   [7:0] src_kernel_win_2_val_2_0_fu_1176_p3;
reg   [7:0] src_kernel_win_2_val_2_0_reg_2106;
wire   [7:0] temp_0_i_i_i_059_i_i_1_0_0_2_s_fu_1208_p3;
reg   [7:0] temp_0_i_i_i_059_i_i_1_0_0_2_s_reg_2113;
wire   [7:0] temp_0_i_i_i_059_i_i_1_1_0_2_s_fu_1240_p3;
reg   [7:0] temp_0_i_i_i_059_i_i_1_1_0_2_s_reg_2119;
wire   [7:0] temp_0_i_i_i_059_i_i_1_2_0_2_s_fu_1272_p3;
reg   [7:0] temp_0_i_i_i_059_i_i_1_2_0_2_s_reg_2125;
wire   [7:0] temp_0_i_i_i_059_i_i_1_0_1_1_s_fu_1339_p3;
reg   [7:0] temp_0_i_i_i_059_i_i_1_0_1_1_s_reg_2131;
wire   [0:0] tmp_283_0_1_2_i_fu_1347_p2;
reg   [0:0] tmp_283_0_1_2_i_reg_2136;
wire   [7:0] temp_0_i_i_i_059_i_i_1_1_1_1_s_fu_1376_p3;
reg   [7:0] temp_0_i_i_i_059_i_i_1_1_1_1_s_reg_2141;
wire   [0:0] tmp_283_1_1_2_i_fu_1384_p2;
reg   [0:0] tmp_283_1_1_2_i_reg_2146;
wire   [7:0] temp_0_i_i_i_059_i_i_1_2_1_1_s_fu_1413_p3;
reg   [7:0] temp_0_i_i_i_059_i_i_1_2_1_1_s_reg_2151;
wire   [0:0] tmp_283_2_1_2_i_fu_1421_p2;
reg   [0:0] tmp_283_2_1_2_i_reg_2156;
wire   [7:0] temp_0_i_i_i_059_i_i_1_0_2_1_s_fu_1493_p3;
reg   [7:0] temp_0_i_i_i_059_i_i_1_0_2_1_s_reg_2161;
wire   [7:0] temp_0_i_i_i_059_i_i_1_1_2_1_s_fu_1532_p3;
reg   [7:0] temp_0_i_i_i_059_i_i_1_1_2_1_s_reg_2167;
wire   [7:0] temp_0_i_i_i_059_i_i_1_2_2_1_s_fu_1571_p3;
reg   [7:0] temp_0_i_i_i_059_i_i_1_2_2_1_s_reg_2173;
wire   [10:0] k_buf_0_val_3_address0;
reg    k_buf_0_val_3_ce0;
wire   [7:0] k_buf_0_val_3_q0;
wire   [10:0] k_buf_0_val_3_address1;
reg    k_buf_0_val_3_ce1;
reg    k_buf_0_val_3_we1;
wire   [7:0] k_buf_0_val_3_d1;
wire   [10:0] k_buf_0_val_4_address0;
reg    k_buf_0_val_4_ce0;
wire   [7:0] k_buf_0_val_4_q0;
wire   [10:0] k_buf_0_val_4_address1;
reg    k_buf_0_val_4_ce1;
reg    k_buf_0_val_4_we1;
reg   [7:0] k_buf_0_val_4_d1;
wire   [10:0] k_buf_0_val_5_address0;
reg    k_buf_0_val_5_ce0;
wire   [7:0] k_buf_0_val_5_q0;
wire   [10:0] k_buf_0_val_5_address1;
reg    k_buf_0_val_5_ce1;
reg    k_buf_0_val_5_we1;
reg   [7:0] k_buf_0_val_5_d1;
wire   [10:0] k_buf_1_val_3_address0;
reg    k_buf_1_val_3_ce0;
wire   [7:0] k_buf_1_val_3_q0;
wire   [10:0] k_buf_1_val_3_address1;
reg    k_buf_1_val_3_ce1;
reg    k_buf_1_val_3_we1;
wire   [7:0] k_buf_1_val_3_d1;
wire   [10:0] k_buf_1_val_4_address0;
reg    k_buf_1_val_4_ce0;
wire   [7:0] k_buf_1_val_4_q0;
wire   [10:0] k_buf_1_val_4_address1;
reg    k_buf_1_val_4_ce1;
reg    k_buf_1_val_4_we1;
reg   [7:0] k_buf_1_val_4_d1;
wire   [10:0] k_buf_1_val_5_address0;
reg    k_buf_1_val_5_ce0;
wire   [7:0] k_buf_1_val_5_q0;
wire   [10:0] k_buf_1_val_5_address1;
reg    k_buf_1_val_5_ce1;
reg    k_buf_1_val_5_we1;
reg   [7:0] k_buf_1_val_5_d1;
wire   [10:0] k_buf_2_val_3_address0;
reg    k_buf_2_val_3_ce0;
wire   [7:0] k_buf_2_val_3_q0;
wire   [10:0] k_buf_2_val_3_address1;
reg    k_buf_2_val_3_ce1;
reg    k_buf_2_val_3_we1;
wire   [7:0] k_buf_2_val_3_d1;
wire   [10:0] k_buf_2_val_4_address0;
reg    k_buf_2_val_4_ce0;
wire   [7:0] k_buf_2_val_4_q0;
wire   [10:0] k_buf_2_val_4_address1;
reg    k_buf_2_val_4_ce1;
reg    k_buf_2_val_4_we1;
reg   [7:0] k_buf_2_val_4_d1;
wire   [10:0] k_buf_2_val_5_address0;
reg    k_buf_2_val_5_ce0;
wire   [7:0] k_buf_2_val_5_q0;
wire   [10:0] k_buf_2_val_5_address1;
reg    k_buf_2_val_5_ce1;
reg    k_buf_2_val_5_we1;
reg   [7:0] k_buf_2_val_5_d1;
reg   [1:0] tmp_23_i_reg_446;
reg   [10:0] p_014_0_i_i_i_reg_457;
reg    ap_sig_cseq_ST_st11_fsm_4;
reg    ap_sig_bdd_430;
wire   [63:0] tmp_224_0_i_fu_775_p1;
reg   [7:0] src_kernel_win_0_val_0_1_fu_146;
reg   [7:0] src_kernel_win_0_val_0_1_2_fu_150;
reg   [7:0] src_kernel_win_0_val_1_1_fu_154;
reg   [7:0] src_kernel_win_0_val_1_1_2_fu_158;
reg   [7:0] src_kernel_win_0_val_2_1_fu_162;
reg   [7:0] src_kernel_win_0_val_2_1_2_fu_166;
reg   [7:0] src_kernel_win_1_val_0_1_fu_170;
reg   [7:0] src_kernel_win_1_val_0_1_2_fu_174;
reg   [7:0] src_kernel_win_1_val_1_1_fu_178;
reg   [7:0] src_kernel_win_1_val_1_1_2_fu_182;
reg   [7:0] src_kernel_win_1_val_2_1_fu_186;
reg   [7:0] src_kernel_win_1_val_2_1_2_fu_190;
reg   [7:0] src_kernel_win_2_val_0_1_fu_194;
reg   [7:0] src_kernel_win_2_val_0_1_2_fu_198;
reg   [7:0] src_kernel_win_2_val_1_1_fu_202;
reg   [7:0] src_kernel_win_2_val_1_1_2_fu_206;
reg   [7:0] src_kernel_win_2_val_2_1_fu_210;
reg   [7:0] src_kernel_win_2_val_2_1_2_fu_214;
reg   [7:0] right_border_buf_0_val_0_0_fu_218;
wire   [7:0] col_buf_0_val_0_0_fu_807_p3;
reg   [7:0] right_border_buf_2_val_2_0_fu_222;
wire   [7:0] col_buf_2_val_2_0_fu_1107_p3;
reg   [7:0] right_border_buf_2_val_1_0_fu_226;
wire   [7:0] col_buf_2_val_1_0_fu_1089_p3;
reg   [7:0] right_border_buf_0_val_1_0_fu_230;
wire   [7:0] col_buf_0_val_1_0_fu_825_p3;
reg   [7:0] right_border_buf_2_val_0_0_fu_234;
wire   [7:0] col_buf_2_val_0_0_fu_1071_p3;
reg   [7:0] right_border_buf_1_val_2_0_fu_238;
wire   [7:0] col_buf_1_val_2_0_fu_975_p3;
reg   [7:0] right_border_buf_0_val_2_0_fu_242;
wire   [7:0] col_buf_0_val_2_0_fu_843_p3;
reg   [7:0] right_border_buf_1_val_1_0_fu_246;
wire   [7:0] col_buf_1_val_1_0_fu_957_p3;
reg   [7:0] right_border_buf_1_val_0_0_fu_250;
wire   [7:0] col_buf_1_val_0_0_fu_939_p3;
wire   [1:0] tmp_103_fu_518_p1;
wire   [9:0] tmp_104_fu_553_p4;
wire   [11:0] tmp_33_cast_i_cast_fu_527_p1;
wire   [11:0] tmp_264_0_i_fu_586_p2;
wire   [0:0] tmp_266_0_i_fu_592_p2;
wire   [1:0] tmp_105_fu_597_p1;
wire   [1:0] tmp_s_fu_601_p3;
wire   [11:0] p_assign_12_0_1_i_fu_613_p2;
wire   [0:0] tmp_266_0_1_i_fu_619_p2;
wire   [1:0] tmp_106_fu_624_p1;
wire   [1:0] tmp_59_fu_628_p3;
wire   [11:0] p_assign_12_0_2_i_fu_640_p2;
wire   [0:0] tmp_266_0_2_i_fu_646_p2;
wire   [1:0] tmp_107_fu_651_p1;
wire   [1:0] tmp_60_fu_655_p3;
wire   [9:0] tmp_108_fu_682_p4;
wire   [11:0] tmp_36_cast_i_cast_fu_667_p1;
wire   [11:0] ImagLoc_x_i_fu_698_p2;
wire   [0:0] tmp_110_fu_708_p3;
wire   [0:0] tmp_208_i_fu_722_p2;
wire   [0:0] rev_fu_716_p2;
wire   [0:0] tmp_111_fu_733_p3;
wire   [10:0] tmp_109_fu_704_p1;
wire   [10:0] p_assign_9_i_fu_741_p3;
wire   [1:0] tmp_112_fu_756_p1;
wire   [0:0] icmp2_fu_692_p2;
wire   [7:0] tmp_61_fu_796_p5;
wire   [7:0] tmp_62_fu_814_p5;
wire   [7:0] tmp_63_fu_832_p5;
wire   [7:0] tmp_64_fu_865_p5;
wire   [7:0] tmp_65_fu_883_p5;
wire   [7:0] tmp_66_fu_901_p5;
wire   [7:0] tmp_68_fu_928_p5;
wire   [7:0] tmp_69_fu_946_p5;
wire   [7:0] tmp_70_fu_964_p5;
wire   [7:0] tmp_71_fu_997_p5;
wire   [7:0] tmp_72_fu_1015_p5;
wire   [7:0] tmp_73_fu_1033_p5;
wire   [7:0] tmp_75_fu_1060_p5;
wire   [7:0] tmp_76_fu_1078_p5;
wire   [7:0] tmp_77_fu_1096_p5;
wire   [7:0] tmp_78_fu_1129_p5;
wire   [7:0] tmp_79_fu_1147_p5;
wire   [7:0] tmp_80_fu_1165_p5;
wire   [0:0] tmp_283_0_0_1_i_fu_1189_p2;
wire   [7:0] temp_0_i_i_i_059_i_i_1_0_0_1_s_fu_1195_p3;
wire   [0:0] tmp_283_0_0_2_i_fu_1203_p2;
wire   [0:0] tmp_283_1_0_1_i_fu_1221_p2;
wire   [7:0] temp_0_i_i_i_059_i_i_1_1_0_1_s_fu_1227_p3;
wire   [0:0] tmp_283_1_0_2_i_fu_1235_p2;
wire   [0:0] tmp_283_2_0_1_i_fu_1253_p2;
wire   [7:0] temp_0_i_i_i_059_i_i_1_2_0_1_s_fu_1259_p3;
wire   [0:0] tmp_283_2_0_2_i_fu_1267_p2;
wire   [0:0] tmp_283_0_1_i_fu_1321_p2;
wire   [7:0] temp_0_i_i_i_059_i_i_1_0_1_i_fu_1326_p3;
wire   [0:0] tmp_283_0_1_1_i_fu_1333_p2;
wire   [0:0] tmp_283_1_1_i_fu_1358_p2;
wire   [7:0] temp_0_i_i_i_059_i_i_1_1_1_i_fu_1363_p3;
wire   [0:0] tmp_283_1_1_1_i_fu_1370_p2;
wire   [0:0] tmp_283_2_1_i_fu_1395_p2;
wire   [7:0] temp_0_i_i_i_059_i_i_1_2_1_i_fu_1400_p3;
wire   [0:0] tmp_283_2_1_1_i_fu_1407_p2;
wire   [7:0] temp_0_i_i_i_059_i_i_1_0_1_2_s_fu_1468_p3;
wire   [0:0] tmp_283_0_2_i_fu_1473_p2;
wire   [7:0] temp_0_i_i_i_059_i_i_1_0_2_i_fu_1479_p3;
wire   [0:0] tmp_283_0_2_1_i_fu_1487_p2;
wire   [7:0] temp_0_i_i_i_059_i_i_1_1_1_2_s_fu_1507_p3;
wire   [0:0] tmp_283_1_2_i_fu_1512_p2;
wire   [7:0] temp_0_i_i_i_059_i_i_1_1_2_i_fu_1518_p3;
wire   [0:0] tmp_283_1_2_1_i_fu_1526_p2;
wire   [7:0] temp_0_i_i_i_059_i_i_1_2_1_2_s_fu_1546_p3;
wire   [0:0] tmp_283_2_2_i_fu_1551_p2;
wire   [7:0] temp_0_i_i_i_059_i_i_1_2_2_i_fu_1557_p3;
wire   [0:0] tmp_283_2_2_1_i_fu_1565_p2;
wire   [0:0] tmp_283_0_2_2_i_fu_1615_p2;
wire   [0:0] tmp_283_1_2_2_i_fu_1626_p2;
wire   [0:0] tmp_283_2_2_2_i_fu_1637_p2;
reg   [4:0] ap_NS_fsm;
reg    ap_sig_bdd_1236;
reg    ap_sig_bdd_1238;
reg    ap_sig_bdd_1235;


hls_sobel_Filter2D_k_buf_0_val_3 #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_0_val_3_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( k_buf_0_val_3_address0 ),
    .ce0( k_buf_0_val_3_ce0 ),
    .q0( k_buf_0_val_3_q0 ),
    .address1( k_buf_0_val_3_address1 ),
    .ce1( k_buf_0_val_3_ce1 ),
    .we1( k_buf_0_val_3_we1 ),
    .d1( k_buf_0_val_3_d1 )
);

hls_sobel_Filter2D_k_buf_0_val_3 #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_0_val_4_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( k_buf_0_val_4_address0 ),
    .ce0( k_buf_0_val_4_ce0 ),
    .q0( k_buf_0_val_4_q0 ),
    .address1( k_buf_0_val_4_address1 ),
    .ce1( k_buf_0_val_4_ce1 ),
    .we1( k_buf_0_val_4_we1 ),
    .d1( k_buf_0_val_4_d1 )
);

hls_sobel_Filter2D_k_buf_0_val_3 #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_0_val_5_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( k_buf_0_val_5_address0 ),
    .ce0( k_buf_0_val_5_ce0 ),
    .q0( k_buf_0_val_5_q0 ),
    .address1( k_buf_0_val_5_address1 ),
    .ce1( k_buf_0_val_5_ce1 ),
    .we1( k_buf_0_val_5_we1 ),
    .d1( k_buf_0_val_5_d1 )
);

hls_sobel_Filter2D_k_buf_0_val_3 #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_1_val_3_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( k_buf_1_val_3_address0 ),
    .ce0( k_buf_1_val_3_ce0 ),
    .q0( k_buf_1_val_3_q0 ),
    .address1( k_buf_1_val_3_address1 ),
    .ce1( k_buf_1_val_3_ce1 ),
    .we1( k_buf_1_val_3_we1 ),
    .d1( k_buf_1_val_3_d1 )
);

hls_sobel_Filter2D_k_buf_0_val_3 #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_1_val_4_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( k_buf_1_val_4_address0 ),
    .ce0( k_buf_1_val_4_ce0 ),
    .q0( k_buf_1_val_4_q0 ),
    .address1( k_buf_1_val_4_address1 ),
    .ce1( k_buf_1_val_4_ce1 ),
    .we1( k_buf_1_val_4_we1 ),
    .d1( k_buf_1_val_4_d1 )
);

hls_sobel_Filter2D_k_buf_0_val_3 #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_1_val_5_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( k_buf_1_val_5_address0 ),
    .ce0( k_buf_1_val_5_ce0 ),
    .q0( k_buf_1_val_5_q0 ),
    .address1( k_buf_1_val_5_address1 ),
    .ce1( k_buf_1_val_5_ce1 ),
    .we1( k_buf_1_val_5_we1 ),
    .d1( k_buf_1_val_5_d1 )
);

hls_sobel_Filter2D_k_buf_0_val_3 #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_2_val_3_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( k_buf_2_val_3_address0 ),
    .ce0( k_buf_2_val_3_ce0 ),
    .q0( k_buf_2_val_3_q0 ),
    .address1( k_buf_2_val_3_address1 ),
    .ce1( k_buf_2_val_3_ce1 ),
    .we1( k_buf_2_val_3_we1 ),
    .d1( k_buf_2_val_3_d1 )
);

hls_sobel_Filter2D_k_buf_0_val_3 #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_2_val_4_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( k_buf_2_val_4_address0 ),
    .ce0( k_buf_2_val_4_ce0 ),
    .q0( k_buf_2_val_4_q0 ),
    .address1( k_buf_2_val_4_address1 ),
    .ce1( k_buf_2_val_4_ce1 ),
    .we1( k_buf_2_val_4_we1 ),
    .d1( k_buf_2_val_4_d1 )
);

hls_sobel_Filter2D_k_buf_0_val_3 #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_2_val_5_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( k_buf_2_val_5_address0 ),
    .ce0( k_buf_2_val_5_ce0 ),
    .q0( k_buf_2_val_5_q0 ),
    .address1( k_buf_2_val_5_address1 ),
    .ce1( k_buf_2_val_5_ce1 ),
    .we1( k_buf_2_val_5_we1 ),
    .d1( k_buf_2_val_5_d1 )
);

hls_sobel_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
hls_sobel_mux_3to1_sel2_8_1_U71(
    .din1( right_border_buf_0_val_0_0_fu_218 ),
    .din2( ap_const_lv8_0 ),
    .din3( ap_const_lv8_0 ),
    .din4( ap_reg_ppstg_col_assign_5_i_reg_1966_pp0_it1 ),
    .dout( tmp_61_fu_796_p5 )
);

hls_sobel_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
hls_sobel_mux_3to1_sel2_8_1_U72(
    .din1( right_border_buf_0_val_1_0_fu_230 ),
    .din2( ap_const_lv8_0 ),
    .din3( ap_const_lv8_0 ),
    .din4( ap_reg_ppstg_col_assign_5_i_reg_1966_pp0_it1 ),
    .dout( tmp_62_fu_814_p5 )
);

hls_sobel_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
hls_sobel_mux_3to1_sel2_8_1_U73(
    .din1( right_border_buf_0_val_2_0_fu_242 ),
    .din2( ap_const_lv8_0 ),
    .din3( ap_const_lv8_0 ),
    .din4( ap_reg_ppstg_col_assign_5_i_reg_1966_pp0_it1 ),
    .dout( tmp_63_fu_832_p5 )
);

hls_sobel_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
hls_sobel_mux_3to1_sel2_8_1_U74(
    .din1( col_buf_0_val_0_0_fu_807_p3 ),
    .din2( col_buf_0_val_1_0_fu_825_p3 ),
    .din3( col_buf_0_val_2_0_fu_843_p3 ),
    .din4( row_assign_14_0_i_reg_1927 ),
    .dout( tmp_64_fu_865_p5 )
);

hls_sobel_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
hls_sobel_mux_3to1_sel2_8_1_U75(
    .din1( col_buf_0_val_0_0_fu_807_p3 ),
    .din2( col_buf_0_val_1_0_fu_825_p3 ),
    .din3( col_buf_0_val_2_0_fu_843_p3 ),
    .din4( row_assign_14_0_1_t_i_reg_1934 ),
    .dout( tmp_65_fu_883_p5 )
);

hls_sobel_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
hls_sobel_mux_3to1_sel2_8_1_U76(
    .din1( col_buf_0_val_0_0_fu_807_p3 ),
    .din2( col_buf_0_val_1_0_fu_825_p3 ),
    .din3( col_buf_0_val_2_0_fu_843_p3 ),
    .din4( row_assign_14_0_2_t_i_reg_1941 ),
    .dout( tmp_66_fu_901_p5 )
);

hls_sobel_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
hls_sobel_mux_3to1_sel2_8_1_U77(
    .din1( right_border_buf_1_val_0_0_fu_250 ),
    .din2( ap_const_lv8_0 ),
    .din3( ap_const_lv8_0 ),
    .din4( ap_reg_ppstg_col_assign_5_i_reg_1966_pp0_it1 ),
    .dout( tmp_68_fu_928_p5 )
);

hls_sobel_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
hls_sobel_mux_3to1_sel2_8_1_U78(
    .din1( right_border_buf_1_val_1_0_fu_246 ),
    .din2( ap_const_lv8_0 ),
    .din3( ap_const_lv8_0 ),
    .din4( ap_reg_ppstg_col_assign_5_i_reg_1966_pp0_it1 ),
    .dout( tmp_69_fu_946_p5 )
);

hls_sobel_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
hls_sobel_mux_3to1_sel2_8_1_U79(
    .din1( right_border_buf_1_val_2_0_fu_238 ),
    .din2( ap_const_lv8_0 ),
    .din3( ap_const_lv8_0 ),
    .din4( ap_reg_ppstg_col_assign_5_i_reg_1966_pp0_it1 ),
    .dout( tmp_70_fu_964_p5 )
);

hls_sobel_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
hls_sobel_mux_3to1_sel2_8_1_U80(
    .din1( col_buf_1_val_0_0_fu_939_p3 ),
    .din2( col_buf_1_val_1_0_fu_957_p3 ),
    .din3( col_buf_1_val_2_0_fu_975_p3 ),
    .din4( row_assign_14_0_i_reg_1927 ),
    .dout( tmp_71_fu_997_p5 )
);

hls_sobel_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
hls_sobel_mux_3to1_sel2_8_1_U81(
    .din1( col_buf_1_val_0_0_fu_939_p3 ),
    .din2( col_buf_1_val_1_0_fu_957_p3 ),
    .din3( col_buf_1_val_2_0_fu_975_p3 ),
    .din4( row_assign_14_0_1_t_i_reg_1934 ),
    .dout( tmp_72_fu_1015_p5 )
);

hls_sobel_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
hls_sobel_mux_3to1_sel2_8_1_U82(
    .din1( col_buf_1_val_0_0_fu_939_p3 ),
    .din2( col_buf_1_val_1_0_fu_957_p3 ),
    .din3( col_buf_1_val_2_0_fu_975_p3 ),
    .din4( row_assign_14_0_2_t_i_reg_1941 ),
    .dout( tmp_73_fu_1033_p5 )
);

hls_sobel_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
hls_sobel_mux_3to1_sel2_8_1_U83(
    .din1( right_border_buf_2_val_0_0_fu_234 ),
    .din2( ap_const_lv8_0 ),
    .din3( ap_const_lv8_0 ),
    .din4( ap_reg_ppstg_col_assign_5_i_reg_1966_pp0_it1 ),
    .dout( tmp_75_fu_1060_p5 )
);

hls_sobel_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
hls_sobel_mux_3to1_sel2_8_1_U84(
    .din1( right_border_buf_2_val_1_0_fu_226 ),
    .din2( ap_const_lv8_0 ),
    .din3( ap_const_lv8_0 ),
    .din4( ap_reg_ppstg_col_assign_5_i_reg_1966_pp0_it1 ),
    .dout( tmp_76_fu_1078_p5 )
);

hls_sobel_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
hls_sobel_mux_3to1_sel2_8_1_U85(
    .din1( right_border_buf_2_val_2_0_fu_222 ),
    .din2( ap_const_lv8_0 ),
    .din3( ap_const_lv8_0 ),
    .din4( ap_reg_ppstg_col_assign_5_i_reg_1966_pp0_it1 ),
    .dout( tmp_77_fu_1096_p5 )
);

hls_sobel_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
hls_sobel_mux_3to1_sel2_8_1_U86(
    .din1( col_buf_2_val_0_0_fu_1071_p3 ),
    .din2( col_buf_2_val_1_0_fu_1089_p3 ),
    .din3( col_buf_2_val_2_0_fu_1107_p3 ),
    .din4( row_assign_14_0_i_reg_1927 ),
    .dout( tmp_78_fu_1129_p5 )
);

hls_sobel_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
hls_sobel_mux_3to1_sel2_8_1_U87(
    .din1( col_buf_2_val_0_0_fu_1071_p3 ),
    .din2( col_buf_2_val_1_0_fu_1089_p3 ),
    .din3( col_buf_2_val_2_0_fu_1107_p3 ),
    .din4( row_assign_14_0_1_t_i_reg_1934 ),
    .dout( tmp_79_fu_1147_p5 )
);

hls_sobel_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
hls_sobel_mux_3to1_sel2_8_1_U88(
    .din1( col_buf_2_val_0_0_fu_1071_p3 ),
    .din2( col_buf_2_val_1_0_fu_1089_p3 ),
    .din3( col_buf_2_val_2_0_fu_1107_p3 ),
    .din4( row_assign_14_0_2_t_i_reg_1941 ),
    .dout( tmp_80_fu_1165_p5 )
);



always @ (posedge ap_clk) begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_done_reg
    if (ap_rst == 1'b1) begin
        ap_done_reg <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_continue)) begin
            ap_done_reg <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(ap_const_lv1_0 == exitcond1_fu_531_p2))) begin
            ap_done_reg <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it0
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))) & ~(ap_const_lv1_0 == exitcond_fu_671_p2))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & (ap_const_lv1_0 == exitcond1_fu_531_p2))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it1
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))) & (ap_const_lv1_0 == exitcond_fu_671_p2))) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_1;
        end else if ((((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & (ap_const_lv1_0 == exitcond1_fu_531_p2)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))) & ~(ap_const_lv1_0 == exitcond_fu_671_p2)))) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it2
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it2 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6)))) begin
            ap_reg_ppiten_pp0_it2 <= ap_reg_ppiten_pp0_it1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it3
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it3 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6)))) begin
            ap_reg_ppiten_pp0_it3 <= ap_reg_ppiten_pp0_it2;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it4
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it4 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6)))) begin
            ap_reg_ppiten_pp0_it4 <= ap_reg_ppiten_pp0_it3;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it5
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it5 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6)))) begin
            ap_reg_ppiten_pp0_it5 <= ap_reg_ppiten_pp0_it4;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it6
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it6 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6)))) begin
            ap_reg_ppiten_pp0_it6 <= ap_reg_ppiten_pp0_it5;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & (ap_const_lv1_0 == exitcond1_fu_531_p2))) begin
            ap_reg_ppiten_pp0_it6 <= ap_const_logic_0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_4)) begin
        p_014_0_i_i_i_reg_457 <= i_V_reg_1887;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~(tmp_25_i_fu_493_p2 == ap_const_lv1_0))) begin
        p_014_0_i_i_i_reg_457 <= ap_const_lv11_0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))) & (ap_const_lv1_0 == exitcond_fu_671_p2))) begin
        p_027_0_i_i_i_reg_468 <= j_V_fu_676_p2;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & (ap_const_lv1_0 == exitcond1_fu_531_p2))) begin
        p_027_0_i_i_i_reg_468 <= ap_const_lv11_0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_64)) begin
        tmp_23_i_reg_446 <= ap_const_lv2_0;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (tmp_25_i_fu_493_p2 == ap_const_lv1_0))) begin
        tmp_23_i_reg_446 <= tmp_24_i_fu_487_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))))) begin
        ap_reg_ppstg_brmerge_0_i_reg_1979_pp0_it1 <= brmerge_0_i_reg_1979;
        ap_reg_ppstg_col_assign_5_i_reg_1966_pp0_it1 <= col_assign_5_i_reg_1966;
        ap_reg_ppstg_exitcond_reg_1948_pp0_it1 <= exitcond_reg_1948;
        ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1 <= or_cond_i424_i_i_i_reg_1957;
        ap_reg_ppstg_or_cond_i_i_i_reg_1992_pp0_it1 <= or_cond_i_i_i_reg_1992;
        exitcond_reg_1948 <= exitcond_fu_671_p2;
        k_buf_0_val_3_addr_reg_1996 <= tmp_224_0_i_fu_775_p1;
        k_buf_0_val_4_addr_reg_2002 <= tmp_224_0_i_fu_775_p1;
        k_buf_0_val_5_addr_reg_2008 <= tmp_224_0_i_fu_775_p1;
        k_buf_1_val_3_addr_reg_2014 <= tmp_224_0_i_fu_775_p1;
        k_buf_1_val_4_addr_reg_2020 <= tmp_224_0_i_fu_775_p1;
        k_buf_1_val_5_addr_reg_2026 <= tmp_224_0_i_fu_775_p1;
        k_buf_2_val_3_addr_reg_2032 <= tmp_224_0_i_fu_775_p1;
        k_buf_2_val_4_addr_reg_2038 <= tmp_224_0_i_fu_775_p1;
        k_buf_2_val_5_addr_reg_2044 <= tmp_224_0_i_fu_775_p1;
    end
end

always @ (posedge ap_clk) begin
    if (~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6)))) begin
        ap_reg_ppstg_exitcond_reg_1948_pp0_it2 <= ap_reg_ppstg_exitcond_reg_1948_pp0_it1;
        ap_reg_ppstg_exitcond_reg_1948_pp0_it3 <= ap_reg_ppstg_exitcond_reg_1948_pp0_it2;
        ap_reg_ppstg_exitcond_reg_1948_pp0_it4 <= ap_reg_ppstg_exitcond_reg_1948_pp0_it3;
        ap_reg_ppstg_or_cond_i_i_i_reg_1992_pp0_it2 <= ap_reg_ppstg_or_cond_i_i_i_reg_1992_pp0_it1;
        ap_reg_ppstg_or_cond_i_i_i_reg_1992_pp0_it3 <= ap_reg_ppstg_or_cond_i_i_i_reg_1992_pp0_it2;
        ap_reg_ppstg_or_cond_i_i_i_reg_1992_pp0_it4 <= ap_reg_ppstg_or_cond_i_i_i_reg_1992_pp0_it3;
        ap_reg_ppstg_or_cond_i_i_i_reg_1992_pp0_it5 <= ap_reg_ppstg_or_cond_i_i_i_reg_1992_pp0_it4;
        ap_reg_ppstg_src_kernel_win_0_val_0_0_reg_2050_pp0_it3 <= src_kernel_win_0_val_0_0_reg_2050;
        ap_reg_ppstg_src_kernel_win_0_val_0_0_reg_2050_pp0_it4 <= ap_reg_ppstg_src_kernel_win_0_val_0_0_reg_2050_pp0_it3;
        ap_reg_ppstg_src_kernel_win_0_val_0_0_reg_2050_pp0_it5 <= ap_reg_ppstg_src_kernel_win_0_val_0_0_reg_2050_pp0_it4;
        ap_reg_ppstg_src_kernel_win_0_val_1_0_reg_2057_pp0_it3 <= src_kernel_win_0_val_1_0_reg_2057;
        ap_reg_ppstg_src_kernel_win_0_val_1_0_reg_2057_pp0_it4 <= ap_reg_ppstg_src_kernel_win_0_val_1_0_reg_2057_pp0_it3;
        ap_reg_ppstg_src_kernel_win_1_val_0_0_reg_2071_pp0_it3 <= src_kernel_win_1_val_0_0_reg_2071;
        ap_reg_ppstg_src_kernel_win_1_val_0_0_reg_2071_pp0_it4 <= ap_reg_ppstg_src_kernel_win_1_val_0_0_reg_2071_pp0_it3;
        ap_reg_ppstg_src_kernel_win_1_val_0_0_reg_2071_pp0_it5 <= ap_reg_ppstg_src_kernel_win_1_val_0_0_reg_2071_pp0_it4;
        ap_reg_ppstg_src_kernel_win_1_val_1_0_reg_2078_pp0_it3 <= src_kernel_win_1_val_1_0_reg_2078;
        ap_reg_ppstg_src_kernel_win_1_val_1_0_reg_2078_pp0_it4 <= ap_reg_ppstg_src_kernel_win_1_val_1_0_reg_2078_pp0_it3;
        ap_reg_ppstg_src_kernel_win_2_val_0_0_reg_2092_pp0_it3 <= src_kernel_win_2_val_0_0_reg_2092;
        ap_reg_ppstg_src_kernel_win_2_val_0_0_reg_2092_pp0_it4 <= ap_reg_ppstg_src_kernel_win_2_val_0_0_reg_2092_pp0_it3;
        ap_reg_ppstg_src_kernel_win_2_val_0_0_reg_2092_pp0_it5 <= ap_reg_ppstg_src_kernel_win_2_val_0_0_reg_2092_pp0_it4;
        ap_reg_ppstg_src_kernel_win_2_val_1_0_reg_2099_pp0_it3 <= src_kernel_win_2_val_1_0_reg_2099;
        ap_reg_ppstg_src_kernel_win_2_val_1_0_reg_2099_pp0_it4 <= ap_reg_ppstg_src_kernel_win_2_val_1_0_reg_2099_pp0_it3;
        src_kernel_win_0_val_0_0_reg_2050 <= src_kernel_win_0_val_0_0_fu_876_p3;
        src_kernel_win_0_val_1_0_reg_2057 <= src_kernel_win_0_val_1_0_fu_894_p3;
        src_kernel_win_0_val_2_0_reg_2064 <= src_kernel_win_0_val_2_0_fu_912_p3;
        src_kernel_win_1_val_0_0_reg_2071 <= src_kernel_win_1_val_0_0_fu_1008_p3;
        src_kernel_win_1_val_1_0_reg_2078 <= src_kernel_win_1_val_1_0_fu_1026_p3;
        src_kernel_win_1_val_2_0_reg_2085 <= src_kernel_win_1_val_2_0_fu_1044_p3;
        src_kernel_win_2_val_0_0_reg_2092 <= src_kernel_win_2_val_0_0_fu_1140_p3;
        src_kernel_win_2_val_1_0_reg_2099 <= src_kernel_win_2_val_1_0_fu_1158_p3;
        src_kernel_win_2_val_2_0_reg_2106 <= src_kernel_win_2_val_2_0_fu_1176_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))) & (ap_const_lv1_0 == exitcond_fu_671_p2))) begin
        brmerge_0_i_reg_1979 <= brmerge_0_i_fu_765_p2;
        col_assign_5_i_reg_1966 <= col_assign_5_i_fu_760_p2;
        or_cond_i424_i_i_i_reg_1957 <= or_cond_i424_i_i_i_fu_727_p2;
        or_cond_i_i_i_reg_1992 <= or_cond_i_i_i_fu_770_p2;
        x_i_reg_1961 <= x_i_fu_748_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        i_V_reg_1887 <= i_V_fu_536_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & (ap_const_lv1_0 == exitcond1_fu_531_p2))) begin
        icmp_reg_1901 <= icmp_fu_563_p2;
        row_assign_14_0_1_t_i_reg_1934 <= row_assign_14_0_1_t_i_fu_635_p2;
        row_assign_14_0_2_t_i_reg_1941 <= row_assign_14_0_2_t_i_fu_662_p2;
        row_assign_14_0_i_reg_1927 <= row_assign_14_0_i_fu_608_p2;
        tmp_203_not_0_i_reg_1896 <= tmp_203_not_0_i_fu_547_p2;
        tmp_239_0_2_i_reg_1910 <= tmp_239_0_2_i_fu_575_p2;
        tmp_239_0_i_reg_1906 <= tmp_239_0_i_fu_569_p2;
        tmp_261_0_i_reg_1914 <= tmp_261_0_i_fu_581_p2;
        tmp_35_i_reg_1892 <= tmp_35_i_fu_542_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1) & ~(ap_const_lv1_0 == icmp_reg_1901) & ~(ap_const_lv1_0 == tmp_35_i_reg_1892) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))))) begin
        right_border_buf_0_val_0_0_fu_218 <= col_buf_0_val_0_0_fu_807_p3;
        right_border_buf_0_val_1_0_fu_230 <= col_buf_0_val_1_0_fu_825_p3;
        right_border_buf_0_val_2_0_fu_242 <= col_buf_0_val_2_0_fu_843_p3;
        right_border_buf_1_val_0_0_fu_250 <= col_buf_1_val_0_0_fu_939_p3;
        right_border_buf_1_val_1_0_fu_246 <= col_buf_1_val_1_0_fu_957_p3;
        right_border_buf_1_val_2_0_fu_238 <= col_buf_1_val_2_0_fu_975_p3;
        right_border_buf_2_val_0_0_fu_234 <= col_buf_2_val_0_0_fu_1071_p3;
        right_border_buf_2_val_1_0_fu_226 <= col_buf_2_val_1_0_fu_1089_p3;
        right_border_buf_2_val_2_0_fu_222 <= col_buf_2_val_2_0_fu_1107_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it5) & ~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1948_pp0_it4))) begin
        src_kernel_win_0_val_0_1_2_fu_150 <= src_kernel_win_0_val_0_1_fu_146;
        src_kernel_win_0_val_0_1_fu_146 <= ap_reg_ppstg_src_kernel_win_0_val_0_0_reg_2050_pp0_it4;
        src_kernel_win_1_val_0_1_2_fu_174 <= src_kernel_win_1_val_0_1_fu_170;
        src_kernel_win_1_val_0_1_fu_170 <= ap_reg_ppstg_src_kernel_win_1_val_0_0_reg_2071_pp0_it4;
        src_kernel_win_2_val_0_1_2_fu_198 <= src_kernel_win_2_val_0_1_fu_194;
        src_kernel_win_2_val_0_1_fu_194 <= ap_reg_ppstg_src_kernel_win_2_val_0_0_reg_2092_pp0_it4;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1948_pp0_it3))) begin
        src_kernel_win_0_val_1_1_2_fu_158 <= src_kernel_win_0_val_1_1_fu_154;
        src_kernel_win_0_val_1_1_fu_154 <= ap_reg_ppstg_src_kernel_win_0_val_1_0_reg_2057_pp0_it3;
        src_kernel_win_1_val_1_1_2_fu_182 <= src_kernel_win_1_val_1_1_fu_178;
        src_kernel_win_1_val_1_1_fu_178 <= ap_reg_ppstg_src_kernel_win_1_val_1_0_reg_2078_pp0_it3;
        src_kernel_win_2_val_1_1_2_fu_206 <= src_kernel_win_2_val_1_1_fu_202;
        src_kernel_win_2_val_1_1_fu_202 <= ap_reg_ppstg_src_kernel_win_2_val_1_0_reg_2099_pp0_it3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1948_pp0_it2))) begin
        src_kernel_win_0_val_2_1_2_fu_166 <= src_kernel_win_0_val_2_1_fu_162;
        src_kernel_win_0_val_2_1_fu_162 <= src_kernel_win_0_val_2_0_reg_2064;
        src_kernel_win_1_val_2_1_2_fu_190 <= src_kernel_win_1_val_2_1_fu_186;
        src_kernel_win_1_val_2_1_fu_186 <= src_kernel_win_1_val_2_0_reg_2085;
        src_kernel_win_2_val_2_1_2_fu_214 <= src_kernel_win_2_val_2_1_fu_210;
        src_kernel_win_2_val_2_1_fu_210 <= src_kernel_win_2_val_2_0_reg_2106;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i_i_i_reg_1992_pp0_it2))) begin
        temp_0_i_i_i_059_i_i_1_0_0_2_s_reg_2113 <= temp_0_i_i_i_059_i_i_1_0_0_2_s_fu_1208_p3;
        temp_0_i_i_i_059_i_i_1_1_0_2_s_reg_2119 <= temp_0_i_i_i_059_i_i_1_1_0_2_s_fu_1240_p3;
        temp_0_i_i_i_059_i_i_1_2_0_2_s_reg_2125 <= temp_0_i_i_i_059_i_i_1_2_0_2_s_fu_1272_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i_i_i_reg_1992_pp0_it3))) begin
        temp_0_i_i_i_059_i_i_1_0_1_1_s_reg_2131 <= temp_0_i_i_i_059_i_i_1_0_1_1_s_fu_1339_p3;
        temp_0_i_i_i_059_i_i_1_1_1_1_s_reg_2141 <= temp_0_i_i_i_059_i_i_1_1_1_1_s_fu_1376_p3;
        temp_0_i_i_i_059_i_i_1_2_1_1_s_reg_2151 <= temp_0_i_i_i_059_i_i_1_2_1_1_s_fu_1413_p3;
        tmp_283_0_1_2_i_reg_2136 <= tmp_283_0_1_2_i_fu_1347_p2;
        tmp_283_1_1_2_i_reg_2146 <= tmp_283_1_1_2_i_fu_1384_p2;
        tmp_283_2_1_2_i_reg_2156 <= tmp_283_2_1_2_i_fu_1421_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i_i_i_reg_1992_pp0_it4))) begin
        temp_0_i_i_i_059_i_i_1_0_2_1_s_reg_2161 <= temp_0_i_i_i_059_i_i_1_0_2_1_s_fu_1493_p3;
        temp_0_i_i_i_059_i_i_1_1_2_1_s_reg_2167 <= temp_0_i_i_i_059_i_i_1_1_2_1_s_fu_1532_p3;
        temp_0_i_i_i_059_i_i_1_2_2_1_s_reg_2173 <= temp_0_i_i_i_059_i_i_1_2_2_1_s_fu_1571_p3;
    end
end

always @ (ap_done_reg or exitcond1_fu_531_p2 or ap_sig_cseq_ST_st3_fsm_2) begin
    if (((ap_const_logic_1 == ap_done_reg) | ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(ap_const_lv1_0 == exitcond1_fu_531_p2)))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0) begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

always @ (exitcond1_fu_531_p2 or ap_sig_cseq_ST_st3_fsm_2) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(ap_const_lv1_0 == exitcond1_fu_531_p2))) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_135) begin
    if (ap_sig_bdd_135) begin
        ap_sig_cseq_ST_pp0_stg0_fsm_3 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp0_stg0_fsm_3 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_430) begin
    if (ap_sig_bdd_430) begin
        ap_sig_cseq_ST_st11_fsm_4 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st11_fsm_4 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_24) begin
    if (ap_sig_bdd_24) begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_80) begin
    if (ap_sig_bdd_80) begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_104) begin
    if (ap_sig_bdd_104) begin
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_pp0_stg0_fsm_3 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_166 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_188 or ap_reg_ppiten_pp0_it6) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))))) begin
        k_buf_0_val_3_ce0 = ap_const_logic_1;
    end else begin
        k_buf_0_val_3_ce0 = ap_const_logic_0;
    end
end

always @ (tmp_35_i_reg_1892 or icmp_reg_1901 or tmp_239_0_2_i_reg_1910 or ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1 or ap_sig_bdd_166 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_188 or ap_reg_ppiten_pp0_it6) begin
    if (((~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1) & ~(ap_const_lv1_0 == icmp_reg_1901) & ~(ap_const_lv1_0 == tmp_35_i_reg_1892) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6)))) | (~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1) & (ap_const_lv1_0 == icmp_reg_1901) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))) & ~(ap_const_lv1_0 == tmp_239_0_2_i_reg_1910)))) begin
        k_buf_0_val_3_ce1 = ap_const_logic_1;
    end else begin
        k_buf_0_val_3_ce1 = ap_const_logic_0;
    end
end

always @ (tmp_35_i_reg_1892 or icmp_reg_1901 or tmp_239_0_2_i_reg_1910 or ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1 or ap_sig_bdd_166 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_188 or ap_reg_ppiten_pp0_it6) begin
    if (((~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1) & ~(ap_const_lv1_0 == icmp_reg_1901) & ~(ap_const_lv1_0 == tmp_35_i_reg_1892) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6)))) | (~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1) & (ap_const_lv1_0 == icmp_reg_1901) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))) & ~(ap_const_lv1_0 == tmp_239_0_2_i_reg_1910)))) begin
        k_buf_0_val_3_we1 = ap_const_logic_1;
    end else begin
        k_buf_0_val_3_we1 = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_pp0_stg0_fsm_3 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_166 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_188 or ap_reg_ppiten_pp0_it6) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))))) begin
        k_buf_0_val_4_ce0 = ap_const_logic_1;
    end else begin
        k_buf_0_val_4_ce0 = ap_const_logic_0;
    end
end

always @ (tmp_35_i_reg_1892 or icmp_reg_1901 or tmp_239_0_i_reg_1906 or ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1 or ap_sig_bdd_166 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_188 or ap_reg_ppiten_pp0_it6) begin
    if (((~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1) & ~(ap_const_lv1_0 == icmp_reg_1901) & ~(ap_const_lv1_0 == tmp_35_i_reg_1892) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6)))) | (~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1) & (ap_const_lv1_0 == icmp_reg_1901) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))) & ~(ap_const_lv1_0 == tmp_239_0_i_reg_1906)))) begin
        k_buf_0_val_4_ce1 = ap_const_logic_1;
    end else begin
        k_buf_0_val_4_ce1 = ap_const_logic_0;
    end
end

always @ (p_src_data_stream_0_V_dout or k_buf_0_val_3_q0 or ap_sig_bdd_1236 or ap_sig_bdd_1238 or ap_sig_bdd_1235) begin
    if (ap_sig_bdd_1235) begin
        if (ap_sig_bdd_1238) begin
            k_buf_0_val_4_d1 = k_buf_0_val_3_q0;
        end else if (ap_sig_bdd_1236) begin
            k_buf_0_val_4_d1 = p_src_data_stream_0_V_dout;
        end else begin
            k_buf_0_val_4_d1 = 'bx;
        end
    end else begin
        k_buf_0_val_4_d1 = 'bx;
    end
end

always @ (tmp_35_i_reg_1892 or icmp_reg_1901 or tmp_239_0_i_reg_1906 or ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1 or ap_sig_bdd_166 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_188 or ap_reg_ppiten_pp0_it6) begin
    if (((~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1) & ~(ap_const_lv1_0 == icmp_reg_1901) & ~(ap_const_lv1_0 == tmp_35_i_reg_1892) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6)))) | (~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1) & (ap_const_lv1_0 == icmp_reg_1901) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))) & ~(ap_const_lv1_0 == tmp_239_0_i_reg_1906)))) begin
        k_buf_0_val_4_we1 = ap_const_logic_1;
    end else begin
        k_buf_0_val_4_we1 = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_pp0_stg0_fsm_3 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_166 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_188 or ap_reg_ppiten_pp0_it6) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))))) begin
        k_buf_0_val_5_ce0 = ap_const_logic_1;
    end else begin
        k_buf_0_val_5_ce0 = ap_const_logic_0;
    end
end

always @ (tmp_35_i_reg_1892 or icmp_reg_1901 or tmp_239_0_i_reg_1906 or ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1 or ap_sig_bdd_166 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_188 or ap_reg_ppiten_pp0_it6) begin
    if (((~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1) & ~(ap_const_lv1_0 == icmp_reg_1901) & ~(ap_const_lv1_0 == tmp_35_i_reg_1892) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6)))) | (~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1) & (ap_const_lv1_0 == icmp_reg_1901) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))) & ~(ap_const_lv1_0 == tmp_239_0_i_reg_1906)))) begin
        k_buf_0_val_5_ce1 = ap_const_logic_1;
    end else begin
        k_buf_0_val_5_ce1 = ap_const_logic_0;
    end
end

always @ (p_src_data_stream_0_V_dout or k_buf_0_val_4_q0 or ap_sig_bdd_1236 or ap_sig_bdd_1238 or ap_sig_bdd_1235) begin
    if (ap_sig_bdd_1235) begin
        if (ap_sig_bdd_1238) begin
            k_buf_0_val_5_d1 = k_buf_0_val_4_q0;
        end else if (ap_sig_bdd_1236) begin
            k_buf_0_val_5_d1 = p_src_data_stream_0_V_dout;
        end else begin
            k_buf_0_val_5_d1 = 'bx;
        end
    end else begin
        k_buf_0_val_5_d1 = 'bx;
    end
end

always @ (tmp_35_i_reg_1892 or icmp_reg_1901 or tmp_239_0_i_reg_1906 or ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1 or ap_sig_bdd_166 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_188 or ap_reg_ppiten_pp0_it6) begin
    if (((~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1) & ~(ap_const_lv1_0 == icmp_reg_1901) & ~(ap_const_lv1_0 == tmp_35_i_reg_1892) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6)))) | (~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1) & (ap_const_lv1_0 == icmp_reg_1901) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))) & ~(ap_const_lv1_0 == tmp_239_0_i_reg_1906)))) begin
        k_buf_0_val_5_we1 = ap_const_logic_1;
    end else begin
        k_buf_0_val_5_we1 = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_pp0_stg0_fsm_3 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_166 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_188 or ap_reg_ppiten_pp0_it6) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))))) begin
        k_buf_1_val_3_ce0 = ap_const_logic_1;
    end else begin
        k_buf_1_val_3_ce0 = ap_const_logic_0;
    end
end

always @ (tmp_35_i_reg_1892 or icmp_reg_1901 or tmp_239_0_2_i_reg_1910 or ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1 or ap_sig_bdd_166 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_188 or ap_reg_ppiten_pp0_it6) begin
    if (((~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1) & ~(ap_const_lv1_0 == icmp_reg_1901) & ~(ap_const_lv1_0 == tmp_35_i_reg_1892) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6)))) | (~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1) & (ap_const_lv1_0 == icmp_reg_1901) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))) & ~(ap_const_lv1_0 == tmp_239_0_2_i_reg_1910)))) begin
        k_buf_1_val_3_ce1 = ap_const_logic_1;
    end else begin
        k_buf_1_val_3_ce1 = ap_const_logic_0;
    end
end

always @ (tmp_35_i_reg_1892 or icmp_reg_1901 or tmp_239_0_2_i_reg_1910 or ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1 or ap_sig_bdd_166 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_188 or ap_reg_ppiten_pp0_it6) begin
    if (((~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1) & ~(ap_const_lv1_0 == icmp_reg_1901) & ~(ap_const_lv1_0 == tmp_35_i_reg_1892) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6)))) | (~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1) & (ap_const_lv1_0 == icmp_reg_1901) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))) & ~(ap_const_lv1_0 == tmp_239_0_2_i_reg_1910)))) begin
        k_buf_1_val_3_we1 = ap_const_logic_1;
    end else begin
        k_buf_1_val_3_we1 = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_pp0_stg0_fsm_3 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_166 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_188 or ap_reg_ppiten_pp0_it6) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))))) begin
        k_buf_1_val_4_ce0 = ap_const_logic_1;
    end else begin
        k_buf_1_val_4_ce0 = ap_const_logic_0;
    end
end

always @ (tmp_35_i_reg_1892 or icmp_reg_1901 or tmp_239_0_i_reg_1906 or ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1 or ap_sig_bdd_166 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_188 or ap_reg_ppiten_pp0_it6) begin
    if (((~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1) & ~(ap_const_lv1_0 == icmp_reg_1901) & ~(ap_const_lv1_0 == tmp_35_i_reg_1892) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6)))) | (~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1) & (ap_const_lv1_0 == icmp_reg_1901) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))) & ~(ap_const_lv1_0 == tmp_239_0_i_reg_1906)))) begin
        k_buf_1_val_4_ce1 = ap_const_logic_1;
    end else begin
        k_buf_1_val_4_ce1 = ap_const_logic_0;
    end
end

always @ (p_src_data_stream_1_V_dout or k_buf_1_val_3_q0 or ap_sig_bdd_1236 or ap_sig_bdd_1238 or ap_sig_bdd_1235) begin
    if (ap_sig_bdd_1235) begin
        if (ap_sig_bdd_1238) begin
            k_buf_1_val_4_d1 = k_buf_1_val_3_q0;
        end else if (ap_sig_bdd_1236) begin
            k_buf_1_val_4_d1 = p_src_data_stream_1_V_dout;
        end else begin
            k_buf_1_val_4_d1 = 'bx;
        end
    end else begin
        k_buf_1_val_4_d1 = 'bx;
    end
end

always @ (tmp_35_i_reg_1892 or icmp_reg_1901 or tmp_239_0_i_reg_1906 or ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1 or ap_sig_bdd_166 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_188 or ap_reg_ppiten_pp0_it6) begin
    if (((~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1) & ~(ap_const_lv1_0 == icmp_reg_1901) & ~(ap_const_lv1_0 == tmp_35_i_reg_1892) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6)))) | (~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1) & (ap_const_lv1_0 == icmp_reg_1901) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))) & ~(ap_const_lv1_0 == tmp_239_0_i_reg_1906)))) begin
        k_buf_1_val_4_we1 = ap_const_logic_1;
    end else begin
        k_buf_1_val_4_we1 = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_pp0_stg0_fsm_3 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_166 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_188 or ap_reg_ppiten_pp0_it6) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))))) begin
        k_buf_1_val_5_ce0 = ap_const_logic_1;
    end else begin
        k_buf_1_val_5_ce0 = ap_const_logic_0;
    end
end

always @ (tmp_35_i_reg_1892 or icmp_reg_1901 or tmp_239_0_i_reg_1906 or ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1 or ap_sig_bdd_166 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_188 or ap_reg_ppiten_pp0_it6) begin
    if (((~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1) & ~(ap_const_lv1_0 == icmp_reg_1901) & ~(ap_const_lv1_0 == tmp_35_i_reg_1892) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6)))) | (~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1) & (ap_const_lv1_0 == icmp_reg_1901) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))) & ~(ap_const_lv1_0 == tmp_239_0_i_reg_1906)))) begin
        k_buf_1_val_5_ce1 = ap_const_logic_1;
    end else begin
        k_buf_1_val_5_ce1 = ap_const_logic_0;
    end
end

always @ (p_src_data_stream_1_V_dout or k_buf_1_val_4_q0 or ap_sig_bdd_1236 or ap_sig_bdd_1238 or ap_sig_bdd_1235) begin
    if (ap_sig_bdd_1235) begin
        if (ap_sig_bdd_1238) begin
            k_buf_1_val_5_d1 = k_buf_1_val_4_q0;
        end else if (ap_sig_bdd_1236) begin
            k_buf_1_val_5_d1 = p_src_data_stream_1_V_dout;
        end else begin
            k_buf_1_val_5_d1 = 'bx;
        end
    end else begin
        k_buf_1_val_5_d1 = 'bx;
    end
end

always @ (tmp_35_i_reg_1892 or icmp_reg_1901 or tmp_239_0_i_reg_1906 or ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1 or ap_sig_bdd_166 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_188 or ap_reg_ppiten_pp0_it6) begin
    if (((~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1) & ~(ap_const_lv1_0 == icmp_reg_1901) & ~(ap_const_lv1_0 == tmp_35_i_reg_1892) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6)))) | (~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1) & (ap_const_lv1_0 == icmp_reg_1901) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))) & ~(ap_const_lv1_0 == tmp_239_0_i_reg_1906)))) begin
        k_buf_1_val_5_we1 = ap_const_logic_1;
    end else begin
        k_buf_1_val_5_we1 = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_pp0_stg0_fsm_3 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_166 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_188 or ap_reg_ppiten_pp0_it6) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))))) begin
        k_buf_2_val_3_ce0 = ap_const_logic_1;
    end else begin
        k_buf_2_val_3_ce0 = ap_const_logic_0;
    end
end

always @ (tmp_35_i_reg_1892 or icmp_reg_1901 or tmp_239_0_2_i_reg_1910 or ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1 or ap_sig_bdd_166 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_188 or ap_reg_ppiten_pp0_it6) begin
    if (((~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1) & ~(ap_const_lv1_0 == icmp_reg_1901) & ~(ap_const_lv1_0 == tmp_35_i_reg_1892) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6)))) | (~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1) & (ap_const_lv1_0 == icmp_reg_1901) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))) & ~(ap_const_lv1_0 == tmp_239_0_2_i_reg_1910)))) begin
        k_buf_2_val_3_ce1 = ap_const_logic_1;
    end else begin
        k_buf_2_val_3_ce1 = ap_const_logic_0;
    end
end

always @ (tmp_35_i_reg_1892 or icmp_reg_1901 or tmp_239_0_2_i_reg_1910 or ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1 or ap_sig_bdd_166 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_188 or ap_reg_ppiten_pp0_it6) begin
    if (((~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1) & ~(ap_const_lv1_0 == icmp_reg_1901) & ~(ap_const_lv1_0 == tmp_35_i_reg_1892) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6)))) | (~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1) & (ap_const_lv1_0 == icmp_reg_1901) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))) & ~(ap_const_lv1_0 == tmp_239_0_2_i_reg_1910)))) begin
        k_buf_2_val_3_we1 = ap_const_logic_1;
    end else begin
        k_buf_2_val_3_we1 = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_pp0_stg0_fsm_3 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_166 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_188 or ap_reg_ppiten_pp0_it6) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))))) begin
        k_buf_2_val_4_ce0 = ap_const_logic_1;
    end else begin
        k_buf_2_val_4_ce0 = ap_const_logic_0;
    end
end

always @ (tmp_35_i_reg_1892 or icmp_reg_1901 or tmp_239_0_i_reg_1906 or ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1 or ap_sig_bdd_166 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_188 or ap_reg_ppiten_pp0_it6) begin
    if (((~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1) & ~(ap_const_lv1_0 == icmp_reg_1901) & ~(ap_const_lv1_0 == tmp_35_i_reg_1892) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6)))) | (~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1) & (ap_const_lv1_0 == icmp_reg_1901) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))) & ~(ap_const_lv1_0 == tmp_239_0_i_reg_1906)))) begin
        k_buf_2_val_4_ce1 = ap_const_logic_1;
    end else begin
        k_buf_2_val_4_ce1 = ap_const_logic_0;
    end
end

always @ (p_src_data_stream_2_V_dout or k_buf_2_val_3_q0 or ap_sig_bdd_1236 or ap_sig_bdd_1238 or ap_sig_bdd_1235) begin
    if (ap_sig_bdd_1235) begin
        if (ap_sig_bdd_1238) begin
            k_buf_2_val_4_d1 = k_buf_2_val_3_q0;
        end else if (ap_sig_bdd_1236) begin
            k_buf_2_val_4_d1 = p_src_data_stream_2_V_dout;
        end else begin
            k_buf_2_val_4_d1 = 'bx;
        end
    end else begin
        k_buf_2_val_4_d1 = 'bx;
    end
end

always @ (tmp_35_i_reg_1892 or icmp_reg_1901 or tmp_239_0_i_reg_1906 or ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1 or ap_sig_bdd_166 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_188 or ap_reg_ppiten_pp0_it6) begin
    if (((~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1) & ~(ap_const_lv1_0 == icmp_reg_1901) & ~(ap_const_lv1_0 == tmp_35_i_reg_1892) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6)))) | (~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1) & (ap_const_lv1_0 == icmp_reg_1901) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))) & ~(ap_const_lv1_0 == tmp_239_0_i_reg_1906)))) begin
        k_buf_2_val_4_we1 = ap_const_logic_1;
    end else begin
        k_buf_2_val_4_we1 = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_pp0_stg0_fsm_3 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_166 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_188 or ap_reg_ppiten_pp0_it6) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))))) begin
        k_buf_2_val_5_ce0 = ap_const_logic_1;
    end else begin
        k_buf_2_val_5_ce0 = ap_const_logic_0;
    end
end

always @ (tmp_35_i_reg_1892 or icmp_reg_1901 or tmp_239_0_i_reg_1906 or ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1 or ap_sig_bdd_166 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_188 or ap_reg_ppiten_pp0_it6) begin
    if (((~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1) & ~(ap_const_lv1_0 == icmp_reg_1901) & ~(ap_const_lv1_0 == tmp_35_i_reg_1892) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6)))) | (~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1) & (ap_const_lv1_0 == icmp_reg_1901) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))) & ~(ap_const_lv1_0 == tmp_239_0_i_reg_1906)))) begin
        k_buf_2_val_5_ce1 = ap_const_logic_1;
    end else begin
        k_buf_2_val_5_ce1 = ap_const_logic_0;
    end
end

always @ (p_src_data_stream_2_V_dout or k_buf_2_val_4_q0 or ap_sig_bdd_1236 or ap_sig_bdd_1238 or ap_sig_bdd_1235) begin
    if (ap_sig_bdd_1235) begin
        if (ap_sig_bdd_1238) begin
            k_buf_2_val_5_d1 = k_buf_2_val_4_q0;
        end else if (ap_sig_bdd_1236) begin
            k_buf_2_val_5_d1 = p_src_data_stream_2_V_dout;
        end else begin
            k_buf_2_val_5_d1 = 'bx;
        end
    end else begin
        k_buf_2_val_5_d1 = 'bx;
    end
end

always @ (tmp_35_i_reg_1892 or icmp_reg_1901 or tmp_239_0_i_reg_1906 or ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1 or ap_sig_bdd_166 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_188 or ap_reg_ppiten_pp0_it6) begin
    if (((~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1) & ~(ap_const_lv1_0 == icmp_reg_1901) & ~(ap_const_lv1_0 == tmp_35_i_reg_1892) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6)))) | (~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1) & (ap_const_lv1_0 == icmp_reg_1901) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))) & ~(ap_const_lv1_0 == tmp_239_0_i_reg_1906)))) begin
        k_buf_2_val_5_we1 = ap_const_logic_1;
    end else begin
        k_buf_2_val_5_we1 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_166 or ap_reg_ppiten_pp0_it2 or ap_reg_ppstg_or_cond_i_i_i_reg_1992_pp0_it5 or ap_sig_bdd_188 or ap_reg_ppiten_pp0_it6) begin
    if ((~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i_i_i_reg_1992_pp0_it5) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6) & ~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))))) begin
        p_dst_data_stream_0_V_write = ap_const_logic_1;
    end else begin
        p_dst_data_stream_0_V_write = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_166 or ap_reg_ppiten_pp0_it2 or ap_reg_ppstg_or_cond_i_i_i_reg_1992_pp0_it5 or ap_sig_bdd_188 or ap_reg_ppiten_pp0_it6) begin
    if ((~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i_i_i_reg_1992_pp0_it5) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6) & ~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))))) begin
        p_dst_data_stream_1_V_write = ap_const_logic_1;
    end else begin
        p_dst_data_stream_1_V_write = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_166 or ap_reg_ppiten_pp0_it2 or ap_reg_ppstg_or_cond_i_i_i_reg_1992_pp0_it5 or ap_sig_bdd_188 or ap_reg_ppiten_pp0_it6) begin
    if ((~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i_i_i_reg_1992_pp0_it5) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6) & ~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))))) begin
        p_dst_data_stream_2_V_write = ap_const_logic_1;
    end else begin
        p_dst_data_stream_2_V_write = ap_const_logic_0;
    end
end

always @ (tmp_35_i_reg_1892 or icmp_reg_1901 or ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1 or ap_sig_bdd_166 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_188 or ap_reg_ppiten_pp0_it6) begin
    if (((~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1) & (ap_const_lv1_0 == icmp_reg_1901) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6)))) | (~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1) & ~(ap_const_lv1_0 == icmp_reg_1901) & ~(ap_const_lv1_0 == tmp_35_i_reg_1892) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6)))))) begin
        p_src_data_stream_0_V_read = ap_const_logic_1;
    end else begin
        p_src_data_stream_0_V_read = ap_const_logic_0;
    end
end

always @ (tmp_35_i_reg_1892 or icmp_reg_1901 or ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1 or ap_sig_bdd_166 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_188 or ap_reg_ppiten_pp0_it6) begin
    if (((~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1) & (ap_const_lv1_0 == icmp_reg_1901) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6)))) | (~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1) & ~(ap_const_lv1_0 == icmp_reg_1901) & ~(ap_const_lv1_0 == tmp_35_i_reg_1892) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6)))))) begin
        p_src_data_stream_1_V_read = ap_const_logic_1;
    end else begin
        p_src_data_stream_1_V_read = ap_const_logic_0;
    end
end

always @ (tmp_35_i_reg_1892 or icmp_reg_1901 or ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1 or ap_sig_bdd_166 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_188 or ap_reg_ppiten_pp0_it6) begin
    if (((~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1) & (ap_const_lv1_0 == icmp_reg_1901) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6)))) | (~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1) & ~(ap_const_lv1_0 == icmp_reg_1901) & ~(ap_const_lv1_0 == tmp_35_i_reg_1892) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6)))))) begin
        p_src_data_stream_2_V_read = ap_const_logic_1;
    end else begin
        p_src_data_stream_2_V_read = ap_const_logic_0;
    end
end
always @ (ap_CS_fsm or ap_sig_bdd_64 or tmp_25_i_fu_493_p2 or exitcond1_fu_531_p2 or exitcond_fu_671_p2 or ap_reg_ppiten_pp0_it0 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_166 or ap_reg_ppiten_pp0_it2 or ap_reg_ppiten_pp0_it5 or ap_sig_bdd_188 or ap_reg_ppiten_pp0_it6) begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
        begin
            if (~ap_sig_bdd_64) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_st2_fsm_1 : 
        begin
            if (~(tmp_25_i_fu_493_p2 == ap_const_lv1_0)) begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end else begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end
        end
        ap_ST_st3_fsm_2 : 
        begin
            if (~(ap_const_lv1_0 == exitcond1_fu_531_p2)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_3;
            end
        end
        ap_ST_pp0_stg0_fsm_3 : 
        begin
            if ((~((ap_const_logic_1 == ap_reg_ppiten_pp0_it6) & ~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it5)) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))) & ~(ap_const_lv1_0 == exitcond_fu_671_p2) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_3;
            end else if ((((ap_const_logic_1 == ap_reg_ppiten_pp0_it6) & ~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it5)) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_166 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_188 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))) & ~(ap_const_lv1_0 == exitcond_fu_671_p2) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
                ap_NS_fsm = ap_ST_st11_fsm_4;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_3;
            end
        end
        ap_ST_st11_fsm_4 : 
        begin
            ap_NS_fsm = ap_ST_st3_fsm_2;
        end
        default : 
        begin
            ap_NS_fsm = 'bx;
        end
    endcase
end


assign ImagLoc_x_i_fu_698_p2 = ($signed(ap_const_lv12_FFF) + $signed(tmp_36_cast_i_cast_fu_667_p1));


always @ (ap_CS_fsm) begin
    ap_sig_bdd_104 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_2]);
end


always @ (ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1 or ap_reg_ppiten_pp0_it2) begin
    ap_sig_bdd_1235 = (~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2));
end


always @ (icmp_reg_1901 or tmp_239_0_i_reg_1906) begin
    ap_sig_bdd_1236 = ((ap_const_lv1_0 == icmp_reg_1901) & ~(ap_const_lv1_0 == tmp_239_0_i_reg_1906));
end


always @ (tmp_35_i_reg_1892 or icmp_reg_1901) begin
    ap_sig_bdd_1238 = (~(ap_const_lv1_0 == icmp_reg_1901) & ~(ap_const_lv1_0 == tmp_35_i_reg_1892));
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_135 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_3]);
end


always @ (p_src_data_stream_0_V_empty_n or p_src_data_stream_1_V_empty_n or p_src_data_stream_2_V_empty_n or tmp_35_i_reg_1892 or icmp_reg_1901 or ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1) begin
    ap_sig_bdd_166 = (((p_src_data_stream_0_V_empty_n == ap_const_logic_0) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1) & (ap_const_lv1_0 == icmp_reg_1901)) | ((p_src_data_stream_0_V_empty_n == ap_const_logic_0) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1) & ~(ap_const_lv1_0 == icmp_reg_1901) & ~(ap_const_lv1_0 == tmp_35_i_reg_1892)) | (~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1) & (ap_const_lv1_0 == icmp_reg_1901) & (p_src_data_stream_1_V_empty_n == ap_const_logic_0)) | (~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1) & ~(ap_const_lv1_0 == icmp_reg_1901) & ~(ap_const_lv1_0 == tmp_35_i_reg_1892) & (p_src_data_stream_1_V_empty_n == ap_const_logic_0)) | (~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1) & (ap_const_lv1_0 == icmp_reg_1901) & (p_src_data_stream_2_V_empty_n == ap_const_logic_0)) | (~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i424_i_i_i_reg_1957_pp0_it1) & ~(ap_const_lv1_0 == icmp_reg_1901) & ~(ap_const_lv1_0 == tmp_35_i_reg_1892) & (p_src_data_stream_2_V_empty_n == ap_const_logic_0)));
end


always @ (p_dst_data_stream_0_V_full_n or p_dst_data_stream_1_V_full_n or p_dst_data_stream_2_V_full_n or ap_reg_ppstg_or_cond_i_i_i_reg_1992_pp0_it5) begin
    ap_sig_bdd_188 = (((p_dst_data_stream_0_V_full_n == ap_const_logic_0) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i_i_i_reg_1992_pp0_it5)) | (~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i_i_i_reg_1992_pp0_it5) & (p_dst_data_stream_1_V_full_n == ap_const_logic_0)) | (~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i_i_i_reg_1992_pp0_it5) & (p_dst_data_stream_2_V_full_n == ap_const_logic_0)));
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_24 = (ap_CS_fsm[ap_const_lv32_0] == ap_const_lv1_1);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_430 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_4]);
end


always @ (ap_start or ap_done_reg) begin
    ap_sig_bdd_64 = ((ap_start == ap_const_logic_0) | (ap_done_reg == ap_const_logic_1));
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_80 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_1]);
end

assign brmerge_0_i_fu_765_p2 = (tmp_208_i_fu_722_p2 | tmp_203_not_0_i_reg_1896);

assign col_assign_5_i_fu_760_p2 = (tmp_fu_514_p1 - tmp_112_fu_756_p1);

assign col_buf_0_val_0_0_fu_807_p3 = ((ap_reg_ppstg_brmerge_0_i_reg_1979_pp0_it1[0:0] === 1'b1) ? k_buf_0_val_3_q0 : tmp_61_fu_796_p5);

assign col_buf_0_val_1_0_fu_825_p3 = ((ap_reg_ppstg_brmerge_0_i_reg_1979_pp0_it1[0:0] === 1'b1) ? k_buf_0_val_4_q0 : tmp_62_fu_814_p5);

assign col_buf_0_val_2_0_fu_843_p3 = ((ap_reg_ppstg_brmerge_0_i_reg_1979_pp0_it1[0:0] === 1'b1) ? k_buf_0_val_5_q0 : tmp_63_fu_832_p5);

assign col_buf_1_val_0_0_fu_939_p3 = ((ap_reg_ppstg_brmerge_0_i_reg_1979_pp0_it1[0:0] === 1'b1) ? k_buf_1_val_3_q0 : tmp_68_fu_928_p5);

assign col_buf_1_val_1_0_fu_957_p3 = ((ap_reg_ppstg_brmerge_0_i_reg_1979_pp0_it1[0:0] === 1'b1) ? k_buf_1_val_4_q0 : tmp_69_fu_946_p5);

assign col_buf_1_val_2_0_fu_975_p3 = ((ap_reg_ppstg_brmerge_0_i_reg_1979_pp0_it1[0:0] === 1'b1) ? k_buf_1_val_5_q0 : tmp_70_fu_964_p5);

assign col_buf_2_val_0_0_fu_1071_p3 = ((ap_reg_ppstg_brmerge_0_i_reg_1979_pp0_it1[0:0] === 1'b1) ? k_buf_2_val_3_q0 : tmp_75_fu_1060_p5);

assign col_buf_2_val_1_0_fu_1089_p3 = ((ap_reg_ppstg_brmerge_0_i_reg_1979_pp0_it1[0:0] === 1'b1) ? k_buf_2_val_4_q0 : tmp_76_fu_1078_p5);

assign col_buf_2_val_2_0_fu_1107_p3 = ((ap_reg_ppstg_brmerge_0_i_reg_1979_pp0_it1[0:0] === 1'b1) ? k_buf_2_val_5_q0 : tmp_77_fu_1096_p5);

assign cols_assign_cast_i_cast_fu_483_p1 = cols;

assign exitcond1_fu_531_p2 = (p_014_0_i_i_i_reg_457 == heightloop_fu_499_p2? 1'b1: 1'b0);

assign exitcond_fu_671_p2 = (p_027_0_i_i_i_reg_468 == widthloop_fu_504_p2? 1'b1: 1'b0);

assign heightloop_fu_499_p2 = (ap_const_lv11_2 + rows);

assign i_V_fu_536_p2 = (p_014_0_i_i_i_reg_457 + ap_const_lv11_1);

assign icmp2_fu_692_p2 = (tmp_108_fu_682_p4 != ap_const_lv10_0? 1'b1: 1'b0);

assign icmp_fu_563_p2 = (tmp_104_fu_553_p4 != ap_const_lv10_0? 1'b1: 1'b0);

assign j_V_fu_676_p2 = (p_027_0_i_i_i_reg_468 + ap_const_lv11_1);

assign k_buf_0_val_3_address0 = tmp_224_0_i_fu_775_p1;

assign k_buf_0_val_3_address1 = k_buf_0_val_3_addr_reg_1996;

assign k_buf_0_val_3_d1 = p_src_data_stream_0_V_dout;

assign k_buf_0_val_4_address0 = tmp_224_0_i_fu_775_p1;

assign k_buf_0_val_4_address1 = k_buf_0_val_4_addr_reg_2002;

assign k_buf_0_val_5_address0 = tmp_224_0_i_fu_775_p1;

assign k_buf_0_val_5_address1 = k_buf_0_val_5_addr_reg_2008;

assign k_buf_1_val_3_address0 = tmp_224_0_i_fu_775_p1;

assign k_buf_1_val_3_address1 = k_buf_1_val_3_addr_reg_2014;

assign k_buf_1_val_3_d1 = p_src_data_stream_1_V_dout;

assign k_buf_1_val_4_address0 = tmp_224_0_i_fu_775_p1;

assign k_buf_1_val_4_address1 = k_buf_1_val_4_addr_reg_2020;

assign k_buf_1_val_5_address0 = tmp_224_0_i_fu_775_p1;

assign k_buf_1_val_5_address1 = k_buf_1_val_5_addr_reg_2026;

assign k_buf_2_val_3_address0 = tmp_224_0_i_fu_775_p1;

assign k_buf_2_val_3_address1 = k_buf_2_val_3_addr_reg_2032;

assign k_buf_2_val_3_d1 = p_src_data_stream_2_V_dout;

assign k_buf_2_val_4_address0 = tmp_224_0_i_fu_775_p1;

assign k_buf_2_val_4_address1 = k_buf_2_val_4_addr_reg_2038;

assign k_buf_2_val_5_address0 = tmp_224_0_i_fu_775_p1;

assign k_buf_2_val_5_address1 = k_buf_2_val_5_addr_reg_2044;

assign or_cond_i424_i_i_i_fu_727_p2 = (tmp_208_i_fu_722_p2 & rev_fu_716_p2);

assign or_cond_i_i_i_fu_770_p2 = (icmp_reg_1901 & icmp2_fu_692_p2);

assign p_assign_12_0_1_i_fu_613_p2 = ($signed(ap_const_lv12_FFE) + $signed(tmp_33_cast_i_cast_fu_527_p1));

assign p_assign_12_0_2_i_fu_640_p2 = ($signed(ap_const_lv12_FFD) + $signed(tmp_33_cast_i_cast_fu_527_p1));

assign p_assign_9_i_fu_741_p3 = ((tmp_111_fu_733_p3[0:0] === 1'b1) ? ap_const_lv11_0 : tmp_32_i_fu_509_p2);

assign p_assign_cast_i_fu_521_p2 = ($signed(ap_const_lv2_3) + $signed(tmp_103_fu_518_p1));

assign p_dst_data_stream_0_V_din = ((tmp_283_0_2_2_i_fu_1615_p2[0:0] === 1'b1) ? ap_reg_ppstg_src_kernel_win_0_val_0_0_reg_2050_pp0_it5 : temp_0_i_i_i_059_i_i_1_0_2_1_s_reg_2161);

assign p_dst_data_stream_1_V_din = ((tmp_283_1_2_2_i_fu_1626_p2[0:0] === 1'b1) ? ap_reg_ppstg_src_kernel_win_1_val_0_0_reg_2071_pp0_it5 : temp_0_i_i_i_059_i_i_1_1_2_1_s_reg_2167);

assign p_dst_data_stream_2_V_din = ((tmp_283_2_2_2_i_fu_1637_p2[0:0] === 1'b1) ? ap_reg_ppstg_src_kernel_win_2_val_0_0_reg_2092_pp0_it5 : temp_0_i_i_i_059_i_i_1_2_2_1_s_reg_2173);

assign rev_fu_716_p2 = (tmp_110_fu_708_p3 ^ ap_const_lv1_1);

assign row_assign_14_0_1_t_i_fu_635_p2 = (p_assign_cast_i_fu_521_p2 - tmp_59_fu_628_p3);

assign row_assign_14_0_2_t_i_fu_662_p2 = (p_assign_cast_i_fu_521_p2 - tmp_60_fu_655_p3);

assign row_assign_14_0_i_fu_608_p2 = (p_assign_cast_i_fu_521_p2 - tmp_s_fu_601_p3);

assign rows_assign_cast_i_cast_fu_479_p1 = rows;

assign src_kernel_win_0_val_0_0_fu_876_p3 = ((tmp_261_0_i_reg_1914[0:0] === 1'b1) ? tmp_64_fu_865_p5 : col_buf_0_val_0_0_fu_807_p3);

assign src_kernel_win_0_val_1_0_fu_894_p3 = ((tmp_261_0_i_reg_1914[0:0] === 1'b1) ? tmp_65_fu_883_p5 : col_buf_0_val_1_0_fu_825_p3);

assign src_kernel_win_0_val_2_0_fu_912_p3 = ((tmp_261_0_i_reg_1914[0:0] === 1'b1) ? tmp_66_fu_901_p5 : col_buf_0_val_2_0_fu_843_p3);

assign src_kernel_win_1_val_0_0_fu_1008_p3 = ((tmp_261_0_i_reg_1914[0:0] === 1'b1) ? tmp_71_fu_997_p5 : col_buf_1_val_0_0_fu_939_p3);

assign src_kernel_win_1_val_1_0_fu_1026_p3 = ((tmp_261_0_i_reg_1914[0:0] === 1'b1) ? tmp_72_fu_1015_p5 : col_buf_1_val_1_0_fu_957_p3);

assign src_kernel_win_1_val_2_0_fu_1044_p3 = ((tmp_261_0_i_reg_1914[0:0] === 1'b1) ? tmp_73_fu_1033_p5 : col_buf_1_val_2_0_fu_975_p3);

assign src_kernel_win_2_val_0_0_fu_1140_p3 = ((tmp_261_0_i_reg_1914[0:0] === 1'b1) ? tmp_78_fu_1129_p5 : col_buf_2_val_0_0_fu_1071_p3);

assign src_kernel_win_2_val_1_0_fu_1158_p3 = ((tmp_261_0_i_reg_1914[0:0] === 1'b1) ? tmp_79_fu_1147_p5 : col_buf_2_val_1_0_fu_1089_p3);

assign src_kernel_win_2_val_2_0_fu_1176_p3 = ((tmp_261_0_i_reg_1914[0:0] === 1'b1) ? tmp_80_fu_1165_p5 : col_buf_2_val_2_0_fu_1107_p3);

assign temp_0_i_i_i_059_i_i_1_0_0_1_s_fu_1195_p3 = ((tmp_283_0_0_1_i_fu_1189_p2[0:0] === 1'b1) ? src_kernel_win_0_val_2_1_fu_162 : src_kernel_win_0_val_2_1_2_fu_166);

assign temp_0_i_i_i_059_i_i_1_0_0_2_s_fu_1208_p3 = ((tmp_283_0_0_2_i_fu_1203_p2[0:0] === 1'b1) ? src_kernel_win_0_val_2_0_reg_2064 : temp_0_i_i_i_059_i_i_1_0_0_1_s_fu_1195_p3);

assign temp_0_i_i_i_059_i_i_1_0_1_1_s_fu_1339_p3 = ((tmp_283_0_1_1_i_fu_1333_p2[0:0] === 1'b1) ? src_kernel_win_0_val_1_1_fu_154 : temp_0_i_i_i_059_i_i_1_0_1_i_fu_1326_p3);

assign temp_0_i_i_i_059_i_i_1_0_1_2_s_fu_1468_p3 = ((tmp_283_0_1_2_i_reg_2136[0:0] === 1'b1) ? ap_reg_ppstg_src_kernel_win_0_val_1_0_reg_2057_pp0_it4 : temp_0_i_i_i_059_i_i_1_0_1_1_s_reg_2131);

assign temp_0_i_i_i_059_i_i_1_0_1_i_fu_1326_p3 = ((tmp_283_0_1_i_fu_1321_p2[0:0] === 1'b1) ? src_kernel_win_0_val_1_1_2_fu_158 : temp_0_i_i_i_059_i_i_1_0_0_2_s_reg_2113);

assign temp_0_i_i_i_059_i_i_1_0_2_1_s_fu_1493_p3 = ((tmp_283_0_2_1_i_fu_1487_p2[0:0] === 1'b1) ? src_kernel_win_0_val_0_1_fu_146 : temp_0_i_i_i_059_i_i_1_0_2_i_fu_1479_p3);

assign temp_0_i_i_i_059_i_i_1_0_2_i_fu_1479_p3 = ((tmp_283_0_2_i_fu_1473_p2[0:0] === 1'b1) ? src_kernel_win_0_val_0_1_2_fu_150 : temp_0_i_i_i_059_i_i_1_0_1_2_s_fu_1468_p3);

assign temp_0_i_i_i_059_i_i_1_1_0_1_s_fu_1227_p3 = ((tmp_283_1_0_1_i_fu_1221_p2[0:0] === 1'b1) ? src_kernel_win_1_val_2_1_fu_186 : src_kernel_win_1_val_2_1_2_fu_190);

assign temp_0_i_i_i_059_i_i_1_1_0_2_s_fu_1240_p3 = ((tmp_283_1_0_2_i_fu_1235_p2[0:0] === 1'b1) ? src_kernel_win_1_val_2_0_reg_2085 : temp_0_i_i_i_059_i_i_1_1_0_1_s_fu_1227_p3);

assign temp_0_i_i_i_059_i_i_1_1_1_1_s_fu_1376_p3 = ((tmp_283_1_1_1_i_fu_1370_p2[0:0] === 1'b1) ? src_kernel_win_1_val_1_1_fu_178 : temp_0_i_i_i_059_i_i_1_1_1_i_fu_1363_p3);

assign temp_0_i_i_i_059_i_i_1_1_1_2_s_fu_1507_p3 = ((tmp_283_1_1_2_i_reg_2146[0:0] === 1'b1) ? ap_reg_ppstg_src_kernel_win_1_val_1_0_reg_2078_pp0_it4 : temp_0_i_i_i_059_i_i_1_1_1_1_s_reg_2141);

assign temp_0_i_i_i_059_i_i_1_1_1_i_fu_1363_p3 = ((tmp_283_1_1_i_fu_1358_p2[0:0] === 1'b1) ? src_kernel_win_1_val_1_1_2_fu_182 : temp_0_i_i_i_059_i_i_1_1_0_2_s_reg_2119);

assign temp_0_i_i_i_059_i_i_1_1_2_1_s_fu_1532_p3 = ((tmp_283_1_2_1_i_fu_1526_p2[0:0] === 1'b1) ? src_kernel_win_1_val_0_1_fu_170 : temp_0_i_i_i_059_i_i_1_1_2_i_fu_1518_p3);

assign temp_0_i_i_i_059_i_i_1_1_2_i_fu_1518_p3 = ((tmp_283_1_2_i_fu_1512_p2[0:0] === 1'b1) ? src_kernel_win_1_val_0_1_2_fu_174 : temp_0_i_i_i_059_i_i_1_1_1_2_s_fu_1507_p3);

assign temp_0_i_i_i_059_i_i_1_2_0_1_s_fu_1259_p3 = ((tmp_283_2_0_1_i_fu_1253_p2[0:0] === 1'b1) ? src_kernel_win_2_val_2_1_fu_210 : src_kernel_win_2_val_2_1_2_fu_214);

assign temp_0_i_i_i_059_i_i_1_2_0_2_s_fu_1272_p3 = ((tmp_283_2_0_2_i_fu_1267_p2[0:0] === 1'b1) ? src_kernel_win_2_val_2_0_reg_2106 : temp_0_i_i_i_059_i_i_1_2_0_1_s_fu_1259_p3);

assign temp_0_i_i_i_059_i_i_1_2_1_1_s_fu_1413_p3 = ((tmp_283_2_1_1_i_fu_1407_p2[0:0] === 1'b1) ? src_kernel_win_2_val_1_1_fu_202 : temp_0_i_i_i_059_i_i_1_2_1_i_fu_1400_p3);

assign temp_0_i_i_i_059_i_i_1_2_1_2_s_fu_1546_p3 = ((tmp_283_2_1_2_i_reg_2156[0:0] === 1'b1) ? ap_reg_ppstg_src_kernel_win_2_val_1_0_reg_2099_pp0_it4 : temp_0_i_i_i_059_i_i_1_2_1_1_s_reg_2151);

assign temp_0_i_i_i_059_i_i_1_2_1_i_fu_1400_p3 = ((tmp_283_2_1_i_fu_1395_p2[0:0] === 1'b1) ? src_kernel_win_2_val_1_1_2_fu_206 : temp_0_i_i_i_059_i_i_1_2_0_2_s_reg_2125);

assign temp_0_i_i_i_059_i_i_1_2_2_1_s_fu_1571_p3 = ((tmp_283_2_2_1_i_fu_1565_p2[0:0] === 1'b1) ? src_kernel_win_2_val_0_1_fu_194 : temp_0_i_i_i_059_i_i_1_2_2_i_fu_1557_p3);

assign temp_0_i_i_i_059_i_i_1_2_2_i_fu_1557_p3 = ((tmp_283_2_2_i_fu_1551_p2[0:0] === 1'b1) ? src_kernel_win_2_val_0_1_2_fu_198 : temp_0_i_i_i_059_i_i_1_2_1_2_s_fu_1546_p3);

assign tmp_103_fu_518_p1 = rows[1:0];

assign tmp_104_fu_553_p4 = {{p_014_0_i_i_i_reg_457[ap_const_lv32_A : ap_const_lv32_1]}};

assign tmp_105_fu_597_p1 = tmp_264_0_i_fu_586_p2[1:0];

assign tmp_106_fu_624_p1 = p_assign_12_0_1_i_fu_613_p2[1:0];

assign tmp_107_fu_651_p1 = p_assign_12_0_2_i_fu_640_p2[1:0];

assign tmp_108_fu_682_p4 = {{p_027_0_i_i_i_reg_468[ap_const_lv32_A : ap_const_lv32_1]}};

assign tmp_109_fu_704_p1 = ImagLoc_x_i_fu_698_p2[10:0];

assign tmp_110_fu_708_p3 = ImagLoc_x_i_fu_698_p2[ap_const_lv32_B];

assign tmp_111_fu_733_p3 = ImagLoc_x_i_fu_698_p2[ap_const_lv32_B];

assign tmp_112_fu_756_p1 = x_i_fu_748_p3[1:0];

assign tmp_203_not_0_i_fu_547_p2 = (tmp_35_i_fu_542_p2 ^ ap_const_lv1_1);

assign tmp_208_i_fu_722_p2 = ($signed(ImagLoc_x_i_fu_698_p2) < $signed(cols_assign_cast_i_cast_fu_483_p1)? 1'b1: 1'b0);

assign tmp_224_0_i_fu_775_p1 = x_i_reg_1961;

assign tmp_239_0_2_i_fu_575_p2 = (p_014_0_i_i_i_reg_457 == ap_const_lv11_1? 1'b1: 1'b0);

assign tmp_239_0_i_fu_569_p2 = (p_014_0_i_i_i_reg_457 == ap_const_lv11_0? 1'b1: 1'b0);

assign tmp_24_i_fu_487_p2 = (tmp_23_i_reg_446 + ap_const_lv2_1);

assign tmp_25_i_fu_493_p2 = (tmp_23_i_reg_446 == ap_const_lv2_2? 1'b1: 1'b0);

assign tmp_261_0_i_fu_581_p2 = (p_014_0_i_i_i_reg_457 > rows? 1'b1: 1'b0);

assign tmp_264_0_i_fu_586_p2 = ($signed(ap_const_lv12_FFF) + $signed(tmp_33_cast_i_cast_fu_527_p1));

assign tmp_266_0_1_i_fu_619_p2 = ($signed(p_assign_12_0_1_i_fu_613_p2) < $signed(rows_assign_cast_i_cast_fu_479_p1)? 1'b1: 1'b0);

assign tmp_266_0_2_i_fu_646_p2 = ($signed(p_assign_12_0_2_i_fu_640_p2) < $signed(rows_assign_cast_i_cast_fu_479_p1)? 1'b1: 1'b0);

assign tmp_266_0_i_fu_592_p2 = ($signed(tmp_264_0_i_fu_586_p2) < $signed(rows_assign_cast_i_cast_fu_479_p1)? 1'b1: 1'b0);

assign tmp_283_0_0_1_i_fu_1189_p2 = (src_kernel_win_0_val_2_1_fu_162 < src_kernel_win_0_val_2_1_2_fu_166? 1'b1: 1'b0);

assign tmp_283_0_0_2_i_fu_1203_p2 = (src_kernel_win_0_val_2_0_reg_2064 < temp_0_i_i_i_059_i_i_1_0_0_1_s_fu_1195_p3? 1'b1: 1'b0);

assign tmp_283_0_1_1_i_fu_1333_p2 = (src_kernel_win_0_val_1_1_fu_154 < temp_0_i_i_i_059_i_i_1_0_1_i_fu_1326_p3? 1'b1: 1'b0);

assign tmp_283_0_1_2_i_fu_1347_p2 = (ap_reg_ppstg_src_kernel_win_0_val_1_0_reg_2057_pp0_it3 < temp_0_i_i_i_059_i_i_1_0_1_1_s_fu_1339_p3? 1'b1: 1'b0);

assign tmp_283_0_1_i_fu_1321_p2 = (src_kernel_win_0_val_1_1_2_fu_158 < temp_0_i_i_i_059_i_i_1_0_0_2_s_reg_2113? 1'b1: 1'b0);

assign tmp_283_0_2_1_i_fu_1487_p2 = (src_kernel_win_0_val_0_1_fu_146 < temp_0_i_i_i_059_i_i_1_0_2_i_fu_1479_p3? 1'b1: 1'b0);

assign tmp_283_0_2_2_i_fu_1615_p2 = (ap_reg_ppstg_src_kernel_win_0_val_0_0_reg_2050_pp0_it5 < temp_0_i_i_i_059_i_i_1_0_2_1_s_reg_2161? 1'b1: 1'b0);

assign tmp_283_0_2_i_fu_1473_p2 = (src_kernel_win_0_val_0_1_2_fu_150 < temp_0_i_i_i_059_i_i_1_0_1_2_s_fu_1468_p3? 1'b1: 1'b0);

assign tmp_283_1_0_1_i_fu_1221_p2 = (src_kernel_win_1_val_2_1_fu_186 < src_kernel_win_1_val_2_1_2_fu_190? 1'b1: 1'b0);

assign tmp_283_1_0_2_i_fu_1235_p2 = (src_kernel_win_1_val_2_0_reg_2085 < temp_0_i_i_i_059_i_i_1_1_0_1_s_fu_1227_p3? 1'b1: 1'b0);

assign tmp_283_1_1_1_i_fu_1370_p2 = (src_kernel_win_1_val_1_1_fu_178 < temp_0_i_i_i_059_i_i_1_1_1_i_fu_1363_p3? 1'b1: 1'b0);

assign tmp_283_1_1_2_i_fu_1384_p2 = (ap_reg_ppstg_src_kernel_win_1_val_1_0_reg_2078_pp0_it3 < temp_0_i_i_i_059_i_i_1_1_1_1_s_fu_1376_p3? 1'b1: 1'b0);

assign tmp_283_1_1_i_fu_1358_p2 = (src_kernel_win_1_val_1_1_2_fu_182 < temp_0_i_i_i_059_i_i_1_1_0_2_s_reg_2119? 1'b1: 1'b0);

assign tmp_283_1_2_1_i_fu_1526_p2 = (src_kernel_win_1_val_0_1_fu_170 < temp_0_i_i_i_059_i_i_1_1_2_i_fu_1518_p3? 1'b1: 1'b0);

assign tmp_283_1_2_2_i_fu_1626_p2 = (ap_reg_ppstg_src_kernel_win_1_val_0_0_reg_2071_pp0_it5 < temp_0_i_i_i_059_i_i_1_1_2_1_s_reg_2167? 1'b1: 1'b0);

assign tmp_283_1_2_i_fu_1512_p2 = (src_kernel_win_1_val_0_1_2_fu_174 < temp_0_i_i_i_059_i_i_1_1_1_2_s_fu_1507_p3? 1'b1: 1'b0);

assign tmp_283_2_0_1_i_fu_1253_p2 = (src_kernel_win_2_val_2_1_fu_210 < src_kernel_win_2_val_2_1_2_fu_214? 1'b1: 1'b0);

assign tmp_283_2_0_2_i_fu_1267_p2 = (src_kernel_win_2_val_2_0_reg_2106 < temp_0_i_i_i_059_i_i_1_2_0_1_s_fu_1259_p3? 1'b1: 1'b0);

assign tmp_283_2_1_1_i_fu_1407_p2 = (src_kernel_win_2_val_1_1_fu_202 < temp_0_i_i_i_059_i_i_1_2_1_i_fu_1400_p3? 1'b1: 1'b0);

assign tmp_283_2_1_2_i_fu_1421_p2 = (ap_reg_ppstg_src_kernel_win_2_val_1_0_reg_2099_pp0_it3 < temp_0_i_i_i_059_i_i_1_2_1_1_s_fu_1413_p3? 1'b1: 1'b0);

assign tmp_283_2_1_i_fu_1395_p2 = (src_kernel_win_2_val_1_1_2_fu_206 < temp_0_i_i_i_059_i_i_1_2_0_2_s_reg_2125? 1'b1: 1'b0);

assign tmp_283_2_2_1_i_fu_1565_p2 = (src_kernel_win_2_val_0_1_fu_194 < temp_0_i_i_i_059_i_i_1_2_2_i_fu_1557_p3? 1'b1: 1'b0);

assign tmp_283_2_2_2_i_fu_1637_p2 = (ap_reg_ppstg_src_kernel_win_2_val_0_0_reg_2092_pp0_it5 < temp_0_i_i_i_059_i_i_1_2_2_1_s_reg_2173? 1'b1: 1'b0);

assign tmp_283_2_2_i_fu_1551_p2 = (src_kernel_win_2_val_0_1_2_fu_198 < temp_0_i_i_i_059_i_i_1_2_1_2_s_fu_1546_p3? 1'b1: 1'b0);

assign tmp_32_i_fu_509_p2 = ($signed(ap_const_lv11_7FF) + $signed(cols));

assign tmp_33_cast_i_cast_fu_527_p1 = p_014_0_i_i_i_reg_457;

assign tmp_35_i_fu_542_p2 = (p_014_0_i_i_i_reg_457 < rows? 1'b1: 1'b0);

assign tmp_36_cast_i_cast_fu_667_p1 = p_027_0_i_i_i_reg_468;

assign tmp_59_fu_628_p3 = ((tmp_266_0_1_i_fu_619_p2[0:0] === 1'b1) ? tmp_106_fu_624_p1 : p_assign_cast_i_fu_521_p2);

assign tmp_60_fu_655_p3 = ((tmp_266_0_2_i_fu_646_p2[0:0] === 1'b1) ? tmp_107_fu_651_p1 : p_assign_cast_i_fu_521_p2);

assign tmp_fu_514_p1 = tmp_32_i_fu_509_p2[1:0];

assign tmp_s_fu_601_p3 = ((tmp_266_0_i_fu_592_p2[0:0] === 1'b1) ? tmp_105_fu_597_p1 : p_assign_cast_i_fu_521_p2);

assign widthloop_fu_504_p2 = (ap_const_lv11_2 + cols);

assign x_i_fu_748_p3 = ((or_cond_i424_i_i_i_fu_727_p2[0:0] === 1'b1) ? tmp_109_fu_704_p1 : p_assign_9_i_fu_741_p3);


endmodule //hls_sobel_Erode_32_32_1080_1920_s

