set_property SRC_FILE_INFO {cfile:C:/Users/Dj/Desktop/vivado/miz_sys.srcs/constrs_1/new/Miz_sys_pin.xdc rfile:../../../miz_sys.srcs/constrs_1/new/Miz_sys_pin.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K17 [get_ports HDMI_CLK_P]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L19 [get_ports HDMI_D0_P]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M19 [get_ports HDMI_D1_P]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K19 [get_ports HDMI_D2_P]
