// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module CvtColor (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        rows,
        cols,
        src0_data_stream_0_s_dout,
        src0_data_stream_0_s_empty_n,
        src0_data_stream_0_s_read,
        src0_data_stream_1_s_dout,
        src0_data_stream_1_s_empty_n,
        src0_data_stream_1_s_read,
        src0_data_stream_2_s_dout,
        src0_data_stream_2_s_empty_n,
        src0_data_stream_2_s_read,
        gray_data_stream_0_s_din,
        gray_data_stream_0_s_full_n,
        gray_data_stream_0_s_write
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_pp0_stage0 = 4'd4;
parameter    ap_ST_fsm_state8 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [31:0] rows;
input  [31:0] cols;
input  [7:0] src0_data_stream_0_s_dout;
input   src0_data_stream_0_s_empty_n;
output   src0_data_stream_0_s_read;
input  [7:0] src0_data_stream_1_s_dout;
input   src0_data_stream_1_s_empty_n;
output   src0_data_stream_1_s_read;
input  [7:0] src0_data_stream_2_s_dout;
input   src0_data_stream_2_s_empty_n;
output   src0_data_stream_2_s_read;
output  [7:0] gray_data_stream_0_s_din;
input   gray_data_stream_0_s_full_n;
output   gray_data_stream_0_s_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg src0_data_stream_0_s_read;
reg src0_data_stream_1_s_read;
reg src0_data_stream_2_s_read;
reg gray_data_stream_0_s_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    src0_data_stream_0_s_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] exitcond_i_reg_374;
reg    src0_data_stream_1_s_blk_n;
reg    src0_data_stream_2_s_blk_n;
reg    gray_data_stream_0_s_blk_n;
reg    ap_enable_reg_pp0_iter4;
reg   [0:0] ap_reg_pp0_iter3_exitcond_i_reg_374;
reg   [10:0] j_i_reg_218;
wire   [10:0] rows_4_fu_229_p1;
reg    ap_block_state1;
wire   [10:0] cols_4_fu_233_p1;
wire   [0:0] exitcond1_i_fu_237_p2;
wire    ap_CS_fsm_state2;
wire   [10:0] i_fu_242_p2;
reg   [10:0] i_reg_369;
wire   [0:0] exitcond_i_fu_248_p2;
wire    ap_block_state3_pp0_stage0_iter0;
reg    ap_block_state4_pp0_stage0_iter1;
wire    ap_block_state5_pp0_stage0_iter2;
wire    ap_block_state6_pp0_stage0_iter3;
reg    ap_block_state7_pp0_stage0_iter4;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] ap_reg_pp0_iter1_exitcond_i_reg_374;
reg   [0:0] ap_reg_pp0_iter2_exitcond_i_reg_374;
wire   [10:0] j_fu_253_p2;
reg    ap_enable_reg_pp0_iter0;
reg   [7:0] tmp_45_reg_383;
reg   [7:0] ap_reg_pp0_iter2_tmp_45_reg_383;
reg   [7:0] tmp_46_reg_388;
reg   [7:0] ap_reg_pp0_iter2_tmp_46_reg_388;
reg   [7:0] tmp_47_reg_393;
wire   [28:0] r_V_4_i_i_fu_331_p2;
reg   [28:0] r_V_4_i_i_reg_398;
wire   [29:0] grp_fu_345_p3;
reg   [29:0] r_V_1_reg_403;
reg    ap_enable_reg_pp0_iter3;
reg   [7:0] p_Val2_3_reg_408;
reg   [0:0] tmp_reg_413;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state3;
reg    ap_enable_reg_pp0_iter2;
reg   [10:0] i_i_reg_207;
wire    ap_CS_fsm_state8;
reg    ap_block_pp0_stage0_01001;
wire   [28:0] grp_fu_337_p3;
wire   [7:0] tmp_7_i_i_i_i_fu_287_p1;
wire   [7:0] p_Val2_4_fu_297_p2;
wire   [0:0] tmp_42_fu_290_p3;
wire   [0:0] tmp_43_fu_302_p3;
wire   [0:0] p_Result_2_i_i_i_n_fu_310_p2;
wire   [0:0] not_carry_i_fu_316_p2;
wire   [7:0] r_V_4_i_i_fu_331_p0;
wire   [21:0] r_V_4_i_i_fu_331_p1;
wire   [7:0] grp_fu_337_p0;
wire   [19:0] grp_fu_337_p1;
wire   [7:0] grp_fu_345_p0;
wire   [22:0] grp_fu_345_p1;
wire   [28:0] grp_fu_345_p2;
reg   [3:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire   [27:0] grp_fu_337_p00;
wire   [29:0] grp_fu_345_p00;
wire   [29:0] grp_fu_345_p20;
wire   [28:0] r_V_4_i_i_fu_331_p00;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
end

hls_fast_corner_mbkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 22 ),
    .dout_WIDTH( 29 ))
hls_fast_corner_mbkb_U24(
    .din0(r_V_4_i_i_fu_331_p0),
    .din1(r_V_4_i_i_fu_331_p1),
    .dout(r_V_4_i_i_fu_331_p2)
);

hls_fast_corner_mcud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 20 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
hls_fast_corner_mcud_U25(
    .din0(grp_fu_337_p0),
    .din1(grp_fu_337_p1),
    .din2(r_V_4_i_i_reg_398),
    .dout(grp_fu_337_p3)
);

hls_fast_corner_mdEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 23 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 30 ))
hls_fast_corner_mdEe_U26(
    .din0(grp_fu_345_p0),
    .din1(grp_fu_345_p1),
    .din2(grp_fu_345_p2),
    .dout(grp_fu_345_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((exitcond1_i_fu_237_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state3) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((exitcond1_i_fu_237_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state3)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state3);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end else if (((exitcond1_i_fu_237_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter4 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        i_i_reg_207 <= i_reg_369;
    end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        i_i_reg_207 <= 11'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_i_fu_248_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        j_i_reg_218 <= j_fu_253_p2;
    end else if (((exitcond1_i_fu_237_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        j_i_reg_218 <= 11'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_reg_pp0_iter1_exitcond_i_reg_374 <= exitcond_i_reg_374;
        exitcond_i_reg_374 <= exitcond_i_fu_248_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_reg_pp0_iter2_exitcond_i_reg_374 <= ap_reg_pp0_iter1_exitcond_i_reg_374;
        ap_reg_pp0_iter2_tmp_45_reg_383 <= tmp_45_reg_383;
        ap_reg_pp0_iter2_tmp_46_reg_388 <= tmp_46_reg_388;
        ap_reg_pp0_iter3_exitcond_i_reg_374 <= ap_reg_pp0_iter2_exitcond_i_reg_374;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_reg_369 <= i_fu_242_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_reg_pp0_iter2_exitcond_i_reg_374 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_Val2_3_reg_408 <= {{grp_fu_345_p3[29:22]}};
        tmp_reg_413 <= grp_fu_345_p3[32'd21];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_reg_pp0_iter2_exitcond_i_reg_374 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        r_V_1_reg_403 <= grp_fu_345_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_reg_pp0_iter1_exitcond_i_reg_374 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        r_V_4_i_i_reg_398 <= r_V_4_i_i_fu_331_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_i_reg_374 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_45_reg_383 <= src0_data_stream_0_s_dout;
        tmp_46_reg_388 <= src0_data_stream_1_s_dout;
        tmp_47_reg_393 <= src0_data_stream_2_s_dout;
    end
end

always @ (*) begin
    if ((exitcond_i_fu_248_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state3 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state3 = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond1_i_fu_237_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond1_i_fu_237_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_reg_pp0_iter3_exitcond_i_reg_374 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        gray_data_stream_0_s_blk_n = gray_data_stream_0_s_full_n;
    end else begin
        gray_data_stream_0_s_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_reg_pp0_iter3_exitcond_i_reg_374 == 1'd0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        gray_data_stream_0_s_write = 1'b1;
    end else begin
        gray_data_stream_0_s_write = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond_i_reg_374 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        src0_data_stream_0_s_blk_n = src0_data_stream_0_s_empty_n;
    end else begin
        src0_data_stream_0_s_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((exitcond_i_reg_374 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src0_data_stream_0_s_read = 1'b1;
    end else begin
        src0_data_stream_0_s_read = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond_i_reg_374 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        src0_data_stream_1_s_blk_n = src0_data_stream_1_s_empty_n;
    end else begin
        src0_data_stream_1_s_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((exitcond_i_reg_374 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src0_data_stream_1_s_read = 1'b1;
    end else begin
        src0_data_stream_1_s_read = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond_i_reg_374 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        src0_data_stream_2_s_blk_n = src0_data_stream_2_s_empty_n;
    end else begin
        src0_data_stream_2_s_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((exitcond_i_reg_374 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src0_data_stream_2_s_read = 1'b1;
    end else begin
        src0_data_stream_2_s_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((exitcond1_i_fu_237_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((exitcond_i_fu_248_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone)) & ~((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter3 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter3 == 1'b0)) | ((exitcond_i_fu_248_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone)))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_reg_pp0_iter3_exitcond_i_reg_374 == 1'd0) & (gray_data_stream_0_s_full_n == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((exitcond_i_reg_374 == 1'd0) & (src0_data_stream_2_s_empty_n == 1'b0)) | ((exitcond_i_reg_374 == 1'd0) & (src0_data_stream_1_s_empty_n == 1'b0)) | ((exitcond_i_reg_374 == 1'd0) & (src0_data_stream_0_s_empty_n == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_reg_pp0_iter3_exitcond_i_reg_374 == 1'd0) & (gray_data_stream_0_s_full_n == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((exitcond_i_reg_374 == 1'd0) & (src0_data_stream_2_s_empty_n == 1'b0)) | ((exitcond_i_reg_374 == 1'd0) & (src0_data_stream_1_s_empty_n == 1'b0)) | ((exitcond_i_reg_374 == 1'd0) & (src0_data_stream_0_s_empty_n == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_reg_pp0_iter3_exitcond_i_reg_374 == 1'd0) & (gray_data_stream_0_s_full_n == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((exitcond_i_reg_374 == 1'd0) & (src0_data_stream_2_s_empty_n == 1'b0)) | ((exitcond_i_reg_374 == 1'd0) & (src0_data_stream_1_s_empty_n == 1'b0)) | ((exitcond_i_reg_374 == 1'd0) & (src0_data_stream_0_s_empty_n == 1'b0)))));
end

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state3_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state4_pp0_stage0_iter1 = (((exitcond_i_reg_374 == 1'd0) & (src0_data_stream_2_s_empty_n == 1'b0)) | ((exitcond_i_reg_374 == 1'd0) & (src0_data_stream_1_s_empty_n == 1'b0)) | ((exitcond_i_reg_374 == 1'd0) & (src0_data_stream_0_s_empty_n == 1'b0)));
end

assign ap_block_state5_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state7_pp0_stage0_iter4 = ((ap_reg_pp0_iter3_exitcond_i_reg_374 == 1'd0) & (gray_data_stream_0_s_full_n == 1'b0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign cols_4_fu_233_p1 = cols[10:0];

assign exitcond1_i_fu_237_p2 = ((i_i_reg_207 == rows_4_fu_229_p1) ? 1'b1 : 1'b0);

assign exitcond_i_fu_248_p2 = ((j_i_reg_218 == cols_4_fu_233_p1) ? 1'b1 : 1'b0);

assign gray_data_stream_0_s_din = ((not_carry_i_fu_316_p2[0:0] === 1'b1) ? p_Val2_4_fu_297_p2 : 8'd255);

assign grp_fu_337_p0 = grp_fu_337_p00;

assign grp_fu_337_p00 = ap_reg_pp0_iter2_tmp_45_reg_383;

assign grp_fu_337_p1 = 28'd478150;

assign grp_fu_345_p0 = grp_fu_345_p00;

assign grp_fu_345_p00 = ap_reg_pp0_iter2_tmp_46_reg_388;

assign grp_fu_345_p1 = 30'd2462056;

assign grp_fu_345_p2 = grp_fu_345_p20;

assign grp_fu_345_p20 = grp_fu_337_p3;

assign i_fu_242_p2 = (i_i_reg_207 + 11'd1);

assign j_fu_253_p2 = (j_i_reg_218 + 11'd1);

assign not_carry_i_fu_316_p2 = (tmp_43_fu_302_p3 | p_Result_2_i_i_i_n_fu_310_p2);

assign p_Result_2_i_i_i_n_fu_310_p2 = (tmp_42_fu_290_p3 ^ 1'd1);

assign p_Val2_4_fu_297_p2 = (p_Val2_3_reg_408 + tmp_7_i_i_i_i_fu_287_p1);

assign r_V_4_i_i_fu_331_p0 = r_V_4_i_i_fu_331_p00;

assign r_V_4_i_i_fu_331_p00 = tmp_47_reg_393;

assign r_V_4_i_i_fu_331_p1 = 29'd1254096;

assign rows_4_fu_229_p1 = rows[10:0];

assign tmp_42_fu_290_p3 = r_V_1_reg_403[32'd29];

assign tmp_43_fu_302_p3 = p_Val2_4_fu_297_p2[32'd7];

assign tmp_7_i_i_i_i_fu_287_p1 = tmp_reg_413;

endmodule //CvtColor
