# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Dj/Desktop/vivado/miz_sys.srcs/sources_1/bd/miz_sys/ip/miz_sys_xbar_0/miz_sys_xbar_0.xci
# IP: The module: 'miz_sys_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Dj/Desktop/vivado/miz_sys.srcs/sources_1/bd/miz_sys/ip/miz_sys_xbar_0/miz_sys_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'miz_sys_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/Dj/Desktop/vivado/miz_sys.srcs/sources_1/bd/miz_sys/ip/miz_sys_xbar_0/miz_sys_xbar_0.xci
# IP: The module: 'miz_sys_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Dj/Desktop/vivado/miz_sys.srcs/sources_1/bd/miz_sys/ip/miz_sys_xbar_0/miz_sys_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'miz_sys_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
