# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Miz_sys_pin.xdc

# Block Designs: bd/miz_sys/miz_sys.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==miz_sys || ORIG_REF_NAME==miz_sys} -quiet] -quiet

# IP: bd/miz_sys/ip/miz_sys_processing_system7_0_0/miz_sys_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==miz_sys_processing_system7_0_0 || ORIG_REF_NAME==miz_sys_processing_system7_0_0} -quiet] -quiet

# IP: bd/miz_sys/ip/miz_sys_axi_vdma_0_0/miz_sys_axi_vdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==miz_sys_axi_vdma_0_0 || ORIG_REF_NAME==miz_sys_axi_vdma_0_0} -quiet] -quiet

# IP: bd/miz_sys/ip/miz_sys_axi_mem_intercon_0/miz_sys_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==miz_sys_axi_mem_intercon_0 || ORIG_REF_NAME==miz_sys_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/miz_sys/ip/miz_sys_rst_processing_system7_0_50M_0/miz_sys_rst_processing_system7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==miz_sys_rst_processing_system7_0_50M_0 || ORIG_REF_NAME==miz_sys_rst_processing_system7_0_50M_0} -quiet] -quiet

# IP: bd/miz_sys/ip/miz_sys_processing_system7_0_axi_periph_0/miz_sys_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==miz_sys_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==miz_sys_processing_system7_0_axi_periph_0} -quiet] -quiet

# IP: bd/miz_sys/ip/miz_sys_axi_vdma_1_0/miz_sys_axi_vdma_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==miz_sys_axi_vdma_1_0 || ORIG_REF_NAME==miz_sys_axi_vdma_1_0} -quiet] -quiet

# IP: bd/miz_sys/ip/miz_sys_v_tc_0_0/miz_sys_v_tc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==miz_sys_v_tc_0_0 || ORIG_REF_NAME==miz_sys_v_tc_0_0} -quiet] -quiet

# IP: bd/miz_sys/ip/miz_sys_v_axi4s_vid_out_0_0/miz_sys_v_axi4s_vid_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==miz_sys_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==miz_sys_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/miz_sys/ip/miz_sys_clk_wiz_0_0/miz_sys_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==miz_sys_clk_wiz_0_0 || ORIG_REF_NAME==miz_sys_clk_wiz_0_0} -quiet] -quiet

# IP: bd/miz_sys/ip/miz_sys_HDMI_FPGA_ML_0_0/miz_sys_HDMI_FPGA_ML_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==miz_sys_HDMI_FPGA_ML_0_0 || ORIG_REF_NAME==miz_sys_HDMI_FPGA_ML_0_0} -quiet] -quiet

# IP: bd/miz_sys/ip/miz_sys_util_vector_logic_0_0/miz_sys_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==miz_sys_util_vector_logic_0_0 || ORIG_REF_NAME==miz_sys_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/miz_sys/ip/miz_sys_hls_fast_corner_0_1/miz_sys_hls_fast_corner_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==miz_sys_hls_fast_corner_0_1 || ORIG_REF_NAME==miz_sys_hls_fast_corner_0_1} -quiet] -quiet

# IP: bd/miz_sys/ip/miz_sys_xbar_1/miz_sys_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==miz_sys_xbar_1 || ORIG_REF_NAME==miz_sys_xbar_1} -quiet] -quiet

# IP: bd/miz_sys/ip/miz_sys_xbar_0/miz_sys_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==miz_sys_xbar_0 || ORIG_REF_NAME==miz_sys_xbar_0} -quiet] -quiet

# IP: bd/miz_sys/ip/miz_sys_auto_pc_0/miz_sys_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==miz_sys_auto_pc_0 || ORIG_REF_NAME==miz_sys_auto_pc_0} -quiet] -quiet

# IP: bd/miz_sys/ip/miz_sys_auto_pc_1/miz_sys_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==miz_sys_auto_pc_1 || ORIG_REF_NAME==miz_sys_auto_pc_1} -quiet] -quiet

# XDC: bd/miz_sys/miz_sys_ooc.xdc
